### ISSUE TITLE
Built-in manual wont start

### ISSUE THREAD

**Issue by chiboreache** [godotengine/godot-vscode-plugin#100]
Have an error: `Unable to open 'vscode.previewHtml': resource is not available.`

```
Name: HTML Preview
Id: tht13.html-preview-vscode
Description: Provides ability to preview HTML documents.
Version: 0.2.5
Publisher: Thomas Haakon Townsend
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode
```

Arch Linux

**Comment by chiboreache** [comment]
previewHtml was deprecated btw

https://github.com/Microsoft/vscode/issues/62630

**Comment by chiboreache** [comment]
use webview API instead

**Comment by Geequlim** [comment]
I'm working on the LSP server implementaion of GDScript in godot. After that the LSP client (A new version of the vscode plugin) should fix this problem. I'll find a way to solve this problem or another way to achive this kind of work.

**Comment by chiboreache** [comment]
@Geequlim 
Keep rocking mate! 

Will it fix IntelliSense issue with static typing?

**Comment by Geequlim** [comment]
@chiboreache 
 IntelliSense issue with static typing is fixed in the new version and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'd like to active godot editor and let godot to show the documentations we clicked in the VSCode.
What do thing ?

**Comment by chiboreache** [comment]
@Geequlim thanks mate!

> show the documentations we clicked in the VSCode

that's would be awesome, since VSCode is just simply the best

**Comment by Geequlim** [comment]
The native documentation is now implemented with custom specifications. Documentations are send from the server realtime and renderer as in a spatial webview in VSCode. 

I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
