### ISSUE TITLE
Pseudocode inside comments is considered code and syntax-checked.

### ISSUE THREAD

**Issue by magpie514** [godotengine/godot-vscode-plugin#101]
Using package version 0.3.7
Pseudocode expressions inside comments such as "this checks if (a == 0)" are syntax-checked and return code errors which pollute the list. This might extend to other godot reserved words being used in comments.
Please refer to screenshot for example:
![screenshot1](https://user-images.githubusercontent.com/323651/58408189-96b8e100-806d-11e9-85dc-2638931344ae.png)

**Comment by Geequlim** [comment]
Will be fixed in the next release in this autumn.

Magpie <notifications@github.com>于2019年5月27日 周一16:56写道：

**Comment by magpie514** [comment]
Thank you. :+1:

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
