### ISSUE TITLE
Most of the Godot Tools commands don't work

### ISSUE THREAD

**Issue by cwick** [godotengine/godot-vscode-plugin#109]
VSCode version: 1.37.0
Godot Tools version: 0.3.7
Godot version 3.1.1
OS: Windows 10

All of the Godot Tools commands except for `GodotTools: Update workspace symbols` fail with a non-descript error:

```
Running the contributed command 'godot.runCurrentScene` failed.
Running the contributed command 'godot.openWithEditor` failed.
Running the contributed command 'godot.runWorkspace` failed.
```

I have `GodotTools.editorPath` set to `C:\Users\carme\Desktop\godot.exe`

There's not much information in the Visual Studio code developer console: https://pastebin.com/z5i2nuXE

**Comment by swprojects** [comment]
VSCode version: 1.37.0
Godot Tools version: 0.3.7
Godot version 3.1.1
OS: Windows 10

I have the same issue.


```
{
    "GodotTools.godotVersion": 3,

    "GodotTools.enableSyntaxChecking": true,
    
    // An absolute path pointing at the Godot Editor executable file. Required to run the project and test scenes from VScode
    "GodotTools.editorPath": "F:/godot/godot.exe",
    
    //Control the documentations of workspace symbols should be rendered as plain text or html from markdown
    "GodotTools.workspaceDocumentWithMarkdown": false,

    // // Parse variables defined after indent of not
    "GodotTools.ignoreIndentedVars": false,

    // // Parse scene files with extension ends with tscn
    "GodotTools.parseTextScene": true,

    // // Show node paths of workspace in the code completion
    "GodotTools.completeNodePath": true, 

    // The godot project directory which contains project.godot or engine.cfg
    "GodotTools.godotProjectRoot": "${workspaceRoot}"
}
``

**Comment by thdimk** [comment]
The problem seems to reside (at least for me) on [tool_manager.js](https://github.com/GodotExplorer/godot-tools/blob/master/src/tool_manager.ts#L204) (line 204). Try commenting it out for a quick fix. Nonetheless, this must get fixed.

**Comment by swprojects** [comment]
Though not a fix, I decided to install Godot Tools 0.3.6 and it works.

**Comment by DrPandemic** [comment]
Should be fixed at some point. There's a fix on master right now https://github.com/godotengine/godot-vscode-plugin/commit/0938b6384a844b812003d74ec7f6558d1f8dbc58

**Comment by Geequlim** [comment]
Should be fixed with the new version.
You can try the new version with godot 3.2
https://github.com/godotengine/godot-vscode-plugin/releases/tag/0.9.0

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the release page
