### ISSUE TITLE
"find help" ?

### ISSUE THREAD

**Issue by burstina** [godotengine/godot-vscode-plugin#113]
Hello,
is there a way to show "find help" dialog similar to Godot builtin editor?
thanks

![immagine](https://user-images.githubusercontent.com/47447512/64645034-42ffb700-d414-11e9-8c2a-3a174c4340c0.png)

**Comment by Geequlim** [comment]
This feature is now added in 1.0.0.
You can run command `List native classes of godot` to list classes defined in godot now.

**Comment by burstina** [comment]
that's great!
thanks!
