### ISSUE TITLE
How did you get the documentation?

### ISSUE THREAD

**Issue by grenzionky** [godotengine/godot-vscode-plugin#115]
this isnt a bug, i just cant figure out how this extension managed to have the entire documentation embedded in vscode, and i really want to know how you guys did it.

**Comment by Geequlim** [comment]
In the new version the documentations are sent from the LSP server side in C++ code.
You can also get all the documentations for classes, methods, properties from the `DocData` class

**Comment by marko995** [comment]
How find DocData class ?

**Comment by Geequlim** [comment]
The native documentation preview is now rewrite and should works for godot 3.2.
I'm closing this as the new version has fixed this issue.
