### ISSUE TITLE
Failed connect to GDScript Language Server

### ISSUE THREAD

**Issue by stmckeni** [godotengine/godot-vscode-plugin#119]
I use ubuntu 64 bit 19 and I use the vs code snap from the software store. I also use the godot snap (the snap system has me nervous a bit.) and pairing them up it says the gdscript server failed to connect. what can I do? what am I doing wrong? what do I need to do? is there some trick?

**Comment by Geequlim** [comment]
You have to use godot 3.2 to make the plugin work if  you are using the vscode plugin version 0.9.0

**Comment by stmckeni** [comment]
I figured. I am manually building the godot 3.2 on my ubuntu 19 64 bit. I used scons to build it. Is there any bugs with 3.2 I need to be aware of? I assume 3.2 is still a nightly build.

**Comment by Geequlim** [comment]
You can report to the godot repo if you meet any issue.

**Comment by rodrigofbm** [comment]
I'm facing this issue too
