### ISSUE TITLE
Version 1.0 not available on VS Code's extension-marketplace

### ISSUE THREAD

**Issue by okapii** [godotengine/godot-vscode-plugin#125]
Apologies in advance as I feel this is not really a bug that belongs here but I have no idea where else to ask about this. I tried to create the VSIX-file using vsce but sadly I failed. That being said I am utterly clueless. In an act of desperation I ended up just changing the suffix of the Zip to VSIX which surprisingly sorta worked up to some point. But in the end the extension hardly did what it is intended to. Any chance of getting 1.0 in the extension store or alternatively having a VSIX-file made available for download?

**Comment by Calinou** [comment]
Speaking of which, who has permission to publish new versions of the extension? Since it's now part of the Godot organization, there should probably be a few more people who can do this.

cc @Geequlim

**Comment by Geequlim** [comment]
@okapii The 1.0 will be published to the market store when godot 3.2 stable released.

> Since it's now part of the Godot organization, there should probably be a few more people who can do this.
@Calinou That is a good idea. I can add more publishers to this extension.

**Comment by okapii** [comment]
Makes sense to only publish the extension on the marketplace once Godot 3.2 is released. But wouldn‘t it be a good idea to make it available as a VSIX-file here so that it is gonna be well tested by lotsa users once it is officially released?

**Comment by Calinou** [comment]
Uploading a VSIX to GitHub Releases is considered good practice in general, so I'm in favor of it too.

**Comment by Geequlim** [comment]
I think the 1.0 vsix file is already in the release page of this repo

**Comment by okapii** [comment]
Sorry, my bad!

**Comment by git2013vb** [comment]
> I think the 1.0 vsix file is already in the release page of this repo

Hi,
 Exactly where it is?

Thank you

**Comment by Overblob** [comment]
https://github.com/godotengine/godot-vscode-plugin/releases

**Comment by CornyjK** [comment]
I guess we can close this now.

**Comment by ndarilek** [comment]
If I've installed this from the release archive, will future updates be 
retrieved from the extension marketplace? Or do I need to uninstall and 
reinstall from the marketplace first?

**Comment by Calinou** [comment]
@ndarilek I believe you need to install it from the Marketplace to get automatic updates.

**Comment by do-kevin** [comment]
Hey there,
I want to let you know that this extension is now also available on [Open VSX](https://open-vsx.org/extension/geequlim/godot-tools), which is used by Onivim 2. It hasn't been claimed by an owner and most features aren't supported yet.

**Comment by Calinou** [comment]
@do-kevin I guess https://github.com/godotengine/godot-vscode-plugin/issues/186 can be closed then?

**Comment by do-kevin** [comment]
@Calinou Ah, looks like I should've posted in your issue than here. Sorry about that!

Whether he should claim ownership over Open VSIX, I don't know. But it's probably best if he does.
