### ISSUE TITLE
GDScript type hint keyword should be colored

### ISSUE THREAD

**Issue by safield** [godotengine/godot-vscode-plugin#126]
Plugin version: 0.3.7

Type keywords are not being colored.

Observe the following gdscript code...

`var my_int: int = 1`

In this example it would be ideal if the **int** keyword was colored.

**Comment by DaelonSuzuka** [comment]
This has definitely been implemented:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/d68b30f2-3ac7-4304-8a5c-88b56fe19c9c)
