### ISSUE TITLE
Warning for boolean comparison expressions

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot-vscode-plugin#128]
The below line is warned, and the reason is: "Unhandled comparation expression contains".
```gdscript
print(a == true)
```
This is valid GDScript, so the warning shouldn't be there, right? Also, it seems like the warning message itself is incomplete, and that it's supposed to be "comparison", not "comparation", so it might also need to be re-examined and spell-checked.

EDIT: Seems to be the same issue as #66. The real problem here is that this is happening on my custom functions, so the solution isn't to just patch `print()` either, haha; it was just an example.

**Comment by DaelonSuzuka** [comment]
Closing because this was never an issue with the extension: errors come from the language server running in the Godot Editor.

Also, the language server has improved significantly in recent versions. I doubt this error happens anymore

**Comment by SolarLune** [comment]
> Closing because this was never an issue with the extension: errors come from the language server running in the Godot Editor.
> 
> Also, the language server has improved significantly in recent versions. I doubt this error happens anymore.

Sounds good - did you mean to close this?

**Comment by DaelonSuzuka** [comment]
Must have hit the wrong button, thanks for catching that.
