### ISSUE TITLE
Pressing Ctrl while hovering over a class name opens its reference

### ISSUE THREAD

**Issue by Whiskydog** [godotengine/godot-vscode-plugin#131]
Whenever I -accidentally while trying to copy code- press CTRL key on top of a class name i.e. a constructor, it opens its reference page on the side. It's really annoying when I want to copy code that I selected but left the mouse just on a class name.

Maybe its intended behaviour though.

**Comment by Geequlim** [comment]
As the `reference page` is a spatial feature of the GDScript langugage server there is no such thing in the standart LSP.
It was triggered when resolving native symbols in the language server.
I didn't find a better  way to do this. Maybe we can add an option to disable this feature ?

**Comment by austinried** [comment]
Would be great if this was control+click instead of just having control held down. As it is now I get annoying accidental triggers just by control+clicking my own methods and accidentally hovering over other stuff before control is released.

**Comment by Geequlim** [comment]
Moved the show documentation page notification to go to decleation.

After this commit you can't open documentation page for native symbols by control+click. You have to request `Go To Decleation` form the right click menu. Of cause you can bind your own custom [keybinding](https://code.visualstudio.com/docs/getstarted/keybindings)
Happy coding.

**Comment by austinried** [comment]
Maybe I misunderstood, but is it not possible to remove the behavior where control+click opens the documentation page, but control+hover does not?  That would be ideal IMO.
