### ISSUE TITLE
No parameters suggestions after method or constructor

### ISSUE THREAD

**Issue by Whiskydog** [godotengine/godot-vscode-plugin#132]
Whenever I auto-complete a function or constructor it opens the left parenthesis but it won't show the parameters list like it did before 1.0
This was really helpful since it listed the parameter names you used when declaring functions so it'd be easy to keep up with your code.

**Comment by Calinou** [comment]
@Whiskydog Which Godot version are you using?

**Comment by Geequlim** [comment]
The [Signature Help](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_signatureHelp) of GDScript languange is not implemented yet.

https://github.com/godotengine/godot/pull/31937 Still need some work to do.

@ankitpriyarup are you still going to finish the stuffs like this ?

**Comment by Whiskydog** [comment]
@Calinou I'm using v3.2.beta4.official

**Comment by austinried** [comment]
@Geequlim is this also the reason that when I autocomplete a function like `load()`, it fills in the brackets just like that and puts the cursor after the closing bracket, or is that a separate issue? I would expect it to put the cursor inside the bracket so that I can enter an argument.

**Comment by Geequlim** [comment]
@austinried  the right brackets with one arguments functions is anothor bug will be fix in next godot release.
