### ISSUE TITLE
VSCode doesn't seem to support either multi-line code, or escape characters.

### ISSUE THREAD

**Issue by sleepcircle** [godotengine/godot-vscode-plugin#133]
Writing this in VSCode doesn't react properly when you try to use an escape character on quotes.
```push_error("This code could paint itself into a corner on run-time. Make sure never to start out with a \"return input\" call")```

The above code shows up, in VSCode, like this:
<img width="465" alt="Screen Shot 2019-12-20 at 4 06 29 PM" src="https://user-images.githubusercontent.com/56527438/71293283-e9782400-2342-11ea-9fcd-7a65644c44c0.png">

**Comment by DaelonSuzuka** [comment]
This was because the game's stdout was being incorrectly sent to an output channel. Extension update `2.0.0` move the stdout to the Debug Console tab where it belongs, so now it correctly handles
 all printing.
