### ISSUE TITLE
No autocompletion on extends

### ISSUE THREAD

**Issue by Rinma** [godotengine/godot-vscode-plugin#135]
Hi,

In my GDscript I want to write `extends KinematicBody2D` and I would expect that when I type `extends Kinema` and press `strg+space` that the autocompletion will suggest `KinematicBody2D`. But it doesn't.
I tried it with verison `0.3.7` and with the beta for`1.0.0` for the plugin and Godot `3.1.2` as also `3.2RC1`.

Regards,
Marvin

**Comment by Leleat** [comment]
I am having the same issue with the built-in editor of Godot, so maybe it isn't this plugins fault.
https://github.com/godotengine/godot/issues/36431

**Comment by Haskaris** [comment]
I can't reproduce this issue, as @Leleat said, it was probably not the plugin's fault.

**Comment by cameronpenner** [comment]
As long as I define the types in the base class, inherited classes get autocomplete on inherited properties. I know this is really old, but this could probably be closed.

**Comment by DaelonSuzuka** [comment]
Thanks @cameronpenner, you're right. This works for me on both Godot 3 and 4 now.
