### ISSUE TITLE
Auto Reload Scripts On External Change is not working

### ISSUE THREAD

**Issue by opensw** [godotengine/godot-vscode-plugin#136]
Hello there,
   with Visual Studio Code 1.41.1 (and previous), Godot 3.2 RC2 and gdscript-lsp-vscode-client-1.0.0-beta2 the Auto Reload Scripts On External Change feature (set to true in Godot Editor) is not working. If the code is changed from Godot Editor (no external editor) then this feature is working like expected.

**Comment by tekknovator** [comment]
Linking these issues, as they seem to be connected:
[https://github.com/godotengine/godot/issues/35248](https://github.com/godotengine/godot/issues/35248)

**Comment by jbromberg** [comment]
I'm currently having this issue using vscode and this plugin. When using the native Godot editor, everything works as expected and script changes are immediately reflected while the project is running. If I make a change in vscode, I have to re-run the project to see the changes.

**Comment by atirut-w** [comment]
Try reproducing this issue using a different text editor and see if it's caused by this extension or just using external editors in general.

**Comment by jbromberg** [comment]
Looks like it may be a Godot issue https://github.com/godotengine/godot/issues/72825
