### ISSUE TITLE
Any GodotTools command failed on linux

### ISSUE THREAD

**Issue by sevkin** [godotengine/godot-vscode-plugin#137]
VSCode version: 1.41.1
Godot Tools version: 0.3.7
Godot version 3.1.2
OS: Ubuntu 18.04

plugin crashed with message `TypeError: Cannot read property 'endsWith' of null`

bug in this code:
```typescript
if (shell.endsWith("powershell.exe") && process.platform === "win32") {
    cmdEsc = `&${cmdEsc}`;
}
```
PR ready

**Comment by sevkin** [comment]
please bump to 0.3.8 with this bugfix on vscode marketplace.
40+ peoples in my team wait for it with impatience :heart_eyes:

**Comment by Geequlim** [comment]
@sevkin We are going to publish the new version 1.0 after godot 3.2 stable released.
You can build a vsix from the source and share with your friends locally.
