### ISSUE TITLE
Missing theme selectors for 'in' and '$' keywords

### ISSUE THREAD

**Issue by qez008** [godotengine/godot-vscode-plugin#139]
'in' and '$' keywords are not highlighted like they are in Godot's built in editor.

This is from vs code:
<img width="489" alt="Screenshot 2020-02-01 at 15 15 08" src="https://user-images.githubusercontent.com/46963115/73593556-c629c280-4505-11ea-9de3-18ed1a1b7d50.png">

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-vscode-plugin/pull/274.
