### ISSUE TITLE
No 'words from the current doc' autocompletion

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot-vscode-plugin#14]
For javascript it works like this:

http://stackoverflow.com/questions/31283811/vs-code-autocompletion-base-on-word-in-file
http://stackoverflow.com/questions/30793337/vscode-intellisense-autocomplete-for-javascript

**Comment by PLyczkowski** [comment]
I guess what I mean is support for things like Variables and Fields, Classes, Interfaces, Modules, Properties and Attributes etc in the autocomplete (not sure which of those gdscript uses).

**Comment by Geequlim** [comment]
That is supported by VSCode originally without any plugin

**Comment by PLyczkowski** [comment]
Ah, you are right, I finally found it. It's located in the settings as:

`"editor.quickSuggestions": {
        "strings": true
    },`

**Comment by PLyczkowski** [comment]
Nope, this doesn't find arguments for instance. Example:

![image](https://cloud.githubusercontent.com/assets/7307968/25569231/527a6a62-2e13-11e7-876b-d387ca1569ea.png)

**Comment by Geequlim** [comment]
Some error with function paramaters

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
