### ISSUE TITLE
On-hover symbol information (IntelliSense) popup is broken

### ISSUE THREAD

**Issue by Jakob-PB** [godotengine/godot-vscode-plugin#140]
VS Code version 1.42.0
Godot version 3.2.0

Around the time that 3.2 was released I remember trying out the new version of this plugin and things seemed to be working fine. I could hover over any symbol and get information about it.

However, now it seems that either an update to VS Code or this plugin has broken my ability to see those popups. More specifically the popups seem to appear briefly (for less than a second), in a weird location (not right above the symbol like they normally should). I've tested out a couple other different languages and it seems this problem is isolated to GDscript.

To reproduce simply use the latest version of Godot, VS Code, and this plugin. Then try to hover your mouse over any symbol.

**Comment by Geequlim** [comment]
I can reproduce it after VSCode upgrade to 1.42.0 but I have no idea about this.
The hover information window is displayed and hide within 0.2s that is strange.

**Comment by Geequlim** [comment]
A hot fix release 1.0.2 for godot 3.2 stable is avaliable on VSCode marketplace.
