### ISSUE TITLE
Using certain variable names for locals/members confuses parser if they are in the documentation

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot-vscode-plugin#145]
Case in point:
![image](https://user-images.githubusercontent.com/2823241/74598923-822bd700-5048-11ea-8f23-dd76bdfa34af.png)

Whereas it's a Vector2 that's being created locally.

**Comment by DaelonSuzuka** [comment]
Closing because:

1: This is a language server problem and not an extension problem
2: Godot 4 is much better at resolving types when using `:=`
