### ISSUE TITLE
Add syntax highlighting for import files

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot-vscode-plugin#153]
Files such as `icon.png.import` currently don't have syntax highlighting. While obviously this is a low priority, it would be nice if there was syntax highlighting for these files. Or, at the very least, list `.import` as a supported extension to stop VS Code from suggesting extensions on the marketplace.

**Comment by Calinou** [comment]
I suppose an INI syntax highlighting file work work well for those.

**Comment by rakkarage** [comment]
"files.associations": {
		"*.import": "ini",
	},

yes please! but this works for now
