### ISSUE TITLE
Have no the  Command  to run the script or open the editor.

### ISSUE THREAD

**Issue by PaulsonH** [godotengine/godot-vscode-plugin#155]
![image](https://user-images.githubusercontent.com/35858134/75699155-f32aea00-5cea-11ea-9e13-5bbcf9350be5.png)
have no the commands to open the editor.

**Comment by DaelonSuzuka** [comment]
![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/7cb5362b-56ca-4ff1-87f3-b506a1fd7cbe)
