### ISSUE TITLE
Go to symbol in workspace doesn't work

### ISSUE THREAD

**Issue by lohmaster** [godotengine/godot-vscode-plugin#157]
All symbols are correctly listed. Clicking on them produces error : "Unable to open 'filename.gd': resource is not available.". Happens both when the symbol in question is in currently opened and when it is in different file.
plugin version 1.0.3
Happens in godot3.2 and 3.2.1-rc1

**Comment by DaelonSuzuka** [comment]
This definitely works now:

![Code_D4WkhxrvS6](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/afd7902e-a843-4076-b980-5d61b0e55fd6)

**Comment by cutecycle** [comment]
This seems to be happening for me? 

File: 

<img width="1003" height="348" alt="Image" src="https://github.com/user-attachments/assets/3777ac36-a840-453e-aa42-a219902364a5" />

workspace: 

<img width="1040" height="120" alt="Image" src="https://github.com/user-attachments/assets/04d4dfe2-bdec-4092-8924-87db60281b92" />
