### ISSUE TITLE
External enum reference highlight doesn't work

### ISSUE THREAD

**Issue by Nubilous** [godotengine/godot-vscode-plugin#158]
If I declare an enum in class A and reference that enum in class B, only the first character of the enum is highlighted, the rest is not. 

```
class_name TestA

enum SomeEnum {
    SAMPLE_ONE,
    SAMPLE_TWO
}
```

```
class_name TestB

func _init()
    var value = TestA.SomeEnum.SAMPLE_ONE
```

![image](https://user-images.githubusercontent.com/906629/75968922-73f60b80-5ece-11ea-9f37-72b511b1cb7d.png)

**Comment by DaelonSuzuka** [comment]
The syntax highlighting has all been fixed.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/2e8b66bf-55d3-49a4-9f7e-e5ff8f4ba4da)

Technically, the enum should be marked light blue, but that would require semantic tokenization to be supported by the language server. Maybe one day..
