### ISSUE TITLE
Syntax highlighting and auto-completion not working

### ISSUE THREAD

**Issue by SuzukaDev** [godotengine/godot-vscode-plugin#160]
Hi.
I'm having problems with the syntax highlighting and auto-completion.

Godot opens the .gd files without problems, and seems to be connected to the server:
![gtbg](https://user-images.githubusercontent.com/52723367/77234743-24dbf600-6bb1-11ea-87dd-148da1a6a760.jpg)

I don't know what happens and what to do. Any idea? Is it a bug?

I'm using:
Windows 7
Godot 3.2.1 stable
Godot tools v1.0.3

Also tried to instal Godot tools v1.0.1 and nothing, I had the same problem

**Comment by Calinou** [comment]
Which syntax theme are you using? Try switching to the default Dark+ theme and see if you can see syntax highlighting correctly.

**Comment by SuzukaDev** [comment]
Aw.. Yes, it was that. Now both syntax higlighting and auto-completion works.
Thank you so much @Calinou !

**Comment by Calinou** [comment]
I'll close this issue as it doesn't appear to be a bug within the plugin. You may want to create an issue on the syntax theme's repository though :slightly_smiling_face:
