### ISSUE TITLE
Cannot find a project.godot in active workspace

### ISSUE THREAD

**Issue by c0ppo** [godotengine/godot-vscode-plugin#167]
Greetings,

I'm having an issue with Godot (flatpak) + VSCode (snap) + this plugin. I'm running Ubuntu 20.04. So I've installed this plugin, and when I run it from Godot, VS Code opens, I get code completion and everything. But if I try to debug with CTRL+F5 in VS Code, I get an error saying:

`Cannot find a project.godot in active workspace`

I guess something in my configuration isn't installed correctly. I've tried everything to correct this issue, but failed. Has anyone any idea on how to set this up?

**Comment by Razoric480** [comment]
Make sure to generate a launch.json file - you can do so by going to the debug panel and create a launch.json file and selecting Godot.

I'll have to investigate why it can't start a debugging session off the default values without a launch.json. I thought I configured it correctly.

**Comment by Razoric480** [comment]
There is a bug in the default configuration provider where it doesn't use the full filepath. I'll issue a fix for it so that way, launch.json will be optional.
