### ISSUE TITLE
Auto open when switch scene

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-vscode-plugin#172]
HI, 
I'm not sure if I can write here this issue or is related to Godot editor.
I'm using C# and 3.2.1 stable.mono in Debian 10.
When I switch between scenes in Godot editor if that scene have a C# script attached Visual Studio Code popup on top of Godot editor.
It is possible to have some setting that allow me to open Visual Studio Code only when I click in Icon script in the Godot editor?

Thank you

**Comment by git2013vb** [comment]
I know that is a difficult question and low priority  =) 
However I found a workaround in the meantime:
![image](https://user-images.githubusercontent.com/13235119/81541520-2339dd80-936b-11ea-90fe-743bb4e44c37.png)

This settings solved my problem for now. I was lucky I guess - like always. =)

**Comment by Calinou** [comment]
This is a bug/limitation in the engine which has already been reported on the main Godot repository. It's not related to this extension, so I'll close this issue.
