### ISSUE TITLE
Output text does not get displayed

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot-vscode-plugin#173]
The output window for the debugger never gets created, due to an oversight while I was refactoring code. PR will be made shortly.

**Comment by tom-dreamviewer** [comment]
Still got same bug on VSCode 1.45.1 MacOS 10.14.6 with Godot Tools 1.1.0

**Comment by Razoric480** [comment]
Yes, it's not working in 1.1.0, but the fix is part of 1.1.1.

**Comment by Shfty** [comment]
Any news on when 1.1.1 will be released? This fix is the last barrier to fully moving my dev workflow over to VS Code.

**Comment by Razoric480** [comment]
Probably when 3.2 comes out. For now, if you check #175, you can find a VSIX file in a zip file I compiled. It includes other fixes to the debugger and other stuff that have been pulled.
