### ISSUE TITLE
launch_scene file property starts with godot launch screen

### ISSUE THREAD

**Issue by Mootook** [godotengine/godot-vscode-plugin#176]
In my launch.json I have `launch_game_instance: true` and `launch_scene: true`, but putting `scene_file` to any tscn launches another godot editor at the project selection window 

here is a my launch.json 
```
"configurations": [
    {
      "name": "Godot",
      "type": "godot",
      "request": "launch",
      "project": "D:/Game Development/git/tyf/Godot/",
      "port": 6007,
      "address": "127.0.0.1",
      "launch_game_instance": true,
      "launch_scene": true,
      "scene_file": "./Nodes/Assets/Player/Player.tscn"
    }
```
![Screenshot (25)](https://user-images.githubusercontent.com/42306342/81487420-65e7a280-9211-11ea-8459-27f0d99c4260.png)

Note: This works if I have `Player.tscn` highlighted in an open pane and sccne_file removed from launch.json.

**Comment by Calinou** [comment]
Does it work if you remove `./` at the beginning of the `scene_file` path?

**Comment by Mootook** [comment]
No, same result have tried against multiple tscns and even relocated some to root dir and still same result.

**Comment by Calinou** [comment]
It sounds like Godot is not accepting the positional command-line argument somehow. Does it work if you use backslashes as a path separator instead of forward slashes? (These must be written as `\\` in the JSON file to be escaped.)

**Comment by Mootook** [comment]
` "Nodes\\Assets\\Player\\Player.tscn"` didn't make a difference

**Comment by Razoric480** [comment]
There was a bug in how I used the scene filename. I didn't catch it at the time because of some very particular testing setup that masked the issue.

I'll issue a fix shortly.
