### ISSUE TITLE
Can't connect to language server with Godot 3.2.2 beta 2

### ISSUE THREAD

**Issue by okapii** [godotengine/godot-vscode-plugin#177]
It keeps saying "Connecting". I just rolled back. Everything working fine with the previous version.

**Godot**
Godot 3.2.2 beta 2

**Godot Tools**
Version 1.1.0

**VS Code**
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by Razoric480** [comment]
This is related to #141 - see godotengine/godot#35864
