### ISSUE TITLE
VS Code not "refresh" AssemblyReference.cache 

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-vscode-plugin#181]
Hi,
I use Godot 3.2.1.stable.mono, Debian 10 and C#.
I have a client server project and I setup a dll section for common parts.
When I modify/add namespaces in my dll, Godot compile fine but in VS Code I see a missing library/reference's namespace.
If I reopen the solution, setting it in EditorSettings, with MonoDeveloper it do some "sync/fix" things before open the solution. 
VS Code don't do it.
I investigate a bit the problem and seems  MonoDevelop has modified the `<myProjectName>.cspojAssemblyReference.cache` file in `.mono/temp/obj/Debug`
My guess is VSC plugin is missing this step.
Thank you.

**Comment by Calinou** [comment]
Does this plugin feature any kind of C#/Mono support?

**Comment by Razoric480** [comment]
The language server will transmit native symbols that the C# bindings are connected to, but it has no facilities, templates, or exposed code that controls C# projects (nor, for that matter, GDScript based projects, either, besides recognizing filetypes.)

So this isn't really the right place for this issue.

**Comment by Calinou** [comment]
Closing per @Razoric480's comment.
