### ISSUE TITLE
Connect signal method adds parentheses

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-vscode-plugin#184]
When connecting a signal, the third parameter of `connect`, adds an opening parentheses which then needs to be deleted.

Expected Output:
```
connect('my_signal', self, '_on_signal')
```

Actual Output:

```
connect('my_signal', self, '_on_signal(')
```
![Additional Parentheses](https://user-images.githubusercontent.com/1571806/83570365-81318f00-a4eb-11ea-924b-f4eefa000f5f.gif)

**Comment by TheColorRed** [comment]
Not sure if this is related or not, but it would be nice if the functions would automatically add the closing `)`.

**Comment by grenappels** [comment]
![autocomplete_one_paren](https://user-images.githubusercontent.com/18580013/86513569-2d131680-bdd9-11ea-9a94-57f3f05548c7.gif)
hints also do not pop up unless i delete the extra `(` and re-add it

**Comment by mickdekkers** [comment]
This looks related to #142, though there it also adds extra double quotes

**Comment by Calinou** [comment]
Note: The bug is in the language server, so you'll need to update to Godot 3.5 once it's released to fix this issue locally. The extension's version does not matter here.
