### ISSUE TITLE
Publish this extension to Open VSX

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-vscode-plugin#186]
Some third-party Visual Studio Code builds like [VSCodium](https://github.com/VSCodium/vscodium) are configured to use [Open VSX](https://open-vsx.org/) as the default extensions provider. This is because the Visual Studio Marketplace can only be used legally from official Visual Studio Code builds. 

We should eventually publish this extension to Open VSX so it can be installed more easily by VSCodium users.

- [More information](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace)
- [Pull request that made VSCodium use Open VSX by default, with additional discussion](https://github.com/VSCodium/vscodium/pull/404)

**Comment by do-kevin** [comment]
Just want to include this in here for anyone lurking and seeing this PR.

The plugin is already in Open VSX via [https://open-vsx.org/extension/geequlim/godot-tools](https://open-vsx.org/extension/geequlim/godot-tools).

However, this version is 1.0.1. It is not 1.2.1, which is the latest version.

**Comment by do-kevin** [comment]
Hey @Calinou,

I've updated godot tools on Open VSX to 1.1.2. You should probably close this issue since it's published and up-to-date now 👍
