### ISSUE TITLE
Adding new item to enum doesn't show in intellisense

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-vscode-plugin#187]
When adding an item to an enum, the new item doesn't show within autocomplete.

![EnumSuggestions](https://user-images.githubusercontent.com/1571806/83649750-2d6f8600-a57d-11ea-9292-d3b94509996e.gif)

**Comment by DaelonSuzuka** [comment]
Completions are provided by the Godot Engine's language server, so unfortunately, there's nothing this extension can do to improve them.

In my experience, though, recent versions of the language server have gotten much better at tracking changes to files and updating itself.
