### ISSUE TITLE
Create new built in function adds parentheses

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-vscode-plugin#189]
When creating a function such as `_ready`, `_process`, etc., opening and closing parentheses is created after the colon:

![ExtraParen](https://user-images.githubusercontent.com/1571806/83687529-7f320380-a5b1-11ea-9d9d-f5a264401637.gif)

**Comment by Calinou** [comment]
Which other VS Code extensions enabled? Maybe one of them could interfere with autocompletion.

**Comment by TheColorRed** [comment]
There shouldn't be any that  interfere, these are the only ones I have enabled:

![image](https://user-images.githubusercontent.com/1571806/83760047-01fea100-a63a-11ea-98b3-d32306076225.png)

**Comment by TheColorRed** [comment]
After testing more out, they each seem to work differently.

```
func _get(property: String):
func _get_configuration_warning() -> String:
func _draw() -> void:()
func _process(delta: float) -> void:(
func _unhandled_input(event: InputEvent) -> void:(
```
* Some have return types
* Some don't have return types
* Some are correct
* Some have parentheses
* Some don't have parentheses
* Some have an opening parentheses

**Comment by Calinou** [comment]
I think `_get()` doesn't have a return type because it can be anything. GDScript doesn't have an `any` return type yet (and doesn't allow to use `Variant` as a return type), so it has to be ommitted for now.

**Comment by TheColorRed** [comment]
Okay, I have removed that from the list of tested items.

**Comment by Razoric480** [comment]
`func _get_configuration_warning() -> String:` adds parenthesis at the end for me, so it's also not correct. Though the other 3 are as stated.

**Comment by Razoric480** [comment]
I've finally investigated this eons later and can confirm that it's an issue with the LSP.
```cpp
if ((item.kind == lsp::CompletionItemKind::Method || item.kind == lsp::CompletionItemKind::Function) && !item.label.ends_with("):")) {
		item.insertText = item.label + "(";
		if (symbol && symbol->children.empty()) {
			item.insertText += ")";
		}
	}
```
does not take into consideration instances where static typing is included with `->`. Changing it to
```cpp
if ((item.kind == lsp::CompletionItemKind::Method || item.kind == lsp::CompletionItemKind::Function) && !item.label.ends_with("):") && item.label.rfind("->") == -1) {
		item.insertText = item.label + "(";
		if (symbol && symbol->children.empty()) {
			item.insertText += ")";
		}
	}
```
removes the issue.

**Comment by Misignu** [comment]
No any possible fix? This bug is a bit annoying.

**Comment by Calinou** [comment]
@Misignu This is a bug that needs to be fixed in Godot's C++ code, not in the Visual Studio Code extension. Due to this, it will have to wait until someone opens a pull request to fix this on Godot and gets it merged.

**Comment by TheColorRed** [comment]
This seems to have been resolved. I am not seeing the issue anymore.
