### ISSUE TITLE
Is `trace_builtins.py` still needed?

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-vscode-plugin#191]
I came across this file in the `configurations/` folder: https://github.com/godotengine/godot-vscode-plugin/blob/master/configurations/trace_builtins.py

Is it still used today? It's pointing to a nonexistent `doc/classes.json` file.

**Comment by Geequlim** [comment]
I think we can delete it now.

**Comment by Razoric480** [comment]
The only place I see it referred to is inside a compiled VSIX, so yeah, probably.
