### ISSUE TITLE
$NodeName Cannot Be AutoCompleted.

### ISSUE THREAD

**Issue by AllenPocketGamer** [godotengine/godot-vscode-plugin#192]
Godot Version: 3.2.1
Vscode Godot Plugin Version: 1.1.0

I am new to Godot and following the official tutorial to learn how to use Godot.
I prefer VSCode rather than the internal editor(although it's good tools) as my text editor.
So I install plugins, but the experience is different from the built-in editor.

vscode CAN'T autocomplete $NodeName.

Yeah, I read the bug #150 and I'm sure vscode is connected to gdscript language server and open the corresponding scene file in godot editor, but the problem still exists.

Maybe there is something wrong with my computer, so I switch to my little surface pro to test, but the problem still exists(So Sad).
I change to a new godot project but yeah the problem is still there.

![捕获](https://user-images.githubusercontent.com/17348971/84458093-cf3a5580-ac96-11ea-9cce-c7a3e7a64dc1.PNG)

Waiting for a MASTER to help me. 😢

**Comment by Geequlim** [comment]
https://github.com/godotengine/godot/pull/36521

**Comment by Razoric480** [comment]
To paraphrase what Geequlim is saying, expect this feature in Godot 3.2

**Comment by AllenPocketGamer** [comment]
Thx for your reply, I download 3.2.2 beta but I found vscode can't connect to the gdscript language server, it always prompts "connecting".

![捕获](https://user-images.githubusercontent.com/17348971/84468809-49c49e80-acb2-11ea-99b6-49e33ddb9ed0.PNG)

emmm~~~ The LSP improvement added to Godot 3.2.2, right?

**Comment by Calinou** [comment]
@AllenPocketGamer Did you download 3.2.2beta4 or an older beta?

Also, you may need a more recent version of this add-on as the language server was switched from WebSockets to TCP. You'll likely need to build it from source.

**Comment by AllenPocketGamer** [comment]
Thanks for the reply, I download Godot 3.2.2 beta4 to test and get the same result :(

I read the changelog of Godot 3.2.2 beta4 and found the improvement(switch WebSocket to tcp) is added to Godot.

Should I build it from the recent source code from github?

**Comment by Calinou** [comment]
@AllenPocketGamer No, I meant you should build *this extension* from source and install the generated VSIX file into your Visual Studio Code isntallation.

I don't remember exactly how to do it though. I think Visual Studio Code should prompt you about it if you clone this repository and open it in Visual Studio Code.

**Comment by AllenPocketGamer** [comment]
@Calinou I tried to package the extension by vsce, but there is something wrong in the extension project.

the errors log:

src/debugger/debug_adapter.ts:3:19 - error TS2339: Property 'run' does not exist on type 'typeof GodotDebugSession'.

3 GodotDebugSession.run(GodotDebugSession);
                    ~~~

src/debugger/debug_session.ts:7:8 - error TS2307: Cannot find module 'vscode-debugadapter' or its corresponding type declarations.

7 } from "vscode-debugadapter";
         ~~~~~~~~~~~~~~~~~~~~~

src/debugger/debug_session.ts:8:31 - error TS2307: Cannot find module 'vscode-debugprotocol' or its corresponding type declarations.

8 import { DebugProtocol } from "vscode-debugprotocol";
                                ~~~~~~~~~~~~~~~~~~~~~~

src/debugger/debug_session.ts:39:8 - error TS2339: Property 'setDebuggerLinesStartAt1' does not exist on type 'GodotDebugSession'.

39      this.setDebuggerLinesStartAt1(false);
             ~~~~~~~~~~~~~~~~~~~~~~~~

src/debugger/debug_session.ts:40:8 - error TS2339: Property 'setDebuggerColumnsStartAt1' does not exist on type 'GodotDebugSession'.

40      this.setDebuggerColumnsStartAt1(false);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/debugger/debug_session.ts:146:9 - error TS2339: Property 'sendResponse' does not exist on type 'GodotDebugSession'.

146             this.sendResponse(response);
                     ~~~~~~~~~~~~

src/debugger/debug_session.ts:178:8 - error TS2339: Property 'sendResponse' does not exist on type 'GodotDebugSession'.

178     this.sendResponse(response);
             ~~~~~~~~~~~~

src/debugger/debug_session.ts:220:8 - error TS2339: Property 'sendResponse' does not exist on type 'GodotDebugSession'.

220     this.sendResponse(response);
             ~~~~~~~~~~~~

src/debugger/debug_session.ts:221:8 - error TS2339: Property 'sendEvent' does not exist on type 'GodotDebugSession'.

221     this.sendEvent(new InitializedEvent());
             ~~~~~~~~~

src/debugger/debug_session.ts:239:8 - error TS2339: Property 'sendResponse' does not exist on type 'GodotDebugSession'.

239     this.sendResponse(response);
             ~~~~~~~~~~~~

src/debugger/debug_session.ts:248:9 - error TS2339: Property 'sendResponse' does not exist on type 'GodotDebugSession'.

248             this.sendResponse(response);
                     ~~~~~~~~~~~~

src/debugger/debug_session.ts:258:9 - error TS2339: Property 'sendResponse' does not exist on type 'GodotDebugSession'.

258             this.sendResponse(response);
                     ~~~~~~~~~~~~

**Comment by Razoric480** [comment]
You'll also need to install NPM and run the `npm -install` command to download dependencies, before you can run `vsce -package`

If you don't want to mess with all that, check out my comments in #168 - I posted a pre-compiled zip file there built from a far more recent master, including the websocket and TCP/IP switch in godot-tools' extension settings.

**Comment by AllenPocketGamer** [comment]
@Razoric480 Thx, It works
