### ISSUE TITLE
Division By Zero in operator '/'.

### ISSUE THREAD

**Issue by 37576677a** [godotengine/godot-vscode-plugin#193]
func _castCdSkill(id):
        ._castCdSkill(id)
        if id == "cdeku_3":
            addBuff(b_diYu.new(10))
        if id == "cdeku_2":
            addBuff(b_moYu.new(10))
        if id == "cdeku_1":
            addBuff(b_liuXue.new(10))
        if id == "Detroit Smash" && aiCha != null:
                    var eff:Eff = newEff("sk_chuanTouJian",sprcPos)
                    eff._initFlyPos(position + (aiCha.position - position).normalized() * 1000,800)
                    eff.connect("onInCell",self,"effInCell")
var bl = false
func  _onBattleStart():
        yield(reTimer(0.4),"timeout")
        bl = true
        var mv = Vector2(cell.x ,cell.y)
        if team == 1:mv.x = 7
        else:mv.x = 0
        var vs = [Vector2(0,0),Vector2(1,0),Vector2(-1,0),Vector2(0,1),Vector2(0,-1),Vector2(1,1),Vector2(-1,1),Vector2(-1,-1),Vector2(1,-1)]
        for i in vs:
            var v = mv+i
            if matCha(v) == null && sys.main.isMatin(v):
                if setCell(v) :
                    var pos = sys.main.map.map_to_world(cell)
                    ying(pos)
                    position = pos
                    aiCha = null
                    break
func ying(pos):
        var l:Vector2 = pos - position
        var s = 25
        var rs = preload("res://core/ying.tscn")
        var n = l.length()/s
        for i in range(n):
            var spr = rs.instance()
            sys.main.map.add_child(spr)
            spr.texture = img.texture_normal
            spr.position = position + s * (i+1) * l.normalized() - Vector2(img.texture_normal.get_width()/2,img.texture_normal.get_height())
            spr.init(255/n * i + 100)
func _onAtkChara(atkInfo:AtkInfo):
        ._onAtkChara(atkInfo)
        if atkInfo.atkType == AtkType.NORMAL && bl: 
            bl = false
            atkInfo.hurtVal *= 3

**Comment by 37576677a** [comment]
what did i wrong

**Comment by Calinou** [comment]
This isn't an issue with the VS Code plugin (nor a bug within Godot). For support questions, please use one of the other [community channels](https://godotengine.org/community) instead.
