### ISSUE TITLE
VSCode doesn't start up Godot and attaches

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot-vscode-plugin#195]
When I F5 or run the game, nothing happens. I can stop the game and pause but there's no game screen, it doesn't seem like it builds. No errors show up anywhere (do I need to enable a setting to see them?). I think the godot editor settings is setup fine since the language server works fine.

How can I troubleshoot this?

I've followed everything in the tutorial, so I'm not sure what could be wrong.

I'm on a Mac OSX Sierra 10.12.6.

Here's my config file:
```
{
	"folders": [
		{
			"path": ".."
		}
	],
	"settings": {},
	"launch": {
		"version": "0.2.0",
		"configurations": [

			{
				"name": "Godot",
				"type": "godot",
				"request": "launch",
				"project": "/Users/lucrecious/dev/gear_game",
				"port": 6007,
				"address": "127.0.0.1",
				"launch_game_instance": true,
				"launch_scene": false
			}
		]
	}
}
```

I've used both the absolute file location and `${workspace}` and both should have worked.

Here's my extension settings:
![image](https://user-images.githubusercontent.com/4584511/84550494-c5d1dd00-acd8-11ea-8009-28358be0ab01.png)

**Comment by Razoric480** [comment]
Hello; if you could try installing this VSIX version and try it again. If it fails to launch Godot, it should give you an error popup in VSCode. If it doesn't, then there might be something else going on and I need to detect it as an error somewhere else.
[godot-tools-error-check.zip](https://github.com/godotengine/godot-vscode-plugin/files/4773871/godot-tools-error-check.zip)

**Comment by Lucrecious** [comment]
Thanks! Maybe this error version should be the default. It helped with solving the debug issue but it had issues connecting to the Godot language server, whereas my other version didn't.

My issue was that I needed to point to the actual executable inside the Godot.app folder not just the directory.

However, while this fixed the issue with the game not starting up, the debug isn't working still. I can see the Active Scene Tree but no breakpoints are hit and the inspector is never updated. Any ideas?

**Comment by Razoric480** [comment]
Godot version 3.2.2 will switch over to TCP/IP instead of Websocket. The current master, from which this fix is derived, includes a fix that allows you to change it, though the default is probably TCP. But if you're on 3.2.1 still, you have to go into godot-tools' options and change it from TCP to WS.

As for not hitting any breakpoints, I have to ask cause it's come up before: is your project a C# project or a GDScript project? This debugger doesn't support C# projects.

**Comment by Lucrecious** [comment]
Hi @Razoric480 

Sorry I missed the github email for this.

But no, I'm using pure GDScript in this project right now. Like I said, I can start up the game now but the breakpoints don't hit.

Is there any way to debug this?

**Comment by Razoric480** [comment]
Do you see output messages? That is, stuff like:
```
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: <Insert Graphics Card Here>
```
in the Godot output panel's output tab?

Does it happen solely on your project? Or does it break even if you create a test project with a simple test GDScript?

**Comment by Lucrecious** [comment]
This happens with any project - and no, I don't get anything in the Godot output window in VSCode. :/

What does that mean?

**Comment by Razoric480** [comment]
It means that it's not successfully communicating with the remote debugger, somehow. I'll dig out my mac mini and see if there's some Mac specific issue going on. I'll get back to you when I have more questions/an answer.

**Comment by Razoric480** [comment]
Hiya @Lucrecious . Can you try this one on for size?
[godot-tools-delaylaunch.vsix.zip](https://github.com/godotengine/godot-vscode-plugin/files/4810705/godot-tools-delaylaunch.vsix.zip)

**Comment by Lucrecious** [comment]
Hey @Razoric480 

This one seems to mostly work! So now I'm able to break in VSCode, all the panels get populated except for the Inspector and Active Scene panels (even when I try refreshing them).

Thanks for the help Razoric, this is great :)

**Comment by Razoric480** [comment]
Okay, thanks; I'll see if I can't figure out why the scene tree isn't working. I think I have an idea of why but we'll see.

**Comment by Razoric480** [comment]
Hopefully this is the last one. Let me know if that works for you.
[godot-tools-eventfix.zip](https://github.com/godotengine/godot-vscode-plugin/files/4810957/godot-tools-eventfix.zip)

**Comment by Lucrecious** [comment]
Nice! Everything seems to work as intended. Thanks :)

Will this version be updated officially for the VSCode extensions? Just wondering.

**Comment by Razoric480** [comment]
Eventually, yeah; the changes are folded in my latest pull request.

**Comment by Shatur95** [comment]
I think the issue can be closed?

**Comment by Shatur95** [comment]
I think it would be nice to find a new maintainer for this plugin. Maybe add the information in README.md or pin the issue with the information.

**Comment by Lucrecious** [comment]
I agree.

I actually don't use VSCode for editing anymore because it feels incomplete. You can't use it for plugins yet, you can't make new `class_name`s without reloading the script in Godot, there are errors whenever you switch between VSCode and Godot, and the there's a lot of little issues. These issues really bother me and it discourages me from using VSCode for GDScript.

I think the maintainer needs to work both with Godot and the plugin itself for it to work properly, otherwise you'll issues like the one above. I think it's worth considering hard-coded VSCode logic in Godot or something, and then general logic (like how we have now) for the rest.
