### ISSUE TITLE
Extension causes high CPU load

### ISSUE THREAD

**Issue by bitbear101** [godotengine/godot-vscode-plugin#200]
- Issue Type: `Performance`
- Extension Name: `godot-tools`
- Extension Version: `1.1.0`
- OS Version: `Linux x64 5.4.47-1-lts`
- VSCode version: `1.46.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/bitbadger/geequlim.godot-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Calinou** [comment]
@IndieRonin Are you getting this CPU load only on a specific project, or are you getting it even in a minimal project?

**Comment by IndieRonin** [comment]
Hi Hugo,
I'm getting the CPU load on only one project.

**Comment by DaelonSuzuka** [comment]
Closing because I highly doubt that any of the factors that led to this situation are still relevant.
