### ISSUE TITLE
Add Auto complete for gdscript static typing

### ISSUE THREAD

**Issue by lazyvainglory** [godotengine/godot-vscode-plugin#203]
For people who prepare static typing, adding an autocomplete support in custom methods and variables, would significantly improve their workflow. 

![image](https://user-images.githubusercontent.com/45304248/85648562-9ad18b00-b6d3-11ea-9a1c-42fcd88e63e4.png)

**Comment by DaelonSuzuka** [comment]
Looks like this exists now:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/7e789796-a512-407b-b773-c113b1efd1dc)

**Comment by atirut-w** [comment]
It has existed for a while IIRC
