### ISSUE TITLE
Unable to connect this plugin to language server for Godot 3.2.2

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot-vscode-plugin#204]
After the connection attempt the following log is printed out:

![image](https://user-images.githubusercontent.com/3036176/85864511-4a3e5880-b7cd-11ea-9a63-50c140047e62.png)

**Comment by Razoric480** [comment]
The plugin has not yet been updated on the marketplace, and the communication protocol has changed from websocket to TCP/IP. only the latest version of the plugin supports both.

**Comment by Calinou** [comment]
I pinned this issue so people can notice it more easily.

**Comment by Geequlim** [comment]
The latest version is published to VSCode extension market now.

**Comment by vickylance** [comment]
@Geequlim @Calinou   I dont think the issue is still resolved. When I click on the Open Godot tools and then choose the editor from my Applications its still not opening. I have to manually open the project.

**Comment by Calinou** [comment]
@vickylance Please open a new issue for this.
