### ISSUE TITLE
Open workspace doesn't work with WSL in Windows

### ISSUE THREAD

**Issue by vickylance** [godotengine/godot-vscode-plugin#208]
`Godot Tools: Open Workspace with Godot Editor` doesn't work with the windows WSL using Ubuntu 20.04

![image](https://user-images.githubusercontent.com/5861833/85917972-68af5d00-b87c-11ea-90da-e90fb1f79c0c.png)

**Comment by Razoric480** [comment]
You likely have to change the path you're using - it's using a windows path when it should be using a WSL enabled path. I.E. you should set the absolute path in the options to `/mnt/host/e/softwares/godot-csharp/Godot-v3.2.2.exe`

**Comment by linkpy** [comment]
That issue seems to be a configuration problem of your user settings. Like @Razoric480 said, you should modify Godot's path in the extension setting so it matches WSL's filesystem.

**Comment by Shatur95** [comment]
@linkpy, is it possible to have different paths to Godot on different system? It would be useful for configuration sync.

**Comment by linkpy** [comment]
What do you mean by "on different system" ? Most of the extensions doesn't do that, and usually look on the path environmental variable to look the executable. You can have different path for godot on different systems, if in all of them you have godot in the path.

**Comment by Shatur95** [comment]
Currently I need to specify absolute path to the Godot executable. If I don't, then launching from the editor won't work. For example, on Windows I have godot.exe in my `PATH`, but it is not recognized until I specify the full path to it in the extension settings.

**Comment by mintyleaf** [comment]
well
to fix it temporary i used to open C:\Users\{user}\.vscode\extensions\geequlim.godot-tools-1.3.1
then, edit the out/godot-tools.js file, commenting out whole check for editorPath variable (starting from 164 line), just leaving run_godot function unsafe to launch

then, setting linux like path for editor_path in workspace works like a charm
