### ISSUE TITLE
Selecting an item in the List native classes of Godot list fails to get docs and causes future hovers to get stuck

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot-vscode-plugin#210]
1. Open a godot project, connect to LSP
2. Hover over a `print()` statement, see that it brings up the documentation for it normally.
3. Open `List native classes of Godot` command and press enter on one of them. The documentation page doesn't come up.
4. Hover over the same `print()` statement, and it's stuck at `Loading...` until reconnected.

The extension outputs the following when debugging it:
```
[godot-tools][2020-06-27T17:39:41.806Z] [server] {"error":{"code":-32700,"message":"Parse error"},"id":null,"jsonrpc":"2.0"} 
loggger.js:36
Received response message without id: Error is: 
{
    "code": -32700,
    "message": "Parse error"
}
```

From then on, it receives the textDocument/hover command, but doesn't do anything with it until it's cancelled by the $/cancelRequest command.

This is latest master on 3.2.2 with tcp/ip.
This issue does not happen on 3.2.1 with websocket.

**Comment by Shatur95** [comment]
I have the same issue.

**Comment by Shatur95** [comment]
@Razoric480, could you look into this issue? Very missing feature :(
