### ISSUE TITLE
GDscript Debug Issue - Breakpoints Not working

### ISSUE THREAD

**Issue by attishno1** [godotengine/godot-vscode-plugin#212]
Hello! Thank you for viewing. I have the tools installed and run the debugger only after the launch.json file is created. Here is what I do.

- Open a script in VS Code
- Hit the debug tab on the left side.
- Create a launch.json file using the create a json option.
- Once create, I hit Play or Run on VS Code after creating a few breakpoints in scripts.
- Then I hit play on the Godot Editor.

No breakpoint is hit. Nothing happens.

**Comment by Razoric480** [comment]
1. Is this for a GDScript project? The debugger does not work with C# projects. Use [Mono Debug](https://godotsharp.net/how-to/debug-your-mono-godot-project/) for those.
2. If you _are_ using GDScript, does it work if you use [this precompiled VSIX file](https://github.com/godotengine/godot-vscode-plugin/files/4810957/godot-tools-eventfix.zip)? (you may have to double check the extension settings to make sure you're using the right protocol to connect to the language server. WS/websocket for 3.2.1 and below, and TCP/IP for 3.2.2 and above.)

**Comment by sgarcia22** [comment]
I am having a similar issue. I'm using 3.2.2 and downloaded the VSIX  godot-tools-1.1.1.vsix.zip and made sure the settings is set to tcp. When I click debug nothing happens, doesn't even open the game up in Godot.

When I use the VSIX above and press Debug it says:
Failed to launch Godot instance: Error: Command failed: "godot" --path "<mypath>" --remote-debug 127.0.0.1:6007 --breakpoints res://Scripts/Twirl.gd:11 '"godot"' is not recognized as an internal or external command, operable program or batch file.

**Comment by Razoric480** [comment]
@sgarcia22 Go into the extension settings and make sure to fill in the Editor_path to your godot exe. By default, if that information is not filled in, the debugger will try to launch "godot.exe" from your PATH environment variable (and if it's not set, or it's named differently, then it won't find it.)

@attishno1 For that matter, same to you, if it's not done.

**Comment by attishno1** [comment]
@Razoric480 The debugger output is working on a GDscript project, but the breakpoints don't work. That's all. For some reason I couldn't reply for the past 2 days.

**Comment by Razoric480** [comment]
And you tried the custom VSIX?

**Comment by sgarcia22** [comment]
> @sgarcia22 Go into the extension settings and make sure to fill in the Editor_path to your godot exe. By default, if that information is not filled in, the debugger will try to launch "godot.exe" from your PATH environment variable (and if it's not set, or it's named differently, then it won't find it.)
> 
> @attishno1 For that matter, same to you, if it's not done.

That worked! Thank you

**Comment by attishno1** [comment]
> And you tried the custom VSIX? @attishno1

I wasn't well for the past few days and didn't log-in. Reinstalling Windows fixed the problem for me.

**Comment by paternostrox** [comment]
> Go into the extension settings and make sure to fill in the Editor_path to your godot exe. By default, if that information is not filled in, the debugger will try to launch "godot.exe" from your PATH environment variable (and if it's not set, or it's named differently, then it won't find it.)

This should be in the debugger setup notes on vscode store, it would help a lot of people.
