### ISSUE TITLE
Language server performance between 3.2.1 with websocket and 3.2.2 with TCP/IP is severely and unusably worse

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot-vscode-plugin#213]
Demonstration videos of the issue:
3.2.1 with websocket video: https://imgur.com/a/z6Z9ypI
3.2.2 with TCP/IP video: https://imgur.com/a/QoQnWY3

It's a difference between instant feedback, and upwards of 10 to 20 seconds before anything shows up.

Compounded with #210 where you cannot get any feedback in certain cases when the extension fails on a function call and never recovers, the extension is more or less unusable right now.

(extension is same version. only difference is that I changed which version of godot is in use and the communication protocol in the extension settings.)

**Comment by Calinou** [comment]
Are you sure this isn't on Godot's side?

**Comment by Razoric480** [comment]
I am not; it certainly could be the language server itself struggling as of 3.2.2 and the TCP/IP implementation is actually fine as far as the extension is concerned.

**Comment by Razoric480** [comment]
Having just tested a few things, it seems that the use of Threads in the language server is to blame for this slow down. Turning Use Thread off in the editor settings boosts the acceleration back to normal, so I'll close this issue and report it on the godot repo instead.

**Comment by Razoric480** [comment]
After having tested in Atom and not encountering the issue as in https://github.com/godotengine/godot/issues/40126, it appears there is an issue at the VS Code side after all.

**Comment by DaelonSuzuka** [comment]
@Razoric480 Is it safe to presume that you aren't still experiencing this issue?

**Comment by Razoric480** [comment]
> @Razoric480 Is it safe to presume that you aren't still experiencing this issue?

Can confirm that on Godot 4.1.stable-official, with VSCode, autocomplete is effectively instantaneous.
