### ISSUE TITLE
Breakpoint setting problem

### ISSUE THREAD

**Issue by rohanrhu** [godotengine/godot-vscode-plugin#215]
Hi, there is a breakpoint setting problem.

You can see the gif:

![](https://i.imgur.com/Q6WxgJr.gif)

**Comment by Calinou** [comment]
Isn't the breakpoint UI provided by VS Code itself?

**Comment by Razoric480** [comment]
I can confirm the bug, but I'm not sure why it's happening internally.

Scenario: Breakpoints on lines 28, 30, 33. Internally, those are stored as [28, 30, 33]
I remove 28. So far so good. [30, 33].
I add 28. So far so good. [30, 33, 28]
I remove 28.

At that point, VSCode sends me a setBreakpointsRequest, but provides [28, 30] as the lines that have breakpoints, when it should be [30, 33].

Anyway, I seem to have been able to fix it by sorting the breakpoints before handing them over to VSCode's debugger context. I'm issuing a PR to fix it.

**Comment by rohanrhu** [comment]
Nice. I will try it.
