### ISSUE TITLE
Newline not properly inserting tabs

### ISSUE THREAD

**Issue by bg641** [godotengine/godot-vscode-plugin#220]
Steps to reproduce:
1. in an indented block, write a line of code
2. press enter twice and write a new line of code

the line between the two lines will have no tabs/spaces, when it should be indented to the same level as the other two lines

**Comment by bg641** [comment]
Upon further digging, this is a vscode problem rather than a plugin problem, and can be solved by setting `editor.trimAutoWhitespace` to false.

**Comment by Calinou** [comment]
Indeed, whitespace trimming is done by Visual Studio Code itself. Closing.
