### ISSUE TITLE
Scripts don't recognize added or edited class_name

### ISSUE THREAD

**Issue by Vikingjonsson** [godotengine/godot-vscode-plugin#225]
If I add a class_name or edit a class_name in a GDscript through VScode, that change doesn't get recognized by other scripts, I can see the name of the class in the hint but I can't use it.

To make the change sync I need to open the script in Godot's internal text editor and save the file. When I then open the script in VScode the change is recognized.

![image](https://user-images.githubusercontent.com/8763236/90975265-f9c84a80-e532-11ea-8ff8-4cdfc9bee702.png)
![image](https://user-images.githubusercontent.com/8763236/90975279-195f7300-e533-11ea-8aaa-1acad50e3715.png)

**Comment by Shatur95** [comment]
It looks like it's a Godot problem. You need to restart it.

**Comment by Vikingjonsson** [comment]
@Shatur95 if I do the same action again it loses the update again if I run the game it works and then it will recognize that the variable change.

What I mean is that to restart Godot is not a solution.

**Comment by Shatur95** [comment]
@Vikingjonsson, of course! It's just a workaround.

**Comment by MarcusDobler** [comment]
I've reported the issue at the GODOT page, they gave me the answer its a PlugIn Bug.

**Comment by Calinou** [comment]
@MarcusDobler I don't know for certain if this is actually a Godot bug or a plugin bug.
