### ISSUE TITLE
Making godot-vscode-plugin the grammar provider for github

### ISSUE THREAD

**Issue by pastra98** [godotengine/godot-vscode-plugin#226]
Hi everyone! A week ago I have raised an issue in the [linguist](https://github.com/github/linguist) repository that github uses for syntax highlighting. I imagine a lot of you have already noticed syntax highlighting on github it is currently broken for .gd files.

That is because the repository used for providing the gdscript grammar file has multiple bugs, most notably an inability to deal with typed function returns using the '->' symbol.

The issue can be found at github/linguist#4974. Thanks to the help of @alhadis I have learned that a repository used by linguist must store the grammar file in a folder called `/syntaxes`. The grammar file of this repository is however stored in `/configurations/GDScript.tmLanguage.json`. I have created a [fork](https://github.com/pastra98/godot-vscode-plugin) that has a copy of the `GDScript.tmLanguage.json` file in the `/syntaxes` folder, just to test if it would work with linguist, and it did.

**So here's my request:** rename the `/configurations` folder to `/syntaxes`. I did not want to submit a PR yet, because I know too little about the internal workings of this plugin and I'm aware that it does a lot more things, other than just coloring code.

A quick search for 'configurations' in my code editor showed me that it is used in the `package.json` and `launch.json` scripts, but I don't know anything about vscode extensions (or typescript for that matter)- so I did not want to mess around changing things. Because of this, I first tried to switch linguist to [another gdscript plugin](https://github.com/PrestonKnopp/language-gdscript) made for the atom code editor, but the maintainer has neither responded to my PR, nor the email that I sent him.

Which leaves me with no other choice than to bother you guys with this😁

I'd love to have .gd scripts displayed properly on github, and I think this repository is the best choice for that, because it is maintained and used by the most people.

**Comment by pastra98** [comment]
Would be great to hear what @Geequlim or @Calinou have to say about this. I don't think this would be a radical change to the codebase, but it would benefit everyone that shares gdscript source code on github.

**Comment by Shatur95** [comment]
Looks like @Geequlim has stopped supporting this plugin in favor of [JS as scripting language](https://github.com/GodotExplorer/ECMAScript). It may require a new maintainer for this plugin. At the moment it contains many bugs.

**Comment by Razoric480** [comment]
And the pull requests to such bug fixes have piled up, untouched.

As for /configurations being converted to /syntaxes, there isn't really anything special about the configurations folder, and only package.json references it. I just tested it with it named syntaxes (with a changed package.json) and everything seemed to work fine.

**Comment by Shatur95** [comment]
@Razoric480, maybe you like to become a maintainer of this plugin? If so, ask Godot developers.

**Comment by pastra98** [comment]
@Shatur95 Thanks for pointing this out. Kind of depressing, I've been on a bit of an odyssey trying to find a new repo to for linguist to use.
@Razoric480 Would be great if this repository had an active maintainer. I think a lot of people use vscode as a godot editor, and I'd also like to continue using it in the future. At least someone that merges PRs occasionally would be awesome, but thats up to you of course.

**Comment by Calinou** [comment]
I can handle the merging of pull requests, but I don't use this extension actively since I mainly use the built-in script editor.

**Comment by pastra98** [comment]
> I can handle the merging of pull requests, but I don't use this extension actively since I mainly use the built-in script editor.
> 
> Feel free to open a pull request to carry out the required changes 🙂

Awesome, I can try to make the PR tomorrow, but again- I'm not really capable of doing much more than a search and replace. But it seems like @Razoric480 has already tested this, changing the `package` file? Maybe he could do it? The fork I made literally just copied the tmlanguage file into a new folder, and thats all linguist requires to find the correct file.

**Comment by Razoric480** [comment]
Sure, I'll do it.

**Comment by pastra98** [comment]
@Razoric480 thanks man! I'll make a PR in the linguist repo once you're done. Finally some progress in my undertaking haha😀

**Comment by Razoric480** [comment]
Done.

**Comment by pastra98** [comment]
Well holy crap, that was fast. I'm currently away from my main computer that has the linguist environment installed, but I'll get to it in about 2hrs.

thanks so much
@Razoric480 , @Calinou

**Comment by Shatur95** [comment]
@Calinou, could you upload a new release in VSCode marketplace with the latest changes?

**Comment by Calinou** [comment]
@Shatur95 I don't have Geequilm's access token, which I need to publish to the marketplace. In the meantime, you can use the artifacts published on GitHub Actions: https://github.com/godotengine/godot-vscode-plugin/actions

**Comment by Shatur95** [comment]
Thanks, that's exactly what I did.
It will be bad if the extension has to be installed manually every time. @Geequilm, maybe you can share your access token with @Calinou if you don't have time to work on it?

**Comment by Geequlim** [comment]
@Calinou already has the permission to update the plugin to vscode market
place.

Hennadii Chernyshchyk <notifications@github.com>于2020年9月9日 周三01:04写道：

**Comment by Shatur95** [comment]
@Geequlim, thank you!

**Comment by Calinou** [comment]
@Geequlim I know, but I need the publisher token to be able to upload to the Marketplace using the `vsce` command-line tool (unless I miss something).
