### ISSUE TITLE
Variables in base class not recognized in subclass

### ISSUE THREAD

**Issue by Vikingjonsson** [godotengine/godot-vscode-plugin#230]
Hello,
If a variable is added to a base class it is not recognized in subclasses until the game has been executed or Godot has been restarted. 

I should also mention that it does seem to understand where the variable is defined. This screenshot is from the subclass.
![image](https://user-images.githubusercontent.com/8763236/93665628-2dd25500-fa78-11ea-8234-4b47307a1e37.png)

I'm on macOS Mojave.
Godot version: Godot Engine v3.2.2.stable.official.
Might be the same issue as: https://github.com/godotengine/godot-vscode-plugin/issues/225

Edit: also tested on windows and the same thing there.

**Comment by linkpy** [comment]
This doesn't look like an issue with the extension itself. The extension itself doesn't do anything to resolve symbols and if the issue is resolved after starting the game in Godot, it is an issue with Godot itself.

It was already reported here https://github.com/godotengine/godot/issues/39713.
