### ISSUE TITLE
Add extension setting to specify project file path so that the vs workspace can be treated as a godot workspace

### ISSUE THREAD

**Issue by pcting** [godotengine/godot-vscode-plugin#239]
I'm in the progress of building out go binding for godot here: [godot-go](https://github.com/godot-go/godot-go). I was wondering if you guys would be interested in adding support for specifying a project file not at the root of the workspace?

basically something like this:
```
godot --path test/project/
```

without this feature, the extension doesn't treat my vscode workspace as a godot workspace and i get the ["Current workspace is not a Godot project"](https://github.com/godotengine/godot-vscode-plugin/blob/60cb0c57fcbafe37f6389d9b3df157c95943e8f3/src/godot-tools.ts#L53) error.

**Comment by DaelonSuzuka** [comment]
The extension no longer assumes that `project.godot` is in the root of the workspace.
