### ISSUE TITLE
Publish godot-vscode-plugin 1.1.2 VSIX as Latest Release For Open VSX

### ISSUE THREAD

**Issue by do-kevin** [godotengine/godot-vscode-plugin#249]
Could you publish version 1.1.2 under latest releases with the VSIX package available? I need a link like `https://github.com/godotengine/godot-vscode-plugin/releases/download/1.0.1/godot-tools-1.0.1.vsix` that provides the vsix package via direct url.

I would like to open a pull request for Open VSX to update their godot-vscode-plugin to its latest version once the releases have been updated. Thanks!

**Comment by do-kevin** [comment]
Hey @Geequlim,

Thanks for publishing the release after I sent you the message. If you didn't receive my second email, the release's assets currently does not include the `.vsix` file. Someone from Open VSX and I are waiting for the update: [https://github.com/open-vsx/publish-extensions/pull/220](https://github.com/open-vsx/publish-extensions/pull/220).

Thanks again.

**Comment by Geequlim** [comment]
https://github.com/godotengine/godot-vscode-plugin/releases/download/1.1.2/godot-tools-1.1.2.vsix
