### ISSUE TITLE
multi-line if statement showing as error

### ISSUE THREAD

**Issue by JimmyJames707** [godotengine/godot-vscode-plugin#25]
Hi,
This is legal syntax in Godot, but is reported as an error in your extension.

![screenshot_2017-05-25_04-41-20](https://cloud.githubusercontent.com/assets/6817086/26420017/d76ff30a-4104-11e7-9e6e-cd56a211bb38.png)

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
