### ISSUE TITLE
"Rename symbol" appears to be unimplemented

### ISSUE THREAD

**Issue by shingle-bells** [godotengine/godot-vscode-plugin#254]
When I try to rename a symbol in gdscript code, I get this error:
```
[Error - 11:28:00 a.m.] Request textDocument/rename failed.
  Message: Method not found: rename
  Code: -32601 
```
Is this on the to-do list?

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-vscode-plugin/issues/32.
