### ISSUE TITLE
Broken functionality for some keywords and identifiers

### ISSUE THREAD

**Issue by Flash1232** [godotengine/godot-vscode-plugin#256]
As I started developing a multiplayer game and wrote my initial (GDScript) server code, I noticed that when I use the networking keywords "remote", "puppet" etc., the editor would auto-complete them but not color them properly and provide no indentation on the new line (as if it doesn't recognize the identifiers internally, possibly needs a change [here](https://github.com/godotengine/godot-vscode-plugin/blob/a8872c2e56a7d4c566af0d35d51806a5ae9eb9e0/configurations/gdscript-configuration.json#L26)).

**EDIT**: The below issue belongs to the engine project and already has an [open issue](https://github.com/godotengine/godot/issues/44482):
~~There also seems to be missing functionality to recognize snake_cased auto-loaded script class identifiers (e.g. `server_data.gd` singleton can be used like `ServerData.method()` but VS Code would throw an error on that line). [This](https://github.com/godotengine/godot/blob/3.2/modules/gdscript/gdscript_parser.cpp#L7807) error message is displayed.~~ Might be fixed in Godot 4.

Affects plugin v1.1.2 with Godot v3.2.3-stable

**Comment by DaelonSuzuka** [comment]
This works now:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/ef9d14c6-741c-4b23-85cf-8a6a3fc4603e)
