### ISSUE TITLE
I cant use my godot tool 

### ISSUE THREAD

**Issue by dinesh007-lap** [godotengine/godot-vscode-plugin#258]
Issue Type: <b>Feature Request</b>

i cant us emy godot tools in vs code it shows connectig to the server but its not  connectting tried agian for many times. it shows only connecting. please do something

Extension version: 1.1.2
VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 6.1.7601

**Comment by Calinou** [comment]
@dinesh007-lap Which Godot version are you using?

**Comment by dinesh007-lap** [comment]
Godot 3.2

**Comment by dinesh007-lap** [comment]
Sorry version 3.2.3

**Comment by Calinou** [comment]
@dinesh007-lap Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

**Comment by dinesh007-lap** [comment]
Nope, Nevermind I changed to Unreal Engine 5 thanks for the help bro

**Comment by Calinou** [comment]
Alright, closing then.
