### ISSUE TITLE
class_name does not update language server

### ISSUE THREAD

**Issue by cameron-hu-ginkgo** [godotengine/godot-vscode-plugin#259]
Example:

Create script `Item.gd`:
```
extends Node
class_name Item
```

Create script `Weapon.gd`:
```
extends Item
```

Run Godot and get

Error:
Unknown class: "Item"

If I do this in the Godot editor it works perfectly

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/42786 (this is a language *server* bug).
