### ISSUE TITLE
What should editor_path be when using the flatpak version of Godot?

### ISSUE THREAD

**Issue by 3ter** [godotengine/godot-vscode-plugin#270]
## Issue

I'm trying to get the debugger running from vscode.
With the flatpak installation I don't know what to put in `editor_path` (things like `flatpak run org.godotengine.Godot`) apparently don't work.

![image](https://user-images.githubusercontent.com/11499929/120064063-c474fe00-c06a-11eb-8491-7d6c830b7be2.png)

I couldn't find help on that in the issues or the documentation.

## Reproduce

- Install latest flatpak version of Godot and vscode via the official snap
- Set up the external editor settings in Godot (`flatpak-spawn`) and install the extension godot-tools in vscode
- Add the default `launch.json` in vscode and try debugging a script

**Comment by Calinou** [comment]
Does `editor_path` require just the path to a launcher script (to make a "run in editor" action work), or does it need something more? If it just requires a path to a launcher script, you can specify `/home/YOUR_USER/.local/share/flatpak/exports/bin/org.godotengine.Godot`.

**Comment by 3ter** [comment]
Thanks @Calinou !

What did the trick for me was
```
/var/lib/flatpak/exports/bin/org.godotengine.Godot
```

I've tried `/home/<username>/.var/app/org.godotengine.Godot` before, but then there were missing permissions. I couldn't find your path on my system.

**Comment by Calinou** [comment]
> I've tried /home/<username>/.var/app/org.godotengine.Godot before, but then there were missing permissions. I couldn't find your path on my system.

It depends on whether the Flatpak was installed system-wide (the default) or user-wide. The path I gave was for user-wide installations, since I always use that personally. User-wide Flatpaks can be installed/updated/removed without requiring administrator privileges, which I find more convenient when you're the only user on a given machine.
