### ISSUE TITLE
Node paths not updating

### ISSUE THREAD

**Issue by Brin-o** [godotengine/godot-vscode-plugin#272]
I've been testing this out over the past day or so and I've noticed that it works great when I open the project for the first time. However I start running into problems when I add more nodes to existing nodes. The code project does not seem to update even tho they exist and godot start spitting errors.

## Reproducing
1. Open a script in VS Code
2. Add a new child node to the node that is associated with the script
3. Try accessing the node with $NodeName
4. The node will not show up in autocomplete and godot will output errors like this:
![image](https://user-images.githubusercontent.com/49071768/120071202-770a8800-c08e-11eb-9270-a7b2fe204e5f.png)

**Comment by DaelonSuzuka** [comment]
I *think* that improvements to the Godot Editor and its Language Server have improved this behavior.

If it's still happening, then you should open an issue on the Godot repository, because this extension doesn't control any of these errors.
