### ISSUE TITLE
[Discussion] GDScript grammar file

### ISSUE THREAD

**Issue by Vlad-Zumer** [godotengine/godot-vscode-plugin#275]
Looking through the issues, seems there are quite a few problems related to the grammar we use to highlight GDScript code.
Unfortunately I have been unable to find in the documentation the grammar for GDScript. 
Should someone from the core project provide and keep up to date a file containing the grammar, the syntax highlight could be  updated and made less prone to errors.

Issues regarding highlighting:

- #139
- #133 
- #256 
- #158 (possibly)
- #219 (possibly)

**Comment by Calinou** [comment]
There's already a GDScript grammar file: https://docs.godotengine.org/en/latest/development/file_formats/gdscript_grammar.html

**Comment by Vlad-Zumer** [comment]
The problem with both both those is that they aren't exhaustive and they are missing references to some language specifications.
Even though some of these can be implied, it would be better if we had a concrete spec.

E.g.

- Strings, multi line strings, formatted strings, escaped strings
- builtin functions
- `$` shorthand

Another solution I am looking into is having the language server generate the highlighting as well. This will however requires it to be a stand-alone application we can start via VSCode and have Godot link to it in the same way. With the current architecture `.gd` files would only have syntax highlighting if Godot is running

New architecture example
```
VSCode <---LSP---> GDScript Language Server <------> Godot
```

**Comment by Calinou** [comment]
> The problem with both both those is that they aren't exhaustive and they are missing references to some language specifications.

GDScript doesn't have a formal language specification, but I can tell you some caveats about the things you mentioned.

> - Strings, multi line strings, formatted strings, escaped strings

Strings can use the following forms:

```gdscript
"One"
'Two'

"""
Three
"""

'''
Four
'''

"""Multi-line strings do not *have* to be on multiple lines, and can contain "quoted" strings without requiring escapes (unless there are 3 quotes or more)."""
```

> - builtin functions

A list of built-in functions can be found here: https://github.com/godotengine/godot/blob/f9521d35cb4fc44d6a54e50bc7554e523c2b93ef/modules/gdscript/gdscript_functions.cpp#L46-L137

> - $ shorthand

The following paths are valid:

```
# Node names must be valid identifiers if they are not quoted. This means they can't start with a number:
$SomeNode
$"2SomeNode"

# No quotes required for paths with only node names and slashes, but they are allowed.
$SomeNode/SomeChildNode

# Quotes are required for paths that contain `..` (double or single quotes).
$"../Example"

# Quotes are also required for absolute paths (double or single quotes).
$"/root/MyNode

The following paths are invalid:

```gdscript
# Node names must be valid identifiers if they are not quoted. This means they can't start with a number:
$2SomeNode

# Path must be quoted since it contains `..`.
$../Example

# Path must be quoted since it's an absolute path.
$/root/MyNode
```
