### ISSUE TITLE
Autoload variables you declare are treated as if they don't exist

### ISSUE THREAD

**Issue by ScorpioneOrzion** [godotengine/godot-vscode-plugin#283]
As you can see in the screenshot, the global variable called `Global` is not defined in the current scope, although it also says it is declared in `res://Autoload/Global.gd`.
It's connected with the godot language server and I don't get this error in godot's built-in editor.
![image](https://user-images.githubusercontent.com/36512390/123805644-8a5b7e00-d8ee-11eb-8d91-f2dcc5609fbb.png)

`project.godot` has this included
```
[autoload]

Data="*res://Autoload/Data.gd"
Global="*res://Autoload/Global.gd"
Network="*res://Autoload/Network.gd"
```

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-vscode-plugin/issues/224#issuecomment-678579903.

**Comment by git2013vb** [comment]
> See [#224 (comment)](https://github.com/godotengine/godot-vscode-plugin/issues/224#issuecomment-678579903).

I have the same problem. I tried to close vscode and restart the project but the error in vscode is still there. any hints?
thanks
