### ISSUE TITLE
How to change editor path after having set it?

### ISSUE THREAD

**Issue by kz-n** [godotengine/godot-vscode-plugin#285]
I accidentally set the editor path to the wrong executable, By changing it from vscode settings it doesn't get saved, Is there some kind of config file I can edit?

**Comment by Razoric480** [comment]
![image](https://user-images.githubusercontent.com/2823241/125110613-cba01a80-e0b2-11eb-9c37-7f9cc7e1c879.png)
Saves fine for me

**Comment by kz-n** [comment]
Not for me, The reason i made this issue.

**Comment by Razoric480** [comment]
You could go into %appdata%\code\user and open `settings.json`. That's where `"godot_tools.editor_path"` is located.

$HOME/Library/Application Support/Code/User/ in MacOS, or $Home/.config/Code/User/ in Linux

**Comment by kz-n** [comment]
This is no longer an issue.
