### ISSUE TITLE
Implement running the project with the option "Visible Collision Shapes" enabled

### ISSUE THREAD

**Issue by marcegs** [godotengine/godot-vscode-plugin#287]
Title ¯\_(ツ)_/¯

**Comment by Calinou** [comment]
This is feasible by starting the Godot editor binary with the `--debug-collisions` command line argument. This is likely implementable in the add-on, but a toggle needs to be exposed somewhere.

Note that `--debug-navigation` can also be used alongside to show navigation meshes while the project is running.

**Comment by marcelogs924** [comment]
> This is feasible by starting the Godot editor binary with the `--debug-collisions` command line argument. This is likely implementable in the add-on, but a toggle needs to be exposed somewhere.
> 
> Note that `--debug-navigation` can also be used alongside to show navigation meshes while the project is running.

Thanks, it worked just fine. But a configuration on the launch.json or something options would be nice!

**Comment by DaelonSuzuka** [comment]
Closing because this seems to have been implemented.
