### ISSUE TITLE
Syntax error when trying to execute the project from VS Code

### ISSUE THREAD

**Issue by svprdga** [godotengine/godot-vscode-plugin#289]
I'm working in a Game in Linux. I'm trying to launch my game directly from VS Code but an error appears:

### Steps to reproduce

1. Create a Godot project in Linux
2. Create some script, open it in VS Code
3. Press ALT+shift+P to show the command palette
4. Select _Godot Tools: Run workspace as Godot project_

### Expected result

Godot game is launched.

### Actual result

I got the following error in the console:
`../project.godot: 1: Syntax error: ";" unexpected`

### Additional data

- OS: Linux Mint 20.1 Cinnamon
- Extension version: 1.1.2

### Notes

- I can launch the project normally from the Godot editor, the issue is only when I try to do it via the extension. I must say that this features has never worked for me.
- It is true that _project.godot_ starts with a `;`, but thats how it's generated initially:

```
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=4
```

**Comment by Calinou** [comment]
Did you specify the path to the Godot binary in the extension's settings? It looks like the extension is trying to execute `project.godot` as if it was a binary file.

**Comment by svprdga** [comment]
You're right @Calinou, I had it misconfigured, thank you!
