### ISSUE TITLE
Godot 3.3.3 crashes when the language server is used (fix: upgrade to 3.3.4)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-vscode-plugin#299]
This is a reminder to not open duplicate issues for https://github.com/godotengine/godot/issues/51923, as it has been fixed in [Godot 3.3.4](https://godotengine.org/article/maintenance-release-godot-3-3-4) and 3.4 beta.

**Comment by jhonalino** [comment]
thank you!

**Comment by akien-mga** [comment]
The fix is deployed in Godot 3.3.4 RC 1 and later: https://godotengine.org/article/release-candidate-godot-3-3-4-rc-1

**Comment by Calinou** [comment]
The fix is deployed in a stable release as of 3.3.4, closing. I'll leave this pinned for a bit so to make this issue easier to notice for people who haven't upgraded yet.

**Comment by atirut-w** [comment]
Unpin?
