### ISSUE TITLE
bash: syntax error near unexpected token `&' on Windows using Git Bash

### ISSUE THREAD

**Issue by kagof** [godotengine/godot-vscode-plugin#302]
I have Git Bash configured as my default terminal on Windows. I did this through VS Code's GUI on the most recent version. However, after doing this, the "Open Godot Editor" command no longer works - I get:

```
bash: syntax error near unexpected token `&'
```

I looked into the code of this plugin, and have realized it is probably due to [this section](https://github.com/godotengine/godot-vscode-plugin/blob/5c5c19b534ba4a8faf48c6c9eab8ba836a82fb10/src/godot-tools.ts#L89):

```ts
const shell_plugin = vscode.workspace.getConfiguration("terminal.integrated.shell");
let shell = (shell_plugin ? shell_plugin.get("windows", POWERSHELL) : POWERSHELL) || POWERSHELL;
if (shell.endsWith(POWERSHELL) || shell.endsWith(POWERSHELL_CORE)) {
	cmdEsc = `&${cmdEsc}`;
}
```

When looking at my VS Code settings, I do not have `terminal.integrated.shell.windows` set, instead I have `"terminal.integrated.defaultProfile.windows": "Git Bash"`. When I attempt to set `terminal.integrated.shell.windows`, I get the following warning:

![terminal_shell](https://user-images.githubusercontent.com/17553493/136675401-6825ad67-ebe0-4c65-bfef-a1d8ca3f93d0.png)

I'm happy to open a Pull Request to address this issue, if the maintainers are willing to accept one. My idea would be to update this section to respect `terminal.integrated.shell.windows` if it is present, falling back to `terminal.integrated.defaultProfile.windows` (and then of course falling back to the default of `POWERSHELL`). This will closely resemble the behaviour of VS Code, as described in the warning.

This is using:
Windows 10
Godot 3.3.4
godot-tools v1.1.2
VS Code 1.61.0

**Comment by Calinou** [comment]
> I'm happy to open a Pull Request to address this issue, if the maintainers are willing to accept one.

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by kagof** [comment]
@Calinou I've opened [A PR](https://github.com/godotengine/godot-vscode-plugin/pull/303) addressing this issue :)
