### ISSUE TITLE
Does the plugin support godot 3.4 now?

### ISSUE THREAD

**Issue by AliceDreamland** [godotengine/godot-vscode-plugin#306]

**Comment by Calinou** [comment]
This plugin should work with Godot 3.4, but there are still many known bugs that occur with any Godot version (see open issues in this repository).

**Comment by AliceDreamland** [comment]
> This plugin should work with Godot 3.4, but there are still many known bugs that occur with any Godot version (see open issues in this repository).

Thanks for your reply
