### ISSUE TITLE
Keywords in strings detected as expressions

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot-vscode-plugin#31]
Example ('for' is part of the string, yet it's detected as an expression):

![shot_170805_123949](https://user-images.githubusercontent.com/7307968/28994937-5f71be96-79db-11e7-9027-64f6d24d6936.png)

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the release page
