### ISSUE TITLE
Add refactor/rename feature

### ISSUE THREAD

**Issue by Anudin** [godotengine/godot-vscode-plugin#32]
Refactoring in Godots native editor is a nightmare for me.  Rename one node and create possible bugs all over the place. VS code seems to have a proper rename function which changes variable occurences but as https://github.com/Microsoft/vscode/issues/7213 states this has to be added to the language extension as it is highly language specific.
My only alternative is "Change all occurences" which also changes strings - not the wanted behaviour. This would be an awesome feature and I bet one many Godot devs would like.

**Comment by Geequlim** [comment]
This would be awesome to support that.
But for now the plugin cannot implement that as it is too complicate for me and I don't have enough time to do that.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/899.

It appears there's already built-in refactoring support in the LSP, but it's not used within the built-in Godot script editor.

**Comment by atirut-w** [comment]
> According to [godotengine/godot-proposals#899 (comment)](https://github.com/godotengine/godot-proposals/issues/899#issuecomment-1077809766), there's already built-in refactoring support in the LSP, but it's not used within the built-in Godot script editor.

Can confirm this. F2 in VSCode on variables and classes works.

**Comment by Calinou** [comment]
Closing, as this is already implemented in this extension.

**Comment by reidhannaford** [comment]
@Calinou Hi all, I'm a bit confused about this thread. F2 does indeed work to rename variables/functions/classes/etc within a script in VSCode, but it _does not_ rename across your whole project / multiple files. It only changes within that one script file.

Ctrl+shift+r does nothing - it just says "no refactors available" - even when connected to the LSP.

Is there a PR to implement project wide refactoring either in VSCode or in the native editor? I feel like this is a critical feature for any kind of scalability in code. Without the ability to refactor GDscript is severely limited for larger (or even medium sized) projects. I'm happy to open a PR but figured one must already exist.

**Comment by DaelonSuzuka** [comment]
@reidhannaford If you want different/better behavior than you need to open an issue on the engine. This feature is 100% provided by the Language Server, which I do not control.

**Comment by reidhannaford** [comment]
@DaelonSuzuka Thanks for the reply! I want to clarify that in my ignorance I thought PR stood for "Proposal Request" and not "Pull Request" - so I was really asking if someone had opened a proposal. I see there is a (quite popular) proposal for the engine to implement better refactoring. Are you saying if this was implemented on the engine side it would make it possible to implement on the VScode extension side?

**Comment by DaelonSuzuka** [comment]
> Are you saying if this was implemented on the engine side it would make it possible to implement on the VScode extension side?

Yep! In fact, if it was implemented in the language server it would _automatically_ work in VSCode.
