### ISSUE TITLE
getting an error in output upon autocompletion

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot-vscode-plugin#320]
when vscode trigger autocompletion, the output log triggers this error:

`servers\visual\visual_server_scene.cpp:764 - Index p_surface = 0 is out of bounds (instance->materials.size() = 0)`

what's interesting about it:
- my colleagues working off of the same project with vscode do no get the error
- ~~I do not get the error in other projects. The error is not triggered in other projects.~~
- At one point I thought I found what the error was triggered by (particle system emitting a custom mesh, so I went ahead and deleted it, recreated the scene and it still got triggered.

If someone wanted to investigate, I can give you access to our games repo. We're well into the project to start anew and i haven't been able to find what's causing it.

**Comment by lentsius-bark** [comment]
after further debugging I can see this is being triggered by Sprite3D

**Comment by Calinou** [comment]
> after further debugging I can see this is being triggered by Sprite3D

Can you reproduce this when only using the built-in script editor?

**Comment by lentsius-bark** [comment]
@Calinou no, when using the built in editor the error does not get triggered.

It may be related to whenever a custom mesh is used? Not sure.

**Comment by lentsius-bark** [comment]
I updated the original comment as this does indeed happen in all projects, though I am not 100% at what point it gets triggered, I've narrowed it down to the fact that there is a mesh instance or a sprite3d in the scene of the edited file, which does not have its surface material set in any way.

**Comment by lentsius-bark** [comment]
just wanted to mention that this issue has disappeared, and therefore I'm closing this issue.
