### ISSUE TITLE
Missing properties, methods and signals  in "List Native Classes in Godot"

### ISSUE THREAD

**Issue by zbyna** [godotengine/godot-vscode-plugin#321]
Using  ```Godot_v3.4.3-rc2_win64``` 
and ```vscode 1.64.2 (system setup) OS: Windows_NT x64 6.1.7601 ```  +  ```godot-tools v1.1.3```

![](https://i.imgur.com/2MYjuqX.gif)

Tested also with ```Godot_v3.4.2-stable_win64``` - the same result.

**Comment by Calinou** [comment]
I don't understand what's wrong on the GIF. Can you further describe, please?

**Comment by zbyna** [comment]
No problem.  In my opinion there is not info on properties, methods and signals with their description as in documentation viewer in Godot application and as is presented in readme of this repo.

Missing info in addon:
![E4-EF685-B-02-DB-4-D3-E-AD73-AEA7-BEC5885-E.jpg](https://i.postimg.cc/kXC6GKCx/E4-EF685-B-02-DB-4-D3-E-AD73-AEA7-BEC5885-E.jpg)

Info presented in readme:
![image](https://user-images.githubusercontent.com/3373705/155402412-005b4a00-cb9c-4f07-9c5a-92b051338166.png)

**Comment by Calinou** [comment]
Unfortunately, I don't know when this feature regressed (or whether it's linked to the Godot editor version in use).

**Comment by zbyna** [comment]
|   **``` GODOT```**      | ```godot-tools v1.1.3``` | ```godot-tools v1.1.2``` |
|:--------------------------------:|:------------------------:|:------------------------:|
| ```v3.5-beta1```  | same                     | same                     |
| ```v3.4-stable```   | same                     | same                     |
| ```v3.3.3-stable```  | same                     | same                     |
| ```v3.3.3-rc2```    | same                     | same                     |
| ```v3.3.3-rc1```     | bad see image ![](https://i.imgur.com/fAZCTBE.png)             | bad - see image ![](https://i.imgur.com/1h7tnvf.png)         |
| ```v3.3.2-stable``` | empty document           | OK   - see image ![](https://i.imgur.com/KiUdGl3.png)                     |
| ```v3.3.1-stable``` | empty document           | OK                       |
| ```v3.3-stable```   | empty document           | OK                       |
| ```v3.2-stable```    | empty document (no tcp)  | OK (no tcp)              |
| ```v3.1-stable```   | not possible to connect    |                   |

![](https://i.imgur.com/fAZCTBE.png)  
![](https://i.imgur.com/1h7tnvf.png)
![](https://i.imgur.com/KiUdGl3.png)

**Comment by zbyna** [comment]
Just only gamble from my side :slightly_smiling_face:   What about this commit  https://github.com/godotengine/godot/pull/50914/commits/02bc1bf355183b3c425819c84dec3ad0512fc0cf ?
