### ISSUE TITLE
Plugin blocks editor builtin documentation popup

### ISSUE THREAD

**Issue by boruok** [godotengine/godot-vscode-plugin#328]
**Issue description**
Noticed that editor builtin documentation (**F1**) doesn't appears if plugin is connected to editor.

**Steps to reproduce**
1. Run vscode
2. Select godot project/folder
3. Press **Open Godot Editor** in popup message
4. Press F1 to open builtin documentation in editor

**Versions**
godot-tools: v1.1.3
godot: v3.4.3.stable.official [242c05d12]
os: debian 11 bullseye

edit: added os version

**Comment by Calinou** [comment]
This is likely an issue with the Godot editor itself, not the VS Code plugin (it's only a *client*).

**Comment by boruok** [comment]
@Calinou should i open issue in editor?
