### ISSUE TITLE
Syntax highlighting partially fails for signal forward declarations with parameters 

### ISSUE THREAD

**Issue by knochenhans** [godotengine/godot-vscode-plugin#334]
### Godot version

3.4.4

### VS Code version

1.65.2

### Godot Tools VS Code extension version

1.1.3

### System information

Arch Linux

### Issue description

Syntax highlighting fails for me when I add parameters to signal forward declarations, the colour is set to standard grey for the following text up to the first function definition. I attached a GIF screen recording that shows the difference when I add/delete the parameter.

![Peek 2022-03-30 23-41](https://user-images.githubusercontent.com/5293125/160935880-8bd35918-44f3-48c6-be27-b2e5bcacf987.gif)

### Steps to reproduce

Add a signal forward declaration with a parameter.

**Comment by DaelonSuzuka** [comment]
I'm currently overhauling the syntax highlighting and I'll make sure this is addressed.

**Comment by knochenhans** [comment]
Many thanks :) by the way, this also seems to happen for return type annotations:
![grafik](https://user-images.githubusercontent.com/5293125/162722979-f28a66ea-f395-438e-aa69-6131b4b9ac3d.png)

**Comment by DaelonSuzuka** [comment]
No problem. There legitimately was a known issue with signal declarations, so it wasn't a stretch to think there could be more problems.
