### ISSUE TITLE
Overaggressive formatting when adding new lines after an if statement

### ISSUE THREAD

**Issue by ZachIsAGardner** [godotengine/godot-vscode-plugin#337]
### Godot version

3.4.4

### VS Code version

1.66.0

### Godot Tools VS Code extension version

1.1.3

### System information

Windows 10

### Issue description

![gdscript_extension_bug_2](https://user-images.githubusercontent.com/30502195/161106385-799a9321-e671-4225-899f-a919f0244891.gif)

As seen in the gif above, if I try to move a line down with either an "enter" key press or with the "move line down" shortcut command it indents it and adds it to the previous if statements block.

![gdscript_extension_bug_3](https://user-images.githubusercontent.com/30502195/161107146-07d69410-c0a7-4114-a00c-a11f2dbf86c4.gif)

Here's another example where I'm trying to copy paste something. It seems to work if I undo after pasting, but it's still a little annoying.

### Steps to reproduce

Try moving a line down after an if statement, or paste something after an if statement

**Comment by was-games** [comment]
confirmed on the master branch

**Comment by ZachIsAGardner** [comment]
I just tried this again it looks like it's fixed for Enter, but it's still behaving the same for **Move Line Down**, **Move Line Up**, and Pasting.

I'm using v1.3.1 of this plugin.

![5060](https://user-images.githubusercontent.com/30502195/172771271-9f582456-7320-49d7-b9a3-c050104cfdb6.gif)
