### ISSUE TITLE
Step over not working

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#347]
### Godot version

v3.4.3.stable.official [242c05d12]

### VS Code version

1.66.2

### Godot Tools VS Code extension version

1.2.0

### System information

Fedora 35

### Issue description

When reaching a breakpoint and stepping over, execution continues instead of stopping on the next line.

https://user-images.githubusercontent.com/25323231/163338091-9f833a74-09aa-48a9-9be9-a0a658316461.mp4

### Steps to reproduce

1. Place down a breakpoint
2. Start debugging
3. Step over when you reach the breakpoint

**Comment by atirut-w** [comment]
Sorry for the bump, but is this issue getting anywhere?

**Comment by Calinou** [comment]
This may be a bug in the language server, rather than the extension. Note that we have very few contributors working on this extension and the language server, so this may take a while to be fixed.

**Comment by DaelonSuzuka** [comment]
@atirut-w Your video file is apparently corrupt now. 

Could I get you to confirm that you're still experiencing this issue with godot-tools `1.3.1` and Godot `3.5stable`?

We had a debugger-related regression back in may (#370) that was allegedly fixed in #371. I don't use the debugger a lot, but when I was trying to confirm that problem, I thought that breakpoints and stepping mostly worked.

**Comment by atirut-w** [comment]
> Your video file is apparently corrupt now.

I can watch still watch it just fine though?



> Could I get you to confirm that you're still experiencing this issue with godot-tools `1.3.1` and Godot `3.5stable`?
> 
> We had a debugger-related regression back in may (#370) that was allegedly fixed in #371. I don't use the debugger a lot, but when I was trying to confirm that problem, I thought that breakpoints and stepping mostly worked.

It indeed seems to be fixed. If it starts happening again in the future, do I open new issue or resurrect this one?

**Comment by DaelonSuzuka** [comment]
> I can watch still watch it just fine though?

<details>
<summary>Probably just GitHub being dumb.</summary>

![image](https://user-images.githubusercontent.com/18042232/185047991-33365098-ea9a-4795-9668-981f9f7f6e8f.png)

</details>

> do I open new issue or resurrect this one?

Feel free to reopen this one and tag me. Unfortunately, I have a feeling that this debugger behavior is intermittent, so you might be back very soon.

**Comment by atirut-w** [comment]
> I have a feeling that this debugger behavior is intermittent, so you might be back very soon.

That's foreshadowing...

**Comment by atirut-w** [comment]
@DaelonSuzuka so uh it started happening again and I have no idea what triggered it. This seems like a pain to make a repro project so I'll link to where the behavior is pretty random in my project:

https://github.com/atirut-w/piano-game/blob/d0d3d1ce0fc3ed9a11b2e81f63b0de5a94686c5f/scenes/piano_roll/piano_roll.gd#L43

**Comment by DaelonSuzuka** [comment]
@atirut-w Are you still experiencing this issue using the new `2.0.0`?

**Comment by atirut-w** [comment]
Your debugger overhaul worked *wonders*. You're the GOAT.
