### ISSUE TITLE
Add a command to run and debug current scene

### ISSUE THREAD

**Issue by TremblingInferno** [godotengine/godot-vscode-plugin#349]
### Godot version

3.4.1.stable.goost.official

### VS Code version

1.66.2

### Godot Tools VS Code extension version

1.2.0

### System information

Pop Os 21.10

### Problem statement

This might already exist, but is there a way to open and debug the current open scene? This is something essential for debugging large projects, but if it already exists, I can't find it.

### Proposed solution

add a command that opens a *.tscn file in debug mode.

**Comment by DaelonSuzuka** [comment]
Using the latest release `2.0.0`, you can now create a new debug profile in `launch.json` that will launch the current scene  (or a scene that matches the currently open GDScript file).

```json
{
	"name": "Launch Current Scene",
	"type": "godot",
	"request": "launch",
	"scene": "current"
}
```
