### ISSUE TITLE
First line of every .gd file has an `Error (test)`

### ISSUE THREAD

**Issue by GGalizzi** [godotengine/godot-vscode-plugin#351]
### Godot version

v3.5.beta3.official [3c0d32562] and v3.4.4.stable.official [419e713a2]

### VS Code version

Version: 1.66.2 (user setup) Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977 Date: 2022-04-11T07:46:01.075Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Windows_NT x64 10.0.19042

### Godot Tools VS Code extension version

v1.2.0

### System information

Windows 10

### Issue description

The title pretty much is all there is to say, very weird issue, here's a screenshot, I'm not sure if it's something with my setup. I've tried both 3.5 beta and 3.4 stable.

![Code_3g1D1jqz57](https://user-images.githubusercontent.com/2095078/164917183-83428ea1-61ec-4591-bfef-5cd52a784acd.png)
 

### Steps to reproduce

* Start new project.
* Add a .gd script
* Open it up in vscode
* Start writing something
* See `Error (test)` under `extends XYZ`. (You can open up a line above the extends to see that it's not specifically about the `extends`

**Comment by Calinou** [comment]
Aa of 2cfbed2dad10d9c576d4b1d9ae3667ccf8c4a44b, I see no instance of `test` within this extension's codebase:

![image](https://user-images.githubusercontent.com/180032/164932906-fc7f83a7-eddd-40c4-9e9c-b191a2ae009f.png)

**Comment by GGalizzi** [comment]
Never mind, after having another look at my extensions I found the culprit to be [another extension](https://github.com/kuhnchris/vscode-formatter-godot) that hasn't been updated in a while
