### ISSUE TITLE
Call stack status not resetting when debugging is restarted

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#372]
### Godot version

v3.4.4.stable.official [419e713a2]

### VS Code version

1.67.2

### Godot Tools VS Code extension version

1.3.0

### System information

N/A

### Issue description

When debugging is paused by anything(breakpoints, error) and restarted, the call stack status stays the same.

Before breakpoint:
![Screenshot_20220526_012733](https://user-images.githubusercontent.com/25323231/170339601-ca64455b-1096-466f-933c-0d9e54df4a55.png)

Breakpoint reached:
![Screenshot_20220526_012445](https://user-images.githubusercontent.com/25323231/170339073-4691a214-60cb-4a3b-9c5a-419a90ea317e.png)

After restart(Ctrl+Shift+F5). Notice how it says "Paused on breakpoint" even though the game is not actually paused:
![Screenshot_20220526_012536](https://user-images.githubusercontent.com/25323231/170339191-64f5643e-f62f-422f-b887-8c5e7790093e.png)

### Steps to reproduce

1. Set a breakpoint
2. Start debugging and reach the breakpoint
3. Restart
4. Call stack status doesn't reset to "Running"

**Comment by DaelonSuzuka** [comment]
`2.0.0` includes a rewritten debugger that reliably starts, stops, and resets.
