### ISSUE TITLE
"launch_scene" debug setting not working properly

### ISSUE THREAD

**Issue by MightyW0lf** [godotengine/godot-vscode-plugin#377]
### Godot version

3.4.4.stable

### VS Code version

1.67.2

### Godot Tools VS Code extension version

1.3.0

### System information

Windows 10 21H1

### Issue description

[Video demonstration](https://youtu.be/LKV-yU7Qf4Q)

When launching debugger with `"launch_scene": true` in a Godot project without a Main scene, the debugger doesn't work (Godot Project Manager is launched instead in a glitched window). Also worth noting that even after setting the Main scene, the debugger is still running after closing the scene window and throws the same _"Failed to launch Godot instance: null"_ error in VSCode, despite working otherwise (as seen in the video).

### Steps to reproduce

Using `launch.json`:

```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Godot Scene",
      "type": "godot",
      "request": "launch",
      "project": "${workspaceFolder}",
      "port": 6007,
      "address": "127.0.0.1",
      "launch_game_instance": true,
      "launch_scene": true
    }
  ]
}
```

* Launch debug with `.tscn` file opened in a Godot project, that has no Main scene.

**Comment by atirut-w** [comment]
Have you set the Godot Path settings?

**Comment by MightyW0lf** [comment]
Yup, `"godot_tools.editor_path": "F:\\Program Files\\Godot_v3.4.4-stable_win64\\Godot_v3.4.4-stable_win64.exe"`.

**Comment by Calinou** [comment]
Does it work if you move the Godot executable to the C: drive? Also try moving it to a path that doesn't contain any spaces or special characters.

**Comment by MightyW0lf** [comment]
Tested with `godot_tools.editor_path": "C:\\Users\\Wolfe\\Downloads\\Godot_v3.4.4-stable_win64.exe`, no change.

But! I have some issues with breakpoints not working and I've found this [issue](https://github.com/godotengine/godot-vscode-plugin/issues/370), so I tried downgrading the extension to 1.2.0 and now the `launch_scene` works correctly (as well as breakpoints).

**Comment by Calinou** [comment]
Can you test 1.3.1 which was just released? You can find a VSIX [here](https://github.com/godotengine/godot-vscode-plugin/releases/tag/1.3.1).

**Comment by MightyW0lf** [comment]
Yup, seems like both breakpoints and the `launch_scene` setting now work as intended, even if the Main scene is not set.
