### ISSUE TITLE
Output window only shows recent values after unfocusing and focusing it

### ISSUE THREAD

**Issue by ZachIsAGardner** [godotengine/godot-vscode-plugin#382]
### Godot version

3.4.4.stable

### VS Code version

1.68.0

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

I have a print command in the _process function, it simply outputs a number that increases every _process call. The problem you can only see the current output if you unfocus and refocus the Output window.

![godot_output](https://user-images.githubusercontent.com/30502195/173154612-ed3a6e6f-bf65-4c9b-b959-ba4ed7941d64.gif)

### Steps to reproduce

- Put a print call in the _process function
- Run project
- The output window will be empty
- Unfocus and refocus window
- Output will show recent values

**Comment by DaelonSuzuka** [comment]
As part of the debugger rewrite, the game's stdout has been moved from an output channel(why was it there?) to it's rightful place in the debug console. As such, I'm very certain this issue doesn't happen anymore.
