### ISSUE TITLE
Strange syntax error ： Error(test)

### ISSUE THREAD

**Issue by xmyhhh** [godotengine/godot-vscode-plugin#390]
### Godot version

3.3.4

### VS Code version

1.68

### Godot Tools VS Code extension version

1.31.

### System information

windows 11

### Issue description

<img width="341" alt="image" src="https://user-images.githubusercontent.com/31955947/175855134-9f666e49-296f-4278-9692-31a3329a6f8a.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/31955947/175855293-8ed694ef-c075-4a1d-9b12-a01d132751f5.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/31955947/175855484-e2d804fb-d925-4ccf-9f28-ab1124979ecb.png">

As you can see in the picture, this simple code has no problem in Godot built-in IDE and the scenario can run normally, while vs code gives reported syntax errors and even code comments, why is this so? 

### Steps to reproduce

just create a script and open it with vs code

**Comment by xmyhhh** [comment]
After I reinstalled vs code（remove all user cache files） on my computer problem was solved Although I still don't know how this caused it!
So close it

**Comment by xmyhhh** [comment]
Finally, I found out what was causing this problem
Just now this problem appeared again after I installed a Godot formatter plugin

https://marketplace.visualstudio.com/items?itemName=KuhnChrisEU.vscode-formatter-godot

This plug-in is the culprit, and I hope the author of this plug-in sees the problem and tries to fix it later.

This answer is recorded here for those who encountered this problem afterwards

**Comment by kuhnchris** [comment]
Looks like the gdtoolkit isn't available - áka gdlint and gdformatter. (see readme) - this is unrelated to *this* plugin tho.
