### ISSUE TITLE
"Open Godot Editor" button starts wrong project if godot-cpp is part of the project

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot-vscode-plugin#391]
### Godot version

3.5 RC 6

### VS Code version

1.68

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

godot-cpp has a test project as part of it's repository and Godot Tools will gladly open that one instead of the main project.godot file in the main directory.
![image](https://user-images.githubusercontent.com/1295635/178233734-0c789c7d-b6a1-4eb2-b99c-48e5013e2f44.png)

### Steps to reproduce

Clone godot-cpp into your Godot project.
Open godot project folder in VSCode
Press "Open Godot Editor"

**Comment by API-Beast** [comment]
Okay so it asks you at the start what project file to use, though it is easy to overlook and there is no obvious way to change the project after the fact, so maybe more of an UX issue?

**Comment by API-Beast** [comment]
Ok turns out that button was actually part of another extension and not part of Godot Tools.

I would suggest adding a little button in the status bar to change the current project like this:
![image](https://user-images.githubusercontent.com/1295635/178261256-904ee2cb-2ef7-41fe-baa9-e875f8bd1ad6.png)

**Comment by KoBeWi** [comment]
I have the same problem. It's unrelated to godot-cpp, seems like the plugin favors nested projects for some reason.

Some relevant code I found:
https://github.com/godotengine/godot-vscode-plugin/blob/55617fdd398100991cc61f489646b71b15d0fbd5/src/extension.ts#L98-L106
Seems like it just uses the first result, so maybe `findFiles()` is depth-first, idk.

**Comment by DaelonSuzuka** [comment]
@KoBeWi Sorry for the delay in addressing this. I've changed it to favor the top-most `project.godot`.

**Comment by DaelonSuzuka** [comment]
Hopefully fixed in #553.

Eventually I'll implement something like the QuickPick from the C-Sharp extension, but doing that correctly would require rewriting the extension's entire startup sequence.

**Comment by DaelonSuzuka** [comment]
With the release of 2.0.0, I think this issue has been resolved.
