### ISSUE TITLE
Godot 4 Alpha 13 - "Unable to read file '[path]/[script_name].gd' ..." when clicking on a reported problem.

### ISSUE THREAD

**Issue by farfalk** [godotengine/godot-vscode-plugin#401]
### Godot version

4.0.alpha13

### VS Code version

1.69.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

See image below. 
![image](https://user-images.githubusercontent.com/9095842/182134471-aec3b3cd-c396-4fc4-84fb-83b1ea348c66.png)

[Note: the problem reported seems to be new to Godot 4 alpha 13 as well, will investigate and open issue if confirmed - but the behaviour DOES NOT DEPEND on the error, it happens everytime]

I'm using the official Godot 4 alpha 13 build in self-contained mode, deleting all configs and temp folders every time I update, so the Godot installation is completely clean.

### Steps to reproduce

1. a problem is highlighted in your code
2. you click the problem, expecting to be brought to the affected code
3. the reported problem is encountered

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-vscode-plugin/pull/400.

**Comment by farfalk** [comment]
Not willing to bump, just leaving an info for whoever might be interested:

For the time being, **until ALPHA 12, most of the basic functionality of this extension is still intact.**

From alpha 13 onward, even opening scripts might lead to... "unforeseen consequences" - to the point of data loss (happened once, but once is enough).

**Comment by farfalk** [comment]
Godot 4 Alpha 16 fixed this problem.
