### ISSUE TITLE
Add support for documentation in other languages

### ISSUE THREAD

**Issue by JeremyFredLin** [godotengine/godot-vscode-plugin#409]
### Godot version

3.5.stable

### VS Code version

1.70.1

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Problem statement

There is only English documentation now, I hope to add support for documentation in other languages

### Proposed solution

Add support for documentation in other languages

**Comment by DaelonSuzuka** [comment]
The documentation is provided 100% by the language server, which runs in your Godot Editor.

A cursory inspection reveals that changing the editor's language DOES change the language of the docs when Godot itself displays them, so in theory that information should be accessible to the language server.

It should be possible to modify the language server to either return the docs in the editor's selected language, or to allow the language client(this extension) to specify the desired language for the docs. 

I would recommend opening a [feature proposal](https://github.com/godotengine/godot-proposals/issues) to see if anybody else is interested in this improvement.

**Comment by DaelonSuzuka** [comment]
@HolonProduction This is a capability that's been requested many times. Since the in-editor docs support languages, hopefully that logic could be reused in the LSP server?

**Comment by TangTangH** [comment]
Godot4.5 has implemented multilingual support for documents, and I have seen it. DaelonSuzuka, thank you for your efforts, 谢谢
