### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by wayrboy** [godotengine/godot-vscode-plugin#412]
### Godot version

v3.5.stable.official [991bb6ac7]

### VS Code version

1.70.0

### Godot Tools VS Code extension version

1.3.1

### System information

windows 10

### Issue description

PS H:\godot\newFengXue> &"G:\SteamLibrary\steamapps\common\Godot Engine\godot.windows.opt.tools.64.exe" --path "h:\godot\newFengXue" -e
PS H:\godot\newFengXue> 
Godot Engine v3.5.stable.official.991bb6ac7 - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce RTX 2070/PCIe/SSE2
Async. shader compilation: OFF
 
thirdparty/mbedtls/library/ssl_tls.c:2702: x509_verify_cert() returned -9984 (-0x2700)
ERROR: TLS handshake error: -9984
   at: _do_handshake (modules/mbedtls/stream_peer_mbedtls.cpp:87)
mbedtls error: returned -0x2700

### Steps to reproduce

![image](https://user-images.githubusercontent.com/15027345/185529337-5479914e-3cff-47f5-80be-1957431de5c8.png)
![image](https://user-images.githubusercontent.com/15027345/185529370-3fb593ac-b5a8-4550-bff8-d9f7e24f65a7.png)

**Comment by Calinou** [comment]
There's a typo in the LSP server host address. It should be `127.0.0.1`, not `127.0.01`.

**Comment by atirut-w** [comment]
Close, then?
