### ISSUE TITLE
Grammar contains several invalid regex with lookbehind assertions that are not a fixed length

### ISSUE THREAD

**Issue by lildude** [godotengine/godot-vscode-plugin#415]
### Godot version

N/A

### VS Code version

N/A

### Godot Tools VS Code extension version

master

### System information

N/A

### Issue description

👋 I'm the lead maintainer of the https://github.com/github/linguist library which is used for language detection and providing the syntax highlighting for languages on GitHub.com, and we use this grammar.

Our grammar compiler has found several problems with the grammars which I thought I'd let you know about:

- Invalid regex in grammar: `source.gdscript` (in `syntaxes/GDScript.tmLanguage.json`) contains a malformed regex (regex "`\b(?<=for\s[\w]*\s)(in)\b`": lookbehind assertion is not fixed length (at offset 18))
- Invalid regex in grammar: `source.gdshader` (in `syntaxes/GDShader.tmLanguage.json`) contains a malformed regex (regex "`(?<=[.]\s*)(?:[xyzw]{2,4}|[rgba]`...": lookbehind assertion is not fixed length (at offset 10))
- Invalid regex in grammar: `source.gdshader` (in `syntaxes/GDShader.tmLanguage.json`) contains a malformed regex (regex "`(?<=[.]\s*)[a-zA-Z_]\w`": lookbehind assertion is not fixed length (at offset 10))

### Steps to reproduce

View each of the regexes in turn in regex101 and note the errors:

- https://github.com/godotengine/godot-vscode-plugin/blob/e7674c12adef55d13d17ee66b057a3f1789a2102/syntaxes/GDScript.tmLanguage.json#L298

  https://regex101.com/r/TFZmub/1

- https://github.com/godotengine/godot-vscode-plugin/blob/e7674c12adef55d13d17ee66b057a3f1789a2102/syntaxes/GDShader.tmLanguage.json#L345

  https://regex101.com/r/JX03EY/1

- https://github.com/godotengine/godot-vscode-plugin/blob/e7674c12adef55d13d17ee66b057a3f1789a2102/syntaxes/GDShader.tmLanguage.json#L349

  https://regex101.com/r/2Zpu1I/1

**Comment by Calinou** [comment]
cc @DaelonSuzuka 

PS: I didn't know this repository was used as a basis for Linguist.

**Comment by lildude** [comment]
We've been using it for GDScript since 2020 thanks to https://github.com/github/linguist/pull/5000 😁

**Comment by DaelonSuzuka** [comment]
Thanks for reporting this. I'll try to look into these issues this weekend.

@lildude Is there documentation somewhere for how I can run your grammar compiler myself, so I can try and catch issues sooner?

**Comment by DaelonSuzuka** [comment]
That's fantastic, thanks for the write-up. When I get these issues fixed, I'll comment in github/linguist#3924 to let you know.

**Comment by DaelonSuzuka** [comment]
> To do this, clone the repo and run script/bootstrap to download and all the grammars. You can then check an individual grammar using: script/grammar-compiler add vendor/grammars/godot-vscode-plugin/:

It might be worth mentioning to install all of linguist's dependencies, including `bundler`, before trying to run the bootstrap script. I'm dumb enough that it took me about ten minutes to figure that out.

**Comment by DaelonSuzuka** [comment]
This issue is resolved by PR #416, but I don't believe everything has been propagated through Linguist to Github itself, yet.

@lildude should I create an issue over at linguist to request a new release?

**Comment by lildude** [comment]
No. Please don't. It'll happen when it happens as per the docs  [here](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting) and [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes).
