### ISSUE TITLE
Wrong boolean highlight color in dictionary

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#418]
### Godot version

v3.5.stable.arch_linux

### VS Code version

1.71.0

### Godot Tools VS Code extension version

1.3.1

### System information

N/A

### Issue description

Boolean values in dictionaries are highlighted with the wrong color if the line does not end with a... yeah idk what it's called. GH also seem to have this problem too??

![Screenshot_20220909_061909](https://user-images.githubusercontent.com/25323231/189242498-51945ff9-31e6-4016-b466-17808780db8a.png)

![Screenshot_20220909_062404](https://user-images.githubusercontent.com/25323231/189242650-399fc104-89fa-403f-9a80-391b57cc9e80.png)

### Steps to reproduce

```gdscript
const black_keys := {
	1: true,
	4: true,
	6: true
}
```

**Comment by Calinou** [comment]
cc @DaelonSuzuka

**Comment by DaelonSuzuka** [comment]
Thanks for the report. The fix for this should be included in the next release.

![Code_uKmPXxuT2m](https://user-images.githubusercontent.com/18042232/189262454-1360e3ce-48a6-4cda-bec6-2b550b1404bb.png)
