### ISSUE TITLE
Function signatures are cut off in autocompletion tooltip

### ISSUE THREAD

**Issue by ash-hashtag** [godotengine/godot-vscode-plugin#421]
### Godot version

3.4.4 stable

### VS Code version

1.71.0

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

When typing it previews only half of the 
![image](https://user-images.githubusercontent.com/94179580/189393881-5b1f0da3-caad-4950-bef0-e3b9551a035e.png)

when pressed tab it fills exactly what it shows till, not too bad but annoying

or is this only my problem? Not just this it is acting very weird I can't use, like putting "quotes" unnecessarily, and putting ( randomly while typing, well when letting autofill to be precise

### Steps to reproduce

just type any function with big name

**Comment by Calinou** [comment]
> or is this only my problem? Not just this it is acting very weird I can't use, like putting "quotes" unnecessarily, and putting ( randomly while typing, well when letting autofill to be precise

This is a known issue from the language server (not this extension): https://github.com/godotengine/godot/issues/48436

**Comment by atirut-w** [comment]
I guess this can be closed then?

**Comment by DaelonSuzuka** [comment]
> I guess this can be closed then?

Yes it can.
