### ISSUE TITLE
`OS` should be highlighted as a class

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#425]
### Godot version

v3.5.stable.arch_linux

### VS Code version

1.71.2

### Godot Tools VS Code extension version

1.3.1

### System information

N/A

### Problem statement

`OS` is highlighted similarly to `func`, `var`, etc. which seems to be incorrect even according to Godot's script editor:

![Screenshot_20220923_123834](https://user-images.githubusercontent.com/25323231/191897997-a8a8ab4f-e698-4df5-a343-27a89f26fd59.png)
![Screenshot_20220923_123855](https://user-images.githubusercontent.com/25323231/191898015-6cc1bef6-ac1e-4c45-b43b-d469911a504c.png)

### Proposed solution

Change the highlight color to be the same as other singletons.

**Comment by DaelonSuzuka** [comment]
Already fixed in #402.
