### ISSUE TITLE
unable to complete initial setup

### ISSUE THREAD

**Issue by ka0s420** [godotengine/godot-vscode-plugin#428]
### Godot version

4 beta 2

### VS Code version

1.71.2

### Godot Tools VS Code extension version

1.3.1

### System information

windows 10

### Issue description

When following the instructions to setup godot tools for vscode, its says to open the command palled and type "Debug: Open launch.json" - however when doing so vscode's suggestion bar shows nothing, and pressing enter does nothing. Without this step working, I can't install the addon.

### Steps to reproduce

install vscode. Get the godot tools addon, open the command palette, type Debug: Open launch.json
![godot_tools_error_pic](https://user-images.githubusercontent.com/23391250/193676474-92cc5ec4-2cb6-4ff2-9e2c-93453dfcbdac.png)

**Comment by ka0s420** [comment]
So a simple work around to this would be simply to add to the instructions that if no launch.json files exists, you may need to make your own. I've since done that, and found the button to load a gdscript config - none of which is mentioned in the setup instructions. 

Now I'm just stuck unable to get the debugger to actually run.

**Comment by atirut-w** [comment]
Opening the "Run and Debug" tab from the menu on the left side and choosing "create a launch.json file" should be more convenient for you. The extension provides a launch.json preset.
