### ISSUE TITLE
Broken language analysis in GDScript since introduction of "Scene unique nodes"

### ISSUE THREAD

**Issue by rsubtil** [godotengine/godot-vscode-plugin#429]
### Godot version

N/A

### VS Code version

N/A

### Godot Tools VS Code extension version

N/A

### System information

N/A

### Issue description

(originally from https://github.com/github/linguist/discussions/6108)

Since Godot introduced "[Scene unique nodes](https://docs.godotengine.org/en/stable/tutorials/scripting/scene_unique_nodes.html)", the `%` operator is breaking syntax highlighting on GitHub:

Before:
```gdscript
var my_node = $/Node1/Node2/MyNode

func _ready() -> void:
    my_node.visible = false
```

After:
```gdscript
var my_node = $"%MyNode"

func _ready() -> void:
    my_node.visible = false
```

This is **not** related to Godot, VSCode, and this plugin (and from VSCode syntax highlighting is working without issue); it's for the grammar used for [linguist](https://github.com/github/linguist/)

### Steps to reproduce

- Submit GDScript code to a GitHub repository that uses scene unique nodes, and inspect it. ([example](https://github.com/retrohub-org/retrohub/blob/master/scenes/root/popups/age_rating/AgeRatingPicker.gd))

**Comment by Error-In-Code** [comment]
This also happens when you use a string literal with the `$`.
```gdscript
var my_string = "hello"
var my_node = $"Node1/Node2/My_Node"

func _ready() -> void:
    my_node.visible = false
```

**Comment by DaelonSuzuka** [comment]
![image](https://user-images.githubusercontent.com/18042232/207009017-451b67e7-f90e-40d9-92ec-6556a9ec2a5a.png)
![image](https://user-images.githubusercontent.com/18042232/207009057-d1f751c6-1ca2-4c02-a452-1e7169e459f9.png)

I don't see what's wrong with either of these examples. I don't love githubs color choices but it looks like the grammar is working correctly to me.

**Comment by rsubtil** [comment]
It seems it was fixed in the meantime! This is what used to look like:
![image](https://user-images.githubusercontent.com/6501975/207033864-cdea1572-35d2-46e2-8c84-eccb3948bebe.png)
