### ISSUE TITLE
Global Variables are not properly detected

### ISSUE THREAD

**Issue by lbrande** [godotengine/godot-vscode-plugin#431]
### Godot version

3.5.1.stable

### VS Code version

1.71.0

### Godot Tools VS Code extension version

1.3.1

### System information

Pop!_OS 22.04

### Issue description

Using Global variables set under Project Settings -> AutoLoad gives the following error "The identifier <identifier> isn't declared in the current scope."

Ctrl-clicking on the Global Variable or a function defined in it works correctly and takes you to its definition.

### Steps to reproduce

1. Create a new script file with a function in it
2. Go to Project Settings -> Autoload and add the script as a global variable
3. Open another script file in the same project
4. Add a line of code corresponding to `<name-of-global-variable>.<name-of-created-function>(<function-parameters)`

**Comment by Calinou** [comment]
Does it work after restarting the editor?

**Comment by lbrande** [comment]
Yes, it seems so now, thought I had already tried that but must have messed it up. I guess you can just ignore this issue then.

**Comment by nikitalita** [comment]
Also running into this on 3.5.1; restarting Godot than VS Code doesn't fix it, nor vice-versa.

While most globals don't get recognized at all, I did note that it seems to think that certain globals are actually similarly-named-members of another class: 
![image](https://user-images.githubusercontent.com/69168929/196302234-2f8f27bc-6f4d-4e4f-a632-c2f7a0667bfe.png)

![image](https://user-images.githubusercontent.com/69168929/196302276-b3e33864-79f9-476a-aa7e-105ebd729346.png)

**Comment by atirut-w** [comment]
This might be a problem with the LSP server in Godot itself then.

**Comment by DaelonSuzuka** [comment]
This is definitely an LSP problem.

> single letter names for autoloads

![mog1](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/ea43b4c0-b942-4d07-9077-f14aaca8d648)

Okay, it's an LSP problem *and* a code style problem.
