### ISSUE TITLE
Language server stuck "Initializing"

### ISSUE THREAD

**Issue by OsamaHeweitat** [godotengine/godot-vscode-plugin#435]
### Godot version

3.5.1

### VS Code version

1.73.0

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

Whenever VSCode is launched, regardless if through Godot or not, or whether it was launched before or after Godot, the language server status at the bottom right will be stuck as "Initializing", clicking on it will give the following popup text: "Connecting to the GDScript language server at 127.0.0.1:6007"

VSCode is actually not connecting to the language server and it isn't just a visual bug, as features such as auto-complete and debugging do not work. I tried every possible fix and nothing worked, I tried multiple versions of Godot and VSCode.

### Steps to reproduce

1. Launch VSCode.

**Comment by OsamaHeweitat** [comment]
The issue doesn't occur when using versions of the plugin below 1.3.0, such as 1.2.0. Using 1.3.0 and 1.3.1 causes the issue to arise again.

**Comment by Calinou** [comment]
cc @DaelonSuzuka

**Comment by OsamaHeweitat** [comment]
Can confirm the issue still occurs for me using the latest `master` branch.

**Comment by DaelonSuzuka** [comment]
Very interesting. I did a quick test and I can't replicate this on `1.3.0`, `1.3.1`, or `master` connecting to Godot `3.5` or `3.5.1` on Windows 10.

> popup text:  "Connecting to the GDScript language server at 127.0.0.1:6007"

@OsamaHeweitat This sticks out to me. The default language server port in Godot 3.x is `6008`, and in Godot 4 it's `6005`. Is `6007` a typo here, or have you intentionally modified your Godot editor settings to change the port to `6007`?

**Comment by OsamaHeweitat** [comment]
> Very interesting. I did a quick test and I can't replicate this on `1.3.0`, `1.3.1`, or `master` connecting to Godot `3.5` or `3.5.1` on Windows 10.
> 
> > popup text:  "Connecting to the GDScript language server at 127.0.0.1:6007"
> 
> @OsamaHeweitat This sticks out to me. The default language server port in Godot 3.x is `6008`, and in Godot 4 it's `6005`. Is `6007` a typo here, or have you intentionally modified your Godot editor settings to change the port to `6007`?

I changed the port at the time to 6007 in hopes of the it working. The issue occurs with both 6008 and 6007 as the port. I tried adjusting a multitude of settings and nothing worked.

**Comment by MagicPenguin301** [comment]
The same issue occurs on godot4.0 beta4.

**Comment by MagicPenguin301** [comment]
Have you ever checked your extension settings in your vscode to make sure that the editor path and port is correct? Because if you just moved from an older godot version and used the extension in the past, then the path will also be the older one, which will prevent it from connecting. I just encountered with this problem.

**Comment by OsamaHeweitat** [comment]
> Have you ever checked your extension settings in your vscode to make sure that the editor path and port is correct? Because if you just moved from an older godot version and used the extension in the past, then the path will also be the older one, which will prevent it from connecting. I just encountered with this problem.

I've always made sure the editor path is correct, sadly it still didn't work.

**Comment by DaelonSuzuka** [comment]
Sorry for the delay in addressing this, I've been sick for the last week or so.

> I had this issue when launching from godot, or when VSCode was closed/reopened after launching from godot. It looks like something, maybe [this line here in activation](https://github.com/godotengine/godot-vscode-plugin/blob/master/src/godot-tools.ts?rgh-link-date=2022-11-13T22%3A14%3A05Z#L67), is dependent on a workspace directory being set, but that doesn't happen when launching from godot into a new, workspace-less window. See full error below.

Thanks for the insight here. I think I only ever open VSCode with a folder-as-workspace, so I might never have tested this. I've wanted to clean up this initialization path for a while but obviously I didn't realize it had the potential to be this broken.
