### ISSUE TITLE
Functions with default argument value does not add tab then pressing enter

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#438]
### Godot version

N/A

### VS Code version

1.73.0

### Godot Tools VS Code extension version

1.3.1

### System information

N/A

### Issue description

Pressing enter after entering the following signature automatically adds a tab:

```gdscript
func _api(endpoint: String, params: Dictionary) -> APIResponse:
```

If you make any of the arguments a dict by default, a tab is no longer added:

```gdscript
# :(
func _api(endpoint: String, params := {}) -> APIResponse:
```

### Steps to reproduce

See above

**Comment by DaelonSuzuka** [comment]
These examples both produce a tab for me using `2.0.0`.
