### ISSUE TITLE
Auto-completion of signal names leaves extra set of quotes

### ISSUE THREAD

**Issue by threethan** [godotengine/godot-vscode-plugin#445]
### Godot version

3.5.1

### VS Code version

1.74.3

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

When auto-completing the the name of a signal, an extra set of double quotes will be added.

Example: `connect(""child_entered_tree"")` *Or, if auto-pairing is not enabled:* `connect(""child_entered_tree"`

This is obviously incorrect, and causes an error.
Note that auto-complete will not appear until a quote is typed after `connect(`, meaning the set of quotes added by autocomplete is always extraneous.

### Steps to reproduce

1. Create a script extending node
2. Type `connect("` or `emit_signal("`
3. Select any auto-completion

**Comment by atirut-w** [comment]
I think this big was already reported. Please search for existing issues before reporting one to make sure you don't create duplicates.

**Comment by threethan** [comment]
My bad, only checked open issues. Duplicate of https://github.com/godotengine/godot/issues/48436.
