### ISSUE TITLE
Stuck connecting to language server

### ISSUE THREAD

**Issue by DigitalChoco** [godotengine/godot-vscode-plugin#447]
### Godot version

3.5.1 stable

### VS Code version

1.74.3

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description
The extension get stuck initializing. It dosen't ever give an error that it couldn't connect either.
![image](https://user-images.githubusercontent.com/13681036/212521632-9293fd8f-aad4-45a1-a2af-8cc094526aa4.png)

### Steps to reproduce

-

**Comment by atirut-w** [comment]
That's.... not a lot of information to go by.

Does the extension complain about not being able to connect to Godot?

**Comment by DigitalChoco** [comment]
> That's.... not a lot of information to go by.
> 
> Does the extension complain about not being able to connect to Godot?

Where would I check that?

**Comment by atirut-w** [comment]
On the bottom right, there will be some text that says "Connecting (number of retries)" and if you click on it or wait long enough, this will pop up:
![image](https://user-images.githubusercontent.com/25323231/212520510-540b9032-7295-4a79-a247-e1790065ab0c.png)

**Comment by DigitalChoco** [comment]
I see now that it is stuck initializing, I can't connect to one of your servers:
![image](https://user-images.githubusercontent.com/13681036/212520577-e64a15ec-e1d7-4e19-ae45-bea169a95248.png)

**Comment by DigitalChoco** [comment]
I edited the thread to be about the connection issue now that I figured out that was the problem.

**Comment by atirut-w** [comment]
Do you have Godot open when trying to use the extension? It doesn't connect to other people's LSP server, it connect to *yours*(127.0.0.1 is localhost a.k.a. the computer it's on).

**Comment by DigitalChoco** [comment]
> Do you have Godot open when trying to use the extension? It doesn't connect to other people's LSP server, it connect to _yours_(127.0.0.1 is localhost a.k.a. the computer it's on).

Yes I have godot open, I tired changing the port in godot and the extension but to no avail.

**Comment by DigitalChoco** [comment]
> I am hitting this too. The extension gives no feedback on whats happening, just says `Initializing`. I open Godot first, set VS code as my editor and open a `.gd` file from inside the FileSystem pane in Godot. I checked `lsof -i tcp:6008` and can see the server is there.
> 
> Godot: v3.5.1 stable macOS Godot-tools: v1.3.1 VSCode: 1.74.3
> 
> This also happens on VSCodium 1.68.1, which is where I initially hit it. I switched to VSCode to verify.

I found this thread containing [this comment](https://github.com/godotengine/godot-vscode-plugin/issues/435#issuecomment-1346091101) which linked to [this version](https://github.com/godotengine/godot-vscode-plugin/suites/9808012901/artifacts/471983389) which works for me.
