### ISSUE TITLE
GDscript Debug Issue - Breakpoints Not working

### ISSUE THREAD

**Issue by DSPerson** [godotengine/godot-vscode-plugin#450]
### Godot version

3.5.1

### VS Code version

1.74.3

### Godot Tools VS Code extension version

1.3.1

### System information

MacOS M1 12.6

### Issue description

1. I can run Godot game not use breakpoint , but my game will stuck when I add a breakpoint at visual studio code.

### Steps to reproduce

<img width="904" alt="image" src="https://user-images.githubusercontent.com/17868782/216266666-a87931e4-bc69-455f-a8e9-b7eab10aa38c.png">

<img width="876" alt="image" src="https://user-images.githubusercontent.com/17868782/216266743-16ba3b38-d1a8-4b3e-b085-497146f45d25.png">
<img width="1902" alt="image" src="https://user-images.githubusercontent.com/17868782/216267073-98caa970-98f1-48f2-b265-2d38a89b2b4c.png">

**Comment by atirut-w** [comment]
Can you upload a screen recording of this happenning? How is it stuck? Does VSCode come up when the game got stuck?

**Comment by DSPerson** [comment]
> Can you upload a screen recording of this happenning? How is it stuck? Does VSCode come up when the game got stuck?

ok

**Comment by omansak** [comment]
@DSPerson i have this problem , How did u fix it ?
