### ISSUE TITLE
Can't Connect to GDScript Language Server

### ISSUE THREAD

**Issue by Luzzotica** [godotengine/godot-vscode-plugin#455]
### Godot version

4.0.rc6.mono

### VS Code version

1.75.1

### Godot Tools VS Code extension version

1.3.1

### System information

MacOS Monterey 12.2.1

### Issue description

VSCode is saying it cannot connect to the GDScript language server at 127.0.0.1:6008

My Godot editor is running. I've tested this multiple times.

I really want to be able to write my C# and GDScript code in VSCode: Having multiple windows is SUPER nice, and lets me work much faster.

I tried setting up the debugger, but when I opened my command palette the `Open launch.json` wouldn't pop up for me. I noticed that in the debugger is says it defaults to port 6007. Perhaps this is my issue?

Looking for a little bit of guidance. Sorry if this question feels mundane.

### Steps to reproduce

I am not sure.

**Comment by DaelonSuzuka** [comment]
In Godot 4, they changed the default LSP port from 6008 to 6005. I recommend going into your editor settings in Godot and changing the port back to 6008.

![image](https://user-images.githubusercontent.com/18042232/221943473-8cf3a715-ec03-4d0a-8736-84e63eba3b81.png)

**Comment by mikemklee** [comment]
I ran into the same issue on Godot 4.
I kept the Godot editor settings as-is, and instead modified the port in the extensions setting in VS Code.

![image](https://user-images.githubusercontent.com/17537040/222329913-50639d21-8b2b-46e2-adaa-c2005251031c.png)

**Comment by DaelonSuzuka** [comment]
> I ran into the same issue on Godot 4.
> I kept the Godot editor settings as-is, and instead modified the port in the extensions setting in VS Code, setting it to 6005.

Doing this doesn't help you if you still have to work on both Godot 3 and Godot 4 projects.

**Comment by mikemklee** [comment]
> Doing this doesn't help you if you still have to work on both Godot 3 and Godot 4 projects.

If that case, you can modify the extensions setting on the workspace level, instead of on the user level.
Assuming each Godot project is its own VSCode workspace.

**Comment by DaelonSuzuka** [comment]
Remembering to do that across dozens of projects is pointless compared to just changing the port setting in Godot.

**Comment by mikemklee** [comment]
haha fair

**Comment by Luzzotica** [comment]
Thank you for the conversation! That was awesome!

I'm going to close this conversation, as my question was 100% answered. Thank you!

**Comment by viabiko** [comment]
Is there a reason why the default port cannot be changed in the plugin? I couldn't find anything on this manner.
