### ISSUE TITLE
Start of path link misaligned when line is indented with tabs

### ISSUE THREAD

**Issue by WeaverSong** [godotengine/godot-vscode-plugin#464]
### Godot version

4.0.2

### VS Code version

1.77.3

### Godot Tools VS Code extension version

1.3.1

### System information

Debian/Gnome

### Issue description

When a line that includes a path to another file is indented with tabs, the start of the link also indents, becoming farther and farther from the actual start of the path.
![image](https://user-images.githubusercontent.com/55251533/231839406-696c4b70-7926-4308-81d4-057a843f526a.png)

### Steps to reproduce

Add a line that includes a path to another file, then indent it with tabs.

**Comment by DaelonSuzuka** [comment]
That's a fun one. Just out of curiosity, are you indenting with tabs or spaces?

**Comment by WeaverSong** [comment]
I use tabs normally, so that's what I've been using with Godot. I didn't test super thoroughly, but it looked like it didn't happen if I swapped the tabs to spaces; although then Godot was complaining about my mixing tabs and spaces, which might have affected the results.

**Comment by DaelonSuzuka** [comment]
Can you paste the text of the file in your screenshot? I can't seem to replicate this locally.

**Comment by WeaverSong** [comment]
Of course. The file is rather large, but this snippet is enough to cause it for me. There needs to be a file at the place specified, of course.
`var test = [
	load("res://scenes/biomes/borkfest/enemies/Ancient Hot Fork.tscn")
]`

**Comment by WeaverSong** [comment]
Of course, then github removed the newlines. The load has to be indented, so it only happens if the array is separated out unto multiple lines.
