### ISSUE TITLE
Cannot launch game from VSCode in Mac

### ISSUE THREAD

**Issue by svprdga** [godotengine/godot-vscode-plugin#478]
### Godot version

v4.0.3.stable.official

### VS Code version

1.77.1 (Universal)

### Godot Tools VS Code extension version

1.3.1

### System information

Mac Mini M2 Pro

### Issue description

I can't launch the game from VSCode's Command Palette

### Steps to reproduce

1. Create a Godot game in Mac and configure it to work with VSCode via this extension.
2. If I select the option from the Command Palette "Godot Tools: Run Workspace as Godot project" then a dialog appears in which I guess that I have to select the executable. I select the Godot application and then an error appears: "Invalid editor path to run the project".

I have the following configuration in my launch.json:

"editor_path": "/Applications/Godot.app/Contents/MacOS/Godot"

**Comment by microBob** [comment]
Does it work if you put your editor path into the settings file instead of the launch file? I have this in my `settings.json` instead of `launch.json`
```json
"godot_tools.editor_path": "/Applications/Godot.app/Contents/MacOS/Godot",
```

**Comment by svprdga** [comment]
> Does it work if you put your editor path into the settings file instead of the launch file? I have this in my `settings.json` instead of `launch.json`
> 
> ```json
> "godot_tools.editor_path": "/Applications/Godot.app/Contents/MacOS/Godot",
> ```

Tried and works, thanks.
