### ISSUE TITLE
Documentation unclear. Can't find "Enable Smart Resolve"

### ISSUE THREAD

**Issue by jeancallisti** [godotengine/godot-vscode-plugin#482]
### Godot version

3.4.x or higher

### VS Code version

1.79.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

The readme of the "godot-tools" plugin contains this section : 

```
Why isn't IntelliSense displaying script members?

    GDScript is a dynamically typed script language. The language server can't infer all variable types.
    To increase the number of results displayed, open the Editor Settings, go to the Language Server section then check Enable Smart Resolve.
```

I did not find anything called "Enable smart resolve", neither in VSCode nor in Godot 3.x.
The closest I got was in Godot : 
`Editor > Editor Settings... > Network > Language server.`
**But it does not contain "Enable Smart Resolve"**

Google does not return **any** result mentioning "Enable smart resolve" other than this plugin's readme, except on a **single** page : https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_changelog_authors.txt

What's this about?

### Steps to reproduce

-

**Comment by Calinou** [comment]
Only 2 pull requests in Godot mention smart resolve:

- https://github.com/godotengine/godot/pull/29780
- https://github.com/godotengine/godot/pull/34920

This is likely a feature that was dropped at some point, so the README should be updated to mention that paragraph.

**Comment by DaelonSuzuka** [comment]
Godot 3.5.2stable looks like this for me:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/ef177720-ced8-4f69-999d-66079c2679f2)

**Comment by Calinou** [comment]
Indeed, I can see it in `master` too: https://github.com/godotengine/godot/blob/ea6a141ffffa6de8a27e2093145ececaaa9aa2f6/modules/gdscript/language_server/gdscript_language_server.cpp#L42
