### ISSUE TITLE
Language server tooltips not appearing on VS Code

### ISSUE THREAD

**Issue by aegroto** [godotengine/godot-vscode-plugin#485]
### Godot version

4.1.1 (Tested on 4.0.3 as well)

### VS Code version

1.80.2

### Godot Tools VS Code extension version

1.3.1

### System information

Kubuntu 20.04.6 LTS (Focal Fossa)

### Issue description

No tooltips appear on VS Code although running the project works. I have no other extensions.

VS Code is able to connect to the language server:
![immagine](https://github.com/godotengine/godot-vscode-plugin/assets/11978802/8ce8f5f2-bbc3-4268-be6e-f0d14d580e4a)

No tooltip is appearing on VS Code:
![immagine](https://github.com/godotengine/godot-vscode-plugin/assets/11978802/9d1b27bc-5f12-4c4a-8f56-dbea0bdb1238)

But suggestions seem to work on the Godot Editor:
![immagine](https://github.com/godotengine/godot-vscode-plugin/assets/11978802/fe658e81-ac69-4b91-b757-d9164f47e3c7)

### Steps to reproduce

I have uploaded the dummy project I have used to take the screenshots: https://github.com/aegroto/godot-issue-dummy.
You can reproduce the issue by opening it on VS Code with a workspace with no other installed extensions apart from godot-tools.

**Comment by Chtau** [comment]
The Tooltip hint can be enabled/disabled for autocomplete in VSCode.
When the autocomplete is open press [CTRL] + [SPACE] to show/hide the Tooltip.

There is actual also a problem that the autocomplete hint is empty after the "." which is fixed in https://github.com/godotengine/godot/pull/82948

**Comment by DaelonSuzuka** [comment]
@aegroto I haven't been able to replicate this. Are you still experiencing it using the latest stable version of Godot and the new `2.0.0` version of godot-tools?

**Comment by aegroto** [comment]
Hello @DaelonSuzuka I didn't have a chance to try out the last version, but I will do it soon and update the issue accordingly, thanks for your interest.

**Comment by aegroto** [comment]
I confirm that as of today, with Godot 4.2.1, the tooltips are back in the editor, therefore I close this issue.
