### ISSUE TITLE
BBC not rendering

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot-vscode-plugin#486]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### VS Code version

1.81.1

### Godot Tools VS Code extension version

1.3.1

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.14037.17019) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When adding bbc to the comment documentation, it doesn't render the bbc.

### Steps to reproduce

```gdscript
## [code]
##    @export var unit: PackedScene
## [/code]
func _example():
    pass
```

![image](https://github.com/godotengine/godot-vscode-plugin/assets/1571806/63910ddd-3d83-4742-9eb4-6701490ba2a9)

**Comment by Calinou** [comment]
You should use `[codeblock]` for multiline codeblocks if I'm not mistaken.

**Comment by TheColorRed** [comment]
Ahh yes that is correct. I did notice though that `[br]` doesn't seem to work unless I am doing that one wrong too.

```gdscript
## Some text
## [br][br]
## Some more text
```

![image](https://github.com/godotengine/godot-vscode-plugin/assets/1571806/c3696e9c-06fb-46d5-b5e8-b5eee269f65d)

**Comment by DaelonSuzuka** [comment]
This is an issue with the Language Server in the editor, not this extension. The language server sends fully rendered markdown for the hover popups, so if there's an issue with the formatting, we can't really do anything about that.
