### ISSUE TITLE
"Variable is never used" on constant that is used in another file

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-vscode-plugin#49]
In 0.3.4, Godot 2.1:

All constants in this script of my project are indicated as unused:

![image](https://user-images.githubusercontent.com/1311555/34802168-64b99848-f66c-11e7-97e2-8f8b1f594b1e.png)

However, they are:

![image](https://user-images.githubusercontent.com/1311555/34802210-a1dd6b50-f66c-11e7-9e9e-005da0ec9d0d.png)
...
![image](https://user-images.githubusercontent.com/1311555/34802197-929eaa82-f66c-11e7-80d9-ba8516dbd76c.png)

I get no accurate completion from `Group.*` either.
They should be resolvable since it's all consts. Maybe it's a more general intellisense problem regarding consts?

The same happens with member vars, but they are not consts so I guess it's harder to verify:

![image](https://user-images.githubusercontent.com/1311555/34802402-c37e4c60-f66d-11e7-8164-56b180718b03.png)
How could you guess?^^
![image](https://user-images.githubusercontent.com/1311555/34802409-ccea3cbe-f66d-11e7-908a-4e464343ca42.png)

In that case it would be nice to not squiggle those since it's not reliable, unless they are prefixed by `_` though, as an option?

**Comment by Geequlim** [comment]
It is hard to implement such checking with multi script files as GDScript is dynamic typed language.
In another hand to do checking in multi script files may slow down the performance.

**Comment by Zylann** [comment]
@Geequlim consts can be checked (so the dynamicness is out of question), Godot does it already. On the other hand, you already check member vars, which contradicts what you says about dynamicness since it's not reliable^^ I believe multi-file checking is possible since other editors can do it when possible to do without hurting performance (again, Godot does at least for consts), although it can be quite some work.

**Comment by Geequlim** [comment]
Now the unused symbol checking can be disabled with project setting in `.vscode/settings.json`
```json
	"GodotTools.lint": {
		"unusedSymbols": false
	}
```

**Comment by boyerjohn** [comment]
@Geequlim Whether it's hard to implement or not is entirely irrelevant. If the extension tells you something is never used when it is, that is a blatant bug. If it can't be implemented properly, it should be removed.

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Calinou** [comment]
This was resolved a while ago, closing.
