### ISSUE TITLE
No autocomplete for eg. bool values

### ISSUE THREAD

**Issue by gro-david** [godotengine/godot-vscode-plugin#493]
### Godot version

4.0.stable.arch_linux

### VS Code version

1.80.1 74f6148eb9ea00507ec113ec51c489d6ffb4b771 x64

### Godot Tools VS Code extension version

Custom build, tested on official v1.3.1

### System information

Arch Linux btw

### Issue description

I noticed that there is no autocomplete for bool values.

### Steps to reproduce

None

**Comment by DaelonSuzuka** [comment]
Yes there is:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/624433c6-2020-4c5b-bea7-0a86cf9c1fc1)

**Comment by atirut-w** [comment]
`abc` icon means it's guessed from the contents of opened files by VSCode itself, not from the extension.

**Comment by DaelonSuzuka** [comment]
Yeah, in that case:
