### ISSUE TITLE
Allow turning off the insertion of the opening bracket on function autocompletion

### ISSUE THREAD

**Issue by VaustXIII** [godotengine/godot-vscode-plugin#494]
### Godot version

v3.5.stable.official [991bb6ac7]

### VS Code version

1.82.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Problem statement

Pressing "Tab" when autocompleting a function name automatically inserts an opening bracket "(".
Usually this behavior is configurable for extensions so that no bracket is inserted, but there's no such setting for godot-tools

### Proposed solution

autocompleteAddParentheses extension setting that is either `true` or `false`. When `false` do not add an opening bracket on autocompletion

**Comment by DaelonSuzuka** [comment]
There's no setting because the extension doesn't control the completions. They come from the language server that's running in your editor. This is a long time known bug with the language server, and we can't fix it here.

**Comment by VaustXIII** [comment]
Got it, thanks for clarification
