### ISSUE TITLE
Signal connect routine not showing up under VSCode

### ISSUE THREAD

**Issue by rickygai** [godotengine/godot-vscode-plugin#495]
### Godot version

4.1.1

### VS Code version

1.82.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

1. Connect a signal of RigidBody3D > body_entered(body: Node) 
2. No signal connect routine created assigned .cs script (of Rigibody3D) under VSCode when loaded the .cs script file.

However, if I disable the external editor, the signal connect routine shown up under Godot C# IDE but placed out of the scope of the class.

Please advise.

![Godot v4 1 1 - Signal routine generating problem](https://github.com/godotengine/godot-vscode-plugin/assets/15626855/21e4d172-5c58-4206-9fcc-85fa8ef9edf5)

### Steps to reproduce

1. At Editor Settings > Text Editor > External > select "Use External Editor" to ON.
2. Set Dotnet > Editor > External Editor > to "visual studio code"
3. Create a RigidBody3D node > assign an empty script, name it as "Sphere.cs".
4.  Click on Scene > "Sphere".
5. At Node panel > Double click on "body_entered(body: Node)
6. At the "Connect a Signal to a Method" dialog, click the "Connect" button.
7. VSCode spawned up.
8. But the signal connect routine "_on_body_entered" is not creating under the assigned Sphere.cs script.
9. Done.

![Godot v4 1 1 - Signal routine generating problem](https://github.com/godotengine/godot-vscode-plugin/assets/15626855/53fc7fd2-4f15-46a5-be7a-444d9d3fe2ab)

![Godot v4 1 1 - Signal routine generating problem 2](https://github.com/godotengine/godot-vscode-plugin/assets/15626855/b5d17774-5c5d-4848-bc16-8f3c2b403ac2)

**Comment by DaelonSuzuka** [comment]
This issue is not related to this extension; it's a problem somewhere in the Godot Engine and you should file a bug there.

This extension really does not attempt to support C#/dotnet in any capacity, and I don't know how any other those systems work inside the Engine/Editor either.

Personally, I consider using the "Connect a Signal to a Method" dialog to be an unhelpful anti-pattern and I always advise against its use.
