### ISSUE TITLE
.gdshader syntax highlight doesn't work

### ISSUE THREAD

**Issue by Rawalanche** [godotengine/godot-vscode-plugin#496]
### Godot version

4.1.1 stable

### VS Code version

1.82.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

I have downloaded godot-tools extension via the VSCode marketplace. I went step by step through the entire official instructions:
"Settings
Godot
If you like this extension, you can set VS Code as your default script editor for Godot by following these steps:

Open the Editor Settings
Select Text Editor > External
Make sure the Use External Editor box is checked
Fill Exec Path with the path to your VS Code executable
On macOS, this executable is typically located at: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Fill Exec Flags with {project} --goto {file}:{line}:{col}
VS Code
You can use the following settings to configure Godot Tools:

editor_path - The absolute path to the Godot editor executable. Under Mac OS, this is the executable inside of Godot.app.
gdscript_lsp_server_port - The WebSocket server port of the GDScript language server.
check_status - Check the GDScript language server connection status."

![image](https://github.com/godotengine/godot-vscode-plugin/assets/38806207/7dcb5749-4d4a-41a8-bd4c-1ddc55f84e92)

Everything is in order and works for .gdfiles, such as autocomplete, syntax higlight, etc..., and the Language server is correctly detected and reports as Connected:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/38806207/f1026182-7d23-4d4f-97d6-764b13f6564c)

the .gdshader files on the other hand have absolutely no syntax highlight whatsoever, despite the language server also being correctly detected as gdshader and language server reporting as connected:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/38806207/4037f771-5cb8-4e7b-960a-805a0665f201)

I use latest stable Godot version, latest stable VSCode version and latest version of the VSCode extension from the marketplace. I followed the setup process carefully and to the letter.

### Steps to reproduce

1. With latest Godot Stable version, latest VSCode stable version and latest godot-tools extension, open any .gdshader file.
Result: The syntax highlight doesn't work
Expected: The syntax highlight works

**Comment by DaelonSuzuka** [comment]
Can you share the actual text of TestMap.gdshader?

**Comment by Rawalanche** [comment]
> Can you share the actual text of `TestMap.gdshader`?

Sure:
[TestMap.zip](https://github.com/godotengine/godot-vscode-plugin/files/12707293/TestMap.zip)

If you won't be able to repro it, I can share the whole project if needed. It's just a small test project.

**Comment by DaelonSuzuka** [comment]
It works for me on extension v1.3.1 and VSCode 1.82.2:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/4e5243bd-72e9-4474-a57f-240cb0798f8b)

The #include statement is clearly being handled wrong, but everything else works.

If you don't mind uploading the whole project, I'll take a look at that, although it isn't supposed to matter: the syntax highlighting system is dumb and only looks at the file it's highlighting.

I think there's another VSCode extension on the marketplace that adds highlighting for these file types, is it possible you have that installed too?

**Comment by Rawalanche** [comment]
![image](https://github.com/godotengine/godot-vscode-plugin/assets/38806207/023bc792-a542-4b1d-be87-ba7cfe74ab02)
I don't think any of these extensions could possibly interfere.

Here's the link to the project:
https://drive.google.com/file/d/1UQOlaG4atMe4aj5WSk4S1Uc0FViMN4rY/view?usp=sharing

**Comment by DaelonSuzuka** [comment]
There's an almost zero percent chance it's project related because of how the extension works, but something is definitely wrong in your screenshots so I figured it's worth checking anyways.

**Comment by Rawalanche** [comment]
> There's an almost zero percent chance it's project related because of how the extension works, but something is definitely wrong in your screenshots so I figured it's worth checking anyways.

Is there possibly anything that could restrict the function of the syntax highlight to the folder you've put the file into? Such as syntaxes/examples?

Other than that, only other thing I can imagine being a factor are VSCode user settings. I am attaching my vscode user settings.json
[settings.zip](https://github.com/godotengine/godot-vscode-plugin/files/12708150/settings.zip)

**Comment by atirut-w** [comment]
I'm guessing it's one of the extensions that you installed. I think there's a way to test for faulty extensions, but I don't remember how.

**Comment by Rawalanche** [comment]
> I'm guessing it's one of the extensions that you installed. I think there's a way to test for faulty extensions, but I don't remember how.

I've disabled all the extensions except godot-tools. Still no change:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/38806207/c9df2ee0-1e49-4908-9267-ab595b299352)

**Comment by atirut-w** [comment]
I decided to actually test this myself and turns out, it *is* a problem with this extension.
![image](https://github.com/godotengine/godot-vscode-plugin/assets/25323231/251b69a2-9038-440b-b66d-b3a46f1ff1f5)

**Comment by DaelonSuzuka** [comment]
There are no settings that effect the syntax highlighting, and it literally only looks at one file at a time.

> Worth to mention that I am on Win 11, not Linux or Mac.

This already really, really shouldn't matter.

**Comment by zaha** [comment]
Same issue happens to me, `shader_type` is the only thing getting syntax highlighted:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/1721211/58cf67eb-5e69-4645-a6be-f756cb7d1ff1)

godot-tools 1.3.1
VS Code 1.83.1

**Comment by DaelonSuzuka** [comment]
@zaha Can you post the code from your example as text?

**Comment by atirut-w** [comment]
For the impatient:

```glsl
shader_type canvas_item;

uniform vec3 highlight_color: source_color = vec3(1);
uniform float progress: hint_range(0.0, 1.0, 0.1) = 0;

void fragment() {
	float current_a = texture(TEXTURE, UV).a;
	vec4 target_color = mix(texture(TEXTURE, UV), vec4(highlight_color, current_a), progress);
	COLOR = target_color;
}
```

This is how it looks in VSCode 1.83.1 with Godot Tools 1.3.1:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/25323231/1b192db4-f55c-41ff-ada2-232c017fa3d3)

**Comment by Rawalanche** [comment]
I am starting to suspect that there's actually something unique about the extension developer's setup/development environment that makes it work rather than something unique about some peoples' setups/environment that breaks it.

Was this actually ever tested on any machine/setup other than the workstation of the developer who made it?

**Comment by zaha** [comment]
Thanks @atirut-w! Didn't get to my PC earlier.

@Rawalanche Ah yes, the classic "works on my machine"-pitfall, we've all been there. It does indeed start to smell like this.

**Comment by DaelonSuzuka** [comment]
@atirut-w Thanks for typing that up.

@atirut-w and @zaha What OS are you each using?

@zaha Unfortunately, I can't replicate your example either. Here's what I see in VSCode `1.83.1`, on Kubuntu this time, with extension v`1.3.1` on the left and the upcoming v`1.4.0` on the right :

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/cdb9e0d0-98fa-49fb-a8ea-2e0166c2d4e0)

**Comment by atirut-w** [comment]
Can you try with a fresh setup of VSCode or in a Windows VM?

**Comment by DaelonSuzuka** [comment]
Can you please answer the question I asked you directly? What OS are you using?

**Comment by atirut-w** [comment]
It's Windows 11, same as everyone else.

**Comment by DaelonSuzuka** [comment]
> Windows 11

Thank you. 

> same as everyone else.

You can't say "same as everyone else" when only one other person has listed their operating system.

**Comment by chrisl8** [comment]
As a bystander I thought I'd test this to see what I see, in case it could help.

The `.gdshader` **does not** work for me with the published online 1.3.1 version of the extension that is available in the VSCode extensions marketplace sidebar:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6188278/e53c09f4-91e4-4592-a9e0-a0d06e4be655)

**System information**
Godot v4.2.beta2 - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.4584) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

It **does** work if I pull the extension from the GIthub repo and build it by hand:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6188278/78f45d59-464c-446e-809f-d8a9c74d96a9)

_It appears to me that this has been fixed in a version of the extension that has not been released yet._

**Comment by DaelonSuzuka** [comment]
Thanks for the report, @chrisl8. At this point it seems likely this only happens on Win11, but I cannot imagine what's different between 10 and 11 that would cause this. 

> It appears to me that this has been fixed in a version of the extension that has not been released yet.

Yes, the gdshader grammar was rewritten from scratch after `1.3.1` was published. The conclusion to this thread was always going to be "wait for `1.4.0`", but I foolishly wanted to figure out what was actually _causing_ the problem.

**Comment by zaha** [comment]
> @atirut-w and @zaha What OS are you each using?

I'm using Windows 11 Pro 22H2. I can also test it on my Win 10 machine these days if it's working there.

**Comment by zaha** [comment]
Finally got the chance to get to my Win 10 desktop PC. I've opened the same gdshader file in VSCode (with synced settings) and I'm getting the same issue here.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/1721211/9e47f685-0b6a-48bd-940c-af9d992b6c68)

```
Edition	    Windows 10 Pro
Version	    22H2
OS build    19045.3570
Experience  Windows Feature Experience Pack 1000.19052.1000.0
````

**Comment by dxu** [comment]
I want to add another data point here - I'm seeing the same issue, except I'm running it on an M1 Mac (Ventura). 

godot-tools version 1.3.1, and vscode 1.84.2

**Comment by Rawalanche** [comment]
Quarter of a year later after being reported, and it's still not working.

**Comment by micheal-w-wells** [comment]
Works for me:
4.3 godot (built from source)
v2 godot-vscode-plugin
VSCode version: 1.88.1 
M1  Sonoma 14.2.1

**Comment by DaelonSuzuka** [comment]
Anybody experiencing a similar problem with extension v2.0.0 or greater is welcome to open a new issue, but I'm considering this one resolved because the gdshader textmate grammar was completely rewritten between `1.3.1` and `2.0.0`.
