### ISSUE TITLE
Custom C# signal names are shown as compiler errors in Godot 4

### ISSUE THREAD

**Issue by fleetfoxx** [godotengine/godot-vscode-plugin#498]
### Godot version

4.1.1.stable.mono

### VS Code version

1.82.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

When using the custom signal syntax for C# described [in the docs](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_signals.html#custom-signals-as-c-events), the signal name is marked as a compiler error CS0117 "'Node.SignalName' does not contain a definition for 'MyCustomSignal'" despite compiling successfully in the editor.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/98632874/d964863b-e2d5-4ec4-bda8-4caa27ac8678)

### Steps to reproduce

1. Create a C# script containing a custom signal.
2. Observe the compiler error.

```cs
using Godot;

public partial class GlobalSignals : Node
{
  [Signal] public delegate void SetCameraTargetEventHandler(Node3D target);

  public void EmitSetCameraTargetSignal(Node3D target)
  {
    EmitSignal(SignalName.SetCameraTarget, target);
  }
}
```

**Comment by atirut-w** [comment]
This extension only deal with GDScripts. The errors are coming from the C# extension, I'm afraid. I remember there's an option in the tools menu to fix this, but I forgot how to do it.

**Comment by fleetfoxx** [comment]
Indeed it does. I had issues with syntax highlighting in Godot 3 that seemed to be resolved after I installed this extension. However, I can confirm syntax highlighting is still present after disabling this extension while using Godot 4. My mistake for attributing this issue to `godot-tools`. Thank you for the help, I'll look around for the option you mentioned.
