### ISSUE TITLE
Distinguish local variable and member variable

### ISSUE THREAD

**Issue by eterlan** [godotengine/godot-vscode-plugin#499]
### Godot version

4.1

### VS Code version

1.82.2

### Godot Tools VS Code extension version

1.3.1

### System information

win10

### Problem statement

The textmate scopes for both local variable and member variable is both undifined, the color theme cannot color them correctly.
![image](https://github.com/godotengine/godot-vscode-plugin/assets/37736673/4d23c7f3-9710-40dd-acfb-19d77c276002)

The problem is user cannot tell whether a variable is local in function without lookup where is symbol defined, it's hard to maintain and error-prone.

### Proposed solution

define both of them in textmate definition file.

**Comment by DaelonSuzuka** [comment]
It's not possible to tell the difference between a local variable and a member variable using only a TextMate grammar.

**Comment by eterlan** [comment]
> It's not possible to tell the difference between a local variable and a member variable using only a TextMate grammar.

I notice C# plguin can find out all the local variable, so I think it's doable.
I kind of find out how to search where the local variable declaration
![image](https://github.com/godotengine/godot-vscode-plugin/assets/37736673/45b82567-20db-4e61-ba0d-cf9c13b9d239)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/37736673/faa3ca75-e84f-4e91-9e5a-ddfd95cb3d50)

But I don't know how to use it to seach their usage places inside function after trying whole day. Do you have any idea?

**Comment by DaelonSuzuka** [comment]
> I notice C# plguin can find out all the local variable, so I think it's doable.

What other extensions can do for other programming languages is not relevant to what _this_ extension can do for _this_ programming language.

> I kind of find out how to search where the local variable declaration

Here's one example of why this doesn't work:

```gdscript
class InnerClass:
	var inner_class_member_variable = 1
```

> But I don't know how to use it to seach their usage places inside function after trying whole day. Do you have any idea?

This is not possible using TextMate grammars.
