### ISSUE TITLE
Debug Editor Toolscripts

### ISSUE THREAD

**Issue by SavoVuksan** [godotengine/godot-vscode-plugin#500]
### Godot version

4.1

### VS Code version

1.83.0

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

Is it possible to debug Editor Toolscripts? I am currently working on a 3D Gizmo Plugin and want to debug it using VS Code and the VS-Code Godot Integration. But I don't seem to find any resources on how to debug Plugin Scripts.

### Steps to reproduce

Create a Toolscript 
Try debugging it.

**Comment by atirut-w** [comment]
You can't even debug tool scripts using the built-in editor, IIRC.

**Comment by Calinou** [comment]
Debugging tool scripts running in the editor isn't supported. You need to use `print()` statements instead.

**Comment by SavoVuksan** [comment]
ahh ok thanks for the info ^^
