### ISSUE TITLE
Debugger and installation instructions don't appear to work for 4.2

### ISSUE THREAD

**Issue by mikest** [godotengine/godot-vscode-plugin#520]
### Godot version

Godot v4.2.beta1 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### VS Code version

1.64.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

1. The instructions for configuring the launch.json should add that the address to the server should include a protocol, for example `tcp://127.0.0.1`. Without it godot will fail to launch with an error complaining about the protocol in the `--remote-debug` flag.

2. After configuring the launch script the launched instance of the game just hangs at the splash screen if I have a breakpoint set.
3. If I remove the breakpoint, the game launches, but I am unable to set a breakpoint.

### Steps to reproduce

1. configure the launch.json
2. set a breakpoint
3. launch the game

results:
1. never gets past the splash screen

workaround:
1. remove breakpoint and relaunch game

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-vscode-plugin/issues/389.
