### ISSUE TITLE
Godot VSCode plugin throws nonexistent errors on top of file

### ISSUE THREAD

**Issue by Excalizan** [godotengine/godot-vscode-plugin#522]
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### VS Code version

1.84.0

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

Godot VSCode extension is not behaving like I'd expect it to. It keeps throwing errors that read "Error (test)" on top of the file (@ line1:col1, the extends NODETYPE part) but my code works just fine when I run the project. It's also inconsistent since it doesn't throw the same error on my Player.gd file. I do not understand what is happening and I don't think it's related to my code, since this happens in every project I have in my folders, including premade games, etc. I have dropped images of the errors below. If you need any other resources such as screenshots or code I can drop them too.

Mainscene.gd:
![error1](https://github.com/godotengine/godot-vscode-plugin/assets/77782958/4d3aa5fc-4f61-4ef5-a442-01becf804685)

Boulder.gd:
![error2](https://github.com/godotengine/godot-vscode-plugin/assets/77782958/a7d2ae9c-402c-400c-915f-7e1aa6e2a303)

Player.gd:
![noerror](https://github.com/godotengine/godot-vscode-plugin/assets/77782958/f70a12ff-4ccb-4c02-a738-d538b0f0a2d1)

I should also note that I am having the same issue on Godot v4.1.2.stable.mono.official [399c9dc39] too.

### Steps to reproduce

Just create a new project in Godot v4.1.2.stable.mono.official [399c9dc39] and make a basic 2D project that involves RigidBody2D's and CharacterBody2D's. I suppose you will see the same effect.

**Comment by DaelonSuzuka** [comment]
This is a problem with the language server, which is a part of the Godot engine. This extension does not generate any of these errors, it just displays the information the engine gives it. 

Unfortunately, there isn't really anything I can do about this.

**Comment by Excalizan** [comment]
Alright, so what do I do now? Do I need to post this on the man repo?

**Comment by DaelonSuzuka** [comment]
Nothing, really. This issue has been known for years and has been reported everywhere many times.

**Comment by Excalizan** [comment]
Well, I kinda fixed it I guess, let me tell.
There was a warning in the script saying the delta parameter in _physics_process was never used and advised me to prefix it with an underscore like _delta. No big deal, right? And I put the underscore in there to make the warning go away, and it just worked. I achieved the same effect by using the delta variable basically anywhere, it doesn't matter.

**Comment by DaelonSuzuka** [comment]
I hope that keeps working for you.
