### ISSUE TITLE
Add 'await' keyword syntax highlighting for Godot 4 versions

### ISSUE THREAD

**Issue by shaugnmarc** [godotengine/godot-vscode-plugin#523]
### Godot version

4.1.2 RC

### VS Code version

1.84.0

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Problem statement

![image](https://github.com/godotengine/godot-vscode-plugin/assets/109469348/34d7cf28-a095-4bb2-aa3e-c4893721a4e5)

Since 'yield' has been kinda replaced in Godot 4.0, it would be nice for the extension to acknowledge 'await' as a keyword for consistent highlighting with everything else for the newest Godot versions.

### Proposed solution

Add 'await' to the keyword category of syntax highlights.

**Comment by DaelonSuzuka** [comment]
![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/0b09cc84-3946-45c6-b26f-0e5ba41d743d)

it's been implemented for like a year. The next release is probably going to be this month.
