### ISSUE TITLE
Wrong syntax highlighting when using ```%``` in a function call until EOF

### ISSUE THREAD

**Issue by MartinVacheron** [godotengine/godot-vscode-plugin#525]
### Godot version

v4.1.stable.official [970459615]

### VS Code version

1.84.2

### Godot Tools VS Code extension version

Development build

### System information

Windows 11

### Issue description

When using the unique name symbol ```%``` in a function call, it breaks the coloring for the rest of the file.

In the following example, from ```fcn8()``` to EOF, the colors are no longer the good ones. I get the same result outside an ```if``` statement.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/99418006/4cefdef3-8f2a-4643-818d-c6d3e3434992)

### Steps to reproduce

Open the file in the zip (or write down the same text as in example image) in VSCode.

[ColoringBug.zip](https://github.com/godotengine/godot-vscode-plugin/files/13322145/ColoringBug.zip)

**Comment by DaelonSuzuka** [comment]
This has been fixed in `master` for a while, and I guess I forgot to update this issue.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/8bfcca9e-a954-4590-8d02-fded8768744a)

**Comment by DaelonSuzuka** [comment]
Closing since `2.0.0` has been released.
