### ISSUE TITLE
Add full C# support

### ISSUE THREAD

**Issue by joined72** [godotengine/godot-vscode-plugin#531]
### Godot version

4.2.rc.1 (ad72de508)

### VS Code version

1.64.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Problem statement

Current the Godot 4.x C# developers cannot use the official C# VsCode extension because it works ONLY on Godot 3.x and isn't updated from more that one year (August'22). 

### Proposed solution

Add full C# support (the same support currently exists for GdScript) and maintain both full aligned!

**Comment by DaelonSuzuka** [comment]
Don't be greedy.

**Comment by joined72** [comment]
> Don't be greedy.

But you will add more C# support? ;)

**Comment by atirut-w** [comment]
Very unlikely. The C# extension is maintained by different people, I think.

**Comment by DaelonSuzuka** [comment]
> Very unlikely. The C# extension is maintained by different people, I think.

Please stop coming into conversations you aren't involved in and answering questions you weren't asked with made-up information that you don't have any source for.

> But you will add more C# support? ;)

Don't expect me to fully replicate the other plugin, but I will definitely be looking for more easy wins to help C# users.
