### ISSUE TITLE
Built in Markdown not rendered

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#533]
### Godot version

v4.1.3.stable.arch_linux

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/2d523105-4e30-44d1-bd5f-fa5bb551334c)

### Steps to reproduce

hover over anything that's defined in your code somewhere

**Comment by LeoDog896** [comment]
This was finished in https://github.com/godotengine/godot-vscode-plugin/commit/6c4fca265ab6ca21dc6470869ab67f14a60e8824

**Comment by DaelonSuzuka** [comment]
@moritz-t-w Are you still experiencing this issue in `2.0.0`?

**Comment by moritz-t-w** [comment]
It works now.
