### ISSUE TITLE
Hovering over any non-symbol shows all enums

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#535]
### Godot version

v4.1.3.stable.arch_linux

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/a8fa47f0-bd9a-4d43-b0b5-e6ab03587452)
Hovering over anything that doesn't have a definition somewhere just shows all enums, which is really annoying. In the screenshot I am hovering just to the right of a function name.

### Steps to reproduce

hover around a bit until you find this. For example:
1. declare a function
2. Hover over the opening bracket

**Comment by DaelonSuzuka** [comment]
Hovers are provided by the Language Server, which is part of the Godot engine itself. As such, this is a bug in the engine and there's nothing I can do about it.

That said, I'm using Godot 4.2beta3, and I can't reproduce this. It's possible they've already improved this behavior in the LS.
