### ISSUE TITLE
Wrong auto-indentation

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#536]
### Godot version

v4.1.3.stable.arch_linux

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

I'll just make a checklist:
> `↵` = hitting enter here
 `|e` = expected cursor position
`|a` = actual cursor position
- [ ] Newline after getter or setter signature
```gdscript
var foo: int:
	get:↵
	|a	|e
```
- [ ] Newline after variable declaration ending in `:` auto-indented too much
```gdscript
var foo: int:
	|e	|a
```
> I have not been able to reproduce this but it's happened a bunch of times and I will update this when it happens again
- [ ] Newline after variable declaration ending in `:` not auto-indented
```gdscript
var foo: int:↵
|a	|e
```
- [ ] Newline after lambda function
```gdscript
var x = func():↵
|a	|e
```
- [ ] Nested blocks auto-indent to inner most block
```gdscript
# expected result of typing else on the last line without indenting manually
if true:
	if true:
		if true:
else
# actual result:
if true:
	if true:
		if true:
		else
```

### Steps to reproduce

as described.

**Comment by DaelonSuzuka** [comment]
Already fixed in `master`.
