### ISSUE TITLE
var foo:int: not highlighted

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#537]
### Godot version

v4.1.3.stable.arch_linux

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

```
var foo:int: # int should be green
	get:
		return 0
var bar: int:
	get:
		return 0
```
![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/f65e123c-f9da-4c36-bf09-7e40e6f445fd)

### Steps to reproduce

1. type `var foo:int:`

**Comment by DaelonSuzuka** [comment]
It's because the new getter/setter syntax in Godot 4 is confusing the parser. `get` should also be yellow like a function name.

This has already been fixed in `master`:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/4664c583-38a2-42aa-958e-8ced1f5fae64)
