### ISSUE TITLE
Debugger instance not stopped after permission denied

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#539]
### Godot version

n/a

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

If you get a permission denied error when trying to debug your project, the session remains open.
![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/fbec43cc-12b4-451f-8b2c-39c955a77e05)
[](url)

### Steps to reproduce

1. Make sure you don't have permissions to execute the executable configured in settings
2. Start a debugger session

**Comment by moritz-t-w** [comment]
related #462

**Comment by DaelonSuzuka** [comment]
The debugger has been almost completely rewritten in `master`, and one of the big goals was consistency and reliability in starting/stopping debug sessions.

I'm not 100% certain that this exact problem will be fixed, but you should try it again when the new version gets released in a week or so.

**Comment by DaelonSuzuka** [comment]
> I'm not 100% certain that this exact problem will be fixed, but you should try it again when the new version gets released in a week or so.

Apparently "or so" == "three months". Oops

@moritz-t-w Are you still experiencing this issue with the released version of `2.0.0`?

**Comment by moritz-t-w** [comment]
I tried to recreate the underlying permissions issue to see if the resulting debugger instance issue is fixed. There's now this error message after `chmod -x`ing the executable.
![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/223fb59d-80bd-4d85-9d10-0d02016380b7)
The debugger instance doesn't get started in the first place, therefore, if I recreated the permissions problem correctly, this issue is not present anymore
