### ISSUE TITLE
Debugger can't find project.godot in workspace

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#540]
### Godot version

n/a

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Arch Linux

### Issue description

When using a workspace with one folder it doesn't find the `project.godot` file. It does work tho when I just open the folder
It would be nice if this worked with multiple folders in a workspace too or even when `project.godot` is in a subfolder, as long as there's only one  `project.godot`.

### Steps to reproduce

1. Open a workspace with a folder that contains a `project.godot`
2. Launch the debugger

**Comment by DaelonSuzuka** [comment]
Already fixed in `master`.
