### ISSUE TITLE
`"patterns"` array does not work with `"match"` TextMate

### ISSUE THREAD

**Issue by RedCMD** [godotengine/godot-vscode-plugin#542]
### Godot version

NA

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

`"patterns"` does not work with `"match"`
escape characters will not get tokenized
did you mean to use `begin`/`end` instead?
```json
"begin": "\""
"end": "\""
```
https://github.com/godotengine/godot-vscode-plugin/blob/f65033c6260e9eb5256d2c02a51a036c88d2ceb9/syntaxes/GDResource.tmLanguage.json#L201-L214

I don't recommend putting the string contents in a capture group and using `"patterns"` inside `"captures"`
as that incurs a medium performance hit in VSCode TextMate
EDIT: `"name"` inside `"captures"` is fine

If Godot shouldn't support escape characters inside a string
then the `"patterns"` array can be safely removed

### Steps to reproduce

Create a string with escape characters inside it `\\`
`[ "string\\bar" ]`

**Comment by DaelonSuzuka** [comment]
Good catch, thank you.

> I don't recommend putting the string contents in a capture group and using "captures"
**as that incurs a medium performance hit in VSCode TextMate**

How do you know that? I've been looking for resources on TextMate best practices for a while, but there isn't much content in this area.

**Comment by RedCMD** [comment]
> but there isn't much content in this area.

heres some links I've used:
- https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide
- https://macromates.com/manual/en/
- https://macromates.com/textmate/manual/
- https://www.apeth.com/nonblog/stories/textmatebundle.html
- https://gist.github.com/Aerijo/b8c82d647db783187804e86fa0a604a1
- https://github.com/kkos/oniguruma/blob/master/doc/RE
- https://github.com/chbk/flight-manual.atom.io/blob/scopes/content/hacking-atom/sections/syntax-naming-conventions.md
- https://github.com/microsoft/vscode-textmate
- https://github.com/kkos/oniguruma

> How do you know that?

Through my own personal testing
I was confused as to why some rules were causing more lag than others for seemingly no reason
turned out simply just using a `"patterns"` array inside `"captures"` was causing the lag
I suspect its doing an inefficient string copy?
you wont see the performance difference much until you try tokenizing 5000+ character lines or 10,000+ line files
EDIT: Using `"name"` inside `"captures"` is fine

**Comment by DaelonSuzuka** [comment]
Holy shit, you're the `tmLanguage.json` syntax extension guy! That's an excellent tool, thank you for building it!

> \<links>

Fantastic, thank you! Those are going in [my list](https://daelon.net/posts/vscode_extensions/) right away.

I was already planning to do some performance testing soon[0], so this is really useful stuff.

[0] I'm building a code formatter for GDScript using the tm grammar and `vscode-textmate`
