### ISSUE TITLE
breakpoint cancellation fails to synchronize

### ISSUE THREAD

**Issue by funny-cat-happy** [godotengine/godot-vscode-plugin#543]
### Godot version

Godot v4.2.stable - Windows 10.0.22621 - GLES3 (Compatibility) - Intel(R) HD Graphics 4000 (Intel Corporation; 10.18.10.4252) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### VS Code version

1.84.2

### Godot Tools VS Code extension version

1.3.1

### System information

win11

### Issue description

https://github.com/godotengine/godot-vscode-plugin/assets/53287533/e37bb707-7860-4cd2-bf26-c0fbe07dd292

If I cancel a breakpoint, it can not synchronize to godot. But godot breakpoint can synchronize to godot.

### Steps to reproduce

follow https://github.com/godotengine/godot-vscode-plugin/issues/389#issuecomment-1782257104 to config. reproduce like above video.

**Comment by LeifintheWind** [comment]
Similar/duplicate(?) of issue #518

**Comment by funny-cat-happy** [comment]
> Similar/duplicate(?) of issue #518

yes.
