### ISSUE TITLE
Failed to launch Godot instance on VSCode

### ISSUE THREAD

**Issue by CapitaoFantastico** [godotengine/godot-vscode-plugin#546]
### Godot version

4.2 Stable

### VS Code version

1.85.0

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 11

### Issue description

I download Godot 4.2 and tried to configure VSCode to use it.
But when i tried to run do project from VSCode i received that error: 

Failed to launch Godot instance: Error: Command failed: "C:\apps\Godot_v4.2-stable_win64.exe\Godot.exe" --path "D:\godotProjects\ReTetris" --remote-debug 127.0.0.1:6007

LSP Server connect with no problem.
When i open VSCode without open Godot, i receive the message below and if i click to open, they open Godot normally:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/f405513d-d9a5-433e-bd22-7ccc25760777)

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/0a039d8e-76e8-481f-a020-389518c08e24)

Editor Path
![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/ab0820d9-a656-4c79-874d-6e5d3e61f278)

launch.json
![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/e15aac6d-4daf-482c-a993-c584f37dd2c9)

Debug Server:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/97268031-f2cb-4cb9-b5de-2a3a192bd746)

### Steps to reproduce

- Download Godot 4.2
- Download VSCode
- Install the Extension
- Create a new launch.json
- Try to run everything

**Comment by CapitaoFantastico** [comment]
the 3rd pic are the language server config and works fine when when i open Godot and VScode

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/baddeb8a-b9f2-4428-9cc5-abad9e0c0399)

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/b5d34a52-6eae-4bf6-9e77-4b8eaee25dd9)


The problem occour when i tried to run the project:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/6270398/2ba9d97d-2d98-42a8-9c07-7a5faeab2030)

**Comment by microBob** [comment]
Ah ok. On line 12 of your launch script, it looks like you're still trying to use port 6007. Try changing that to 6005.

**Comment by DigiBanks99** [comment]
I've set the debug port to 6005 and configured my launch.json to use 6005 and I get the same error as OP:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/235971/0bf40bc2-1c2a-4db0-a425-4d63d8f5c6fa)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/235971/548358c7-eee7-47d5-a576-7bb722917fd0)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/235971/8555ad63-267d-47d9-b5fc-d3c7c25627ed)

**Comment by DigiBanks99** [comment]
My issue was solved by [this workaround](https://github.com/godotengine/godot-vscode-plugin/issues/389#issuecomment-1806992798) mentioned in #389

**Comment by CapitaoFantastico** [comment]
> My issue was solved by [this workaround](https://github.com/godotengine/godot-vscode-plugin/issues/389#issuecomment-1806992798) mentioned in #389

Solved with this solution, thanks!

btw this solution needs to be on the plugin's documentation

Thanks to everybody

**Comment by DaelonSuzuka** [comment]
> btw this solution needs to be on the plugin's documentation

Most of the extension's features don't actually work if you use the `debugServer` "workaround". If you're happy with your experience using it, that's fine, but I'm not going to recommend and there's no way it's going in the documentation.

**Comment by DigiBanks99** [comment]
So, should this be opened again or will #389 serve as tracking?

**Comment by DaelonSuzuka** [comment]
What's there to track? The people in that thread are clearly satisfied, so why is it my place to barge in and tell them that they're having fun the wrong way?

My only opinion is specifically in response to the idea of putting that non-solution in the documentation.

**Comment by atirut-w** [comment]
> The people in that thread are clearly satisfied, so why is it my place to barge in and tell them that they're having fun the wrong way?

I think you should slow down a bit there. Yes, they found the workaround to be satisfactory, but the feature still doesn't work as intended, yes? There's no rush, but it wouldn't be good if this issue goes unfixed either.
