### ISSUE TITLE
Support Region blocks

### ISSUE THREAD

**Issue by microBob** [godotengine/godot-vscode-plugin#547]
### Godot version

4.2-stable

### VS Code version

1.85

### Godot Tools VS Code extension version

1.3.1

### System information

macOS

### Problem statement

Godot 4.2 introduces folding region blocks like this:
```gdscript
#region My Region
...
#endregion
```

### Proposed solution

It would be great if VSCode could recognize these blocks, perform autocomplete to create them, fold them, and show them in the outline.

**Comment by DaelonSuzuka** [comment]
https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder

**Comment by Calinou** [comment]
@DaelonSuzuka This could be added as a recommended extension to this extension, since it's a standard part of GDScript now.

**Comment by DaelonSuzuka** [comment]
I have almost never _not_ been annoyed by extension recommendations, but I'll think about it.
