### ISSUE TITLE
launch_scene setting not working

### ISSUE THREAD

**Issue by DeszkaCodes** [godotengine/godot-vscode-plugin#551]
### Godot version

4.2.stable.mono.official

### VS Code version

1.85.1

### Godot Tools VS Code extension version

1.3.1

### System information

Windows 10

### Issue description

Hi!

I cannot get the currently opened scene to start using the extension in version 1.3.1. Whenever I start a debugging session, the main scene starts running.

This is my `launch.json`.

```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch current scene",
            "type": "godot",
            "request": "launch",
            "project": "${workspaceFolder}",
            "port": 6007,
            "debugServer": 6008,
            "address": "127.0.0.1",
            "launch_game_instance": true,
            "launch_scene": true
        }
    ]
}
```

### Steps to reproduce

1. Set `launch.json` to
```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch current scene",
            "type": "godot",
            "request": "launch",
            "project": "${workspaceFolder}",
            "port": 6007,
            "debugServer": 6008,
            "address": "127.0.0.1",
            "launch_game_instance": true,
            "launch_scene": true
        }
    ]
}
```
2. Open a scene in Godot
3. Start debugging with Visual Studio Code
4. Main scene will open

**Comment by DaelonSuzuka** [comment]
Yeah, this feature is confusing and doesn't work very well. It's being removed and replaced with something much nicer in the next extension update.

If you want to try and get it working now, I think you need to right click on the scene(the `.tscn` file) in VSCode's file explorer and select "Set as scene", then you can try to debug.

**Comment by DeszkaCodes** [comment]
Unfortunately that still does not solve the issue.

**Comment by DaelonSuzuka** [comment]
Sorry, that's as much as I know about the old settings. You can try the new version by installing `master`, or wait for the next release to get published (which I'm trying to do very soon).

**Comment by DeszkaCodes** [comment]
Thank you anyways!
