### ISSUE TITLE
any keyword between : and end of line gets treated as type by highlighter

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#562]
### Godot version

v4.2.1.stable.arch_linux

### VS Code version

Version: 1.85.1 Release: 23348 Commit: 08e6c15293922dd53a864bb041be381322fee401 Date: 2023-12-14T20:36:42.296Z Electron: 25.9.7 ElectronBuildId: undefined Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Linux x64 6.1.70-1-lts

### Godot Tools VS Code extension version

1.3.1

### System information

n/a

### Issue description
Any single keyword between `:` and the end of the line gets highlighted green, like a type
![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/0bc1a692-f1f3-49b9-8e20-c21254199764)
```gdscript
func foo():
	if true: return
	else:
		return
```

### Steps to reproduce

1. paste this: `:x`
2. x is green
3. cry

**Comment by moritz-t-w** [comment]
![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/05effe3b-d28d-4051-b635-911ae43a0e7b)
```gdscript
const c = {
	"a": true,
	"b": true
}
```
Here's another example

**Comment by moritz-t-w** [comment]
![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/5cc7552b-e431-4921-ae8f-34e6f70803ee)
even this gets highlighted

**Comment by DaelonSuzuka** [comment]
I believe these were all fixed in `master` a while ago.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/2f7920bc-db16-4d94-8f07-cc1e3c900596)
