### ISSUE TITLE
Prerelease Version on Marketplace

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#563]
### VS Code version

`1.63.0`+

### Problem statement

I have run into several issues that turned out to be fixed in master. It's a chore to manually reinstalling the extension from dev builds.

### Proposed solution

I would love to be able to switch to the pre-release version from within the editor.
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_63.md#pre-release-extensions

**Comment by Calinou** [comment]
I think we could just release 2.0.0 now. I haven't followed how many breaking changes occurred lately, so maybe releasing it as 1.4.0 is fine if it still works with Godot 3.x.

**Comment by moritz-t-w** [comment]
@Calinou 
Sure but that's a separate issue, I still think prerelease versions should be integrated properly, since they're already being released, so it wouldn't be too much effort to also release them to the marketplace

**Comment by Calinou** [comment]
> I still think prerelease versions should be integrated properly, since they're already being released

There are no prerelease versions tagged on GitHub, so there are none that could be uploaded on the marketplace.

**Comment by DaelonSuzuka** [comment]
> I haven't followed how many breaking changes occurred lately, so maybe releasing it as 1.4.0 is fine if it still works with Godot 3.x.

There are breaking changes from replacing entire sections of the workflow, but everything is still 3.x compatible. I've been aiming at a `2.0.0` release, but I was also trying to resolve some issues people had reported on `master`. It's possible that I'm aiming too high in terms of expected polish...

> If @DaelonSuzuka is OK with it, I can tag the current state of the repository as 1.4.0 or 2.0.0 and upload it to the marketplace.

I think you should do a pre-release now at `1.4.0`, but then we should set up publishing via GitHub Actions. I'll message you later and we can talk about the details.

**Comment by dawsonc623** [comment]
Do we happen to have an update on a release, or is the best option for getting a newer build to grab the dev build currently?

**Comment by Calinou** [comment]
Since README.md mentions 2.0.0 already, I guess it makes sense to publish a 2.0.0 next week.

**Comment by Calinou** [comment]
@DaelonSuzuka I've left you a message on Godot contributors chat, can you check it?

**Comment by DaelonSuzuka** [comment]
@Calinou Sorry about that, my login expired and I didn't notice.

**Comment by Calinou** [comment]
[2.0.0 has been released](https://github.com/godotengine/godot-vscode-plugin/releases/tag/2.0.0), superseding this issue.

**Comment by moritz-t-w** [comment]
What about future prerelease versions?

**Comment by moritz-t-w** [comment]
If that's not planned, close this as "not planned", not as "completed"

**Comment by DaelonSuzuka** [comment]
> close this as "not planned", not as "completed"

Why, for the archeological record? Future historians are going to be _very cross_ with us if we Do It Wrong™?

> What about future prerelease versions?

How can we possibly answer this? If it makes sense at the time, we'll do a pre-release. If it doesn't, we won't.

**Comment by moritz-t-w** [comment]
> Why, for the archeological record?

Yes, think of the future generations. But also so one can quickly see if this issue was completed or not. If I search for an issue about prerelease versions because I can't find them, and see this closed as completed, I think I must be wrong and there is in fact a prerelease version. It's not that important obviously, it's just that there is a simple way to mark the issue correctly, so why not use it.

> How can we possibly answer this?

I didn't mean to make you answer it, I'm just saying that this issue is not superseded and should either be closed as "not planned" or left open to be decided on in the future.

**Comment by Calinou** [comment]
> If that's not planned, close this as "not planned", not as "completed"

The way GitHub exposes this UI can be pretty confusing, so I prefer not using the "closing as not planned" functionality. I've had people complain about the exact opposite when I used it :slightly_smiling_face:

**Comment by moritz-t-w** [comment]
Yeah GitHub sucks :/
