### ISSUE TITLE
Terminal Formatting

### ISSUE THREAD

**Issue by moritz-t-w** [godotengine/godot-vscode-plugin#564]
### Godot version

v4.2.1.stable.arch_linux

### VS Code version

1.85.1

### Godot Tools VS Code extension version

4ae31bf99d0309fd646cda8ff62d9ec85c840b9e

### System information

Arch Linux

### Problem statement

Godot provides colored output to the terminal:
![Screenshot from 2024-01-08 11-08-56](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/a6a427b8-85a8-4197-95da-90c3a60375b6)
But the separate terminal ignores it and there's also some weird indenting going on:
![image](https://github.com/godotengine/godot-vscode-plugin/assets/90388353/2fe115b1-3af4-46e9-af56-2736f7680b3e)

### Proposed solution

support it ¯\\\_(ツ)_/¯

**Comment by DaelonSuzuka** [comment]
I'm fairly confident this is impossible. Godot's stdout would need to have the color code information in it, but it doesn't.

**Comment by moritz-t-w** [comment]
But how is zsh getting it then?

**Comment by DaelonSuzuka** [comment]
I mistook your first screenshot for the in-editor terminal. In that case it should *already* be working because I'm simply redirecting the stdout I receive to VSCode's terminal, which definitely supports colors.

**Comment by moritz-t-w** [comment]
Well it's not

**Comment by DaelonSuzuka** [comment]
> Well it's not

Yes, I am _clearly_ aware of that. 

Nothing I try has any effect, so all I can conclude is that VSCode's `vscode.Pseudoterminal` just doesn't support this for some reason.

**Comment by moritz-t-w** [comment]
> Yes, I am clearly aware of that.
Sorry, didn't mean to be rude to u, I was being rude to VSCode's terminal 😂

Guess I'l close as wontfix then.

**Comment by DaelonSuzuka** [comment]
> Sorry, didn't mean to be rude to u, I was being rude to VSCode's terminal

Don't worry about it, I was also annoyed at VSCode over this. Moving bytes from one stream to another should definitely just work. Half of the options/settings that were recommended for similar issues with Node just caused NO output instead. 

I'll look into this again in the future, maybe when I have the patience to trace through the editor's source code or something.
