### ISSUE TITLE
Active Scene Tree saying data has not been requested

### ISSUE THREAD

**Issue by BrysonMcI** [godotengine/godot-vscode-plugin#565]
### Godot version

4.3.dev1.official [9d1cbab1c]

### VS Code version

1.85.1

### Godot Tools VS Code extension version

4ae31bf99d0309fd646cda8ff62d9ec85c840b9e

### System information

Windows 11

### Issue description

The active scene tree in the debugger (the inspector and scene preview as well, but not as worried about those) always says the data has not been requested after hitting refresh. No logs in the VSCode output console for the debugger (or lsp). Breakpoints, stack trace, and viewing state at the breakpoint do work though.

Any logs or data I could investigate to help? My project is quite large so not sure I could provide that.

### Steps to reproduce

1. Launching using
```json
{
    "name": "Godot Launch",
    "type": "godot",
    "request": "launch",
    "project": "${workspaceFolder}",
    "port": 6007,
    "debugServer": 6006,
    "address": "127.0.0.1"
}
```
2. Set a breakpoint and let it get hit
3. Hit refresh on Active Scene Tree
4. Nothing happens

**Comment by DaelonSuzuka** [comment]
Using the `debugServer` option is not recommended. None of this extension's custom debug features are available when using it.

I suggest making sure you're using the latest `2.0.0` of this extension, and then creating a new debug profile in `launch.json` with the following:

```json
{
    "name": "Godot Launch",
    "type": "godot",
    "request": "launch"
}
```

**Comment by BrysonMcI** [comment]
Looks like 2.0 with the extra config options removed works for live debugging panels.
