### ISSUE TITLE
Add option for disabling formatter

### ISSUE THREAD

**Issue by MarkhorDev** [godotengine/godot-vscode-plugin#568]
### Godot version

4.1.3

### VS Code version

1.85.1

### Godot Tools VS Code extension version

4ae31bf

### System information

Windows 10

### Problem statement

I want to use a different formatter, but keep using the other features of this extension.

### Proposed solution

Add a way of disabling the formatter, or at least disable auto-formatting on save.

**Comment by DaelonSuzuka** [comment]
Those are both VSCode features. Just turn format-on-save off.

**Comment by MarkhorDev** [comment]
Not my smartest moment, I forgot format-on-save is a VSCode thing, apologies. But I cannot see a way of disabling the formatting for this extension or choosing which extension to use for formatting?

**Comment by DaelonSuzuka** [comment]
Command Palette > Format document with > configure default formatter

**Comment by MarkhorDev** [comment]
Yes. Thank you. I feel really stupid. Sorry for wasting your time.

**Comment by DaelonSuzuka** [comment]
> Yes. Thank you. I feel really stupid. Sorry for wasting your time.

Don't worry it! You asked a question, you learned something. It happens to all of us.
