### ISSUE TITLE
True, false, & null do not show up in autocomplete

### ISSUE THREAD

**Issue by kennethdamica** [godotengine/godot-vscode-plugin#57]
The constants true, false, & null don't show up in my autocomplete results. 

My guess is that there's something wrong [here](https://github.com/GodotExplorer/godot-tools/blob/921977fbdb368fd0a077ef05fe04093492cf8bb8/configurations/GDScript.tmLanguage.json#L103)

**Comment by Geequlim** [comment]
Nope all keywords is not provided by the autocomplete yet.

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by GammaGames** [comment]
Will the new release also have the new constants, like the various helpers for `Vector3`?

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
