### ISSUE TITLE
Add support for type inference inlay hints

### ISSUE THREAD

**Issue by LeoDog896** [godotengine/godot-vscode-plugin#588]
### Godot version

4.2

### VS Code version

1.86.0

### Godot Tools VS Code extension version

2.0.0; bf1d739d073c93f62abf280a7ae19d5c3054c935

### System information

Windows 10

### Problem statement

You can't see the type of inferred assignments without having to hover over the variable or the function that creates it

### Proposed solution

Use VSCode's native [inlay hints](https://code.visualstudio.com/docs/typescript/typescript-editing#_inlay-hints) feature.

### Extra notes:
- I don't mind implementing this
- This extension has never implemented inlay hints, so it doesn't seem as if the platform information above matters.

**Comment by Calinou** [comment]
Sounds good to me. I suggest coordinating with @DaelonSuzuka on this, but it may be better to focus on finalizing what's already being developed so we can release the long overdue 2.0.0.

**Comment by DaelonSuzuka** [comment]
Not a bad idea. I investigated inlay hints for types before, but the type information that's available from the LSP is inconsistent. I wasn't sure how good the experience would be if only half or less of the variables had hints resolve properly.

> I don't mind implementing this

If you *want* to do it you're more than welcome. I'm already familiar with the systems required so it would probably take me an hour or two to add this.

Implementation notes off the top of my head:
- This feature would need to work with Godot 3 and 4, and the relevant LSP messages are formatted differently between the two.
- Some users HATE inlay hints, so there needs to be a setting that disables it
- `src/providers/inlay_hints.ts`

> This extension has never implemented inlay hints, so it doesn't seem as if the platform information above matters.

Open a scene file lol:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/dfadff3d-fc80-47bd-adcb-5d0a05cb3f20)

**Comment by LeoDog896** [comment]
> Open a scene file lol:

whoops! meant in GDScript;

**Comment by DaelonSuzuka** [comment]
> whoops! meant in GDScript;

I assume most users have never even opened a scene file in VSCode, so I have to take every opportunity to shill all the work I put into those features!

**Comment by LeoDog896** [comment]
> > whoops! meant in GDScript;
> 
> I assume most users have never even opened a scene file in VSCode, so I have to take every opportunity to shill all the work I put into those features!

So far, this is the best extension I've used to resolve pesty merge conflicts, so thanks for the extra scene features! 👍 (that's also why I wanted to contribute back in the first place; after that, I'm finding the dual vs/godot coding experience quite nice)

**Comment by Calinou** [comment]
- Implemented by https://github.com/godotengine/godot-vscode-plugin/pull/589.
