### ISSUE TITLE
Error: Class "SkillNode" hides a global script class.

### ISSUE THREAD

**Issue by esklarski** [godotengine/godot-vscode-plugin#590]
### Godot version

4.2.1

### VS Code version

1.86.1

### Godot Tools VS Code extension version

1.3.1

### System information

Fedora 39

### Issue description

All scripts in which I use the `class_name` identifier report the following error in VSCode: `Class "xxxxxxx" hides a global script class.`

This isn't an issue in the editor, and the game project works fine with no errors in the engine IDE.

I really have no idea where to start looking for a solution.

![Screenshot from 2024-02-13 13-32-38](https://github.com/godotengine/godot-vscode-plugin/assets/55821817/d41281e8-c16a-44b6-83a5-232a71432eb7)

![Screenshot from 2024-02-13 13-35-03](https://github.com/godotengine/godot-vscode-plugin/assets/55821817/a7d1b211-0df6-4397-bcb0-9618e4531bbd)

### Steps to reproduce

Load a project folder, connect the language server, open a script that uses the `class_name` syntax.

**Comment by DaelonSuzuka** [comment]
This is a known problem with with the Language Server, which is a component of the Godot Engine. Unfortunately, this extension just uses the language server, and has no control over it's development. 

This particular issue has been known for a long time and has been reported here multiple time.

**Comment by esklarski** [comment]
I figured it out!

It was a quirk of my file system. If I open the project from a symlink (`~/DATA/blah`) I get this error, but if I open the folder from a root relative path (`/mnt/DATA/blah`) it works.

So beware symlinks and VSCode, I guess.


[godot engine issue](https://github.com/godotengine/godot/issues/88976#issuecomment-1982130703)

**Comment by DaelonSuzuka** [comment]
Very interesting! Thanks for reporting back with your findings. 

I feel like things *should* work properly through symlinks, but it's a lot of extra moving parts, so I'm *surprised* either.

I'm going to add this to my mental list of "wierd things the extension could possibly notice and warn you about?", to be worked on at a later time.

**Comment by esklarski** [comment]
It is interesting that it's only this class declaration thing that causes issue. Every other feature I experienced worked as expected.

Like it could complain about hiding a global class, while correctly syntax checking the rest of the document.

Weird indeed.
