### ISSUE TITLE
`func` alone is highlighted as variable instead of keyword

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot-vscode-plugin#591]
### Godot version

N/A

### VS Code version

1.86.2

### Godot Tools VS Code extension version

v2.0.0 (bf1d739d073c93f62abf280a7ae19d5c3054c935)

### System information

Windows 11

### Issue description

`func` is only highlighted as keyword when there is at least one opening parenthesis on the same line:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/25323231/bd24cb36-3c6f-42d4-8efe-e687533ab8c7)

### Steps to reproduce

```gdscript
extends Node

func

func ()

func (
```

**Comment by xiaoxustudio** [comment]
I don't think this is a bug. gdscript functions are defined with parentheses, so I think it's pointless to test them like this

**Comment by atirut-w** [comment]
It's not pointless if it's for the sake of consistency. Also, This is how it looks in Godot's editor:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/25323231/e04dbe52-fdb4-46ed-b516-466cc43ed5a7)

**Comment by DaelonSuzuka** [comment]
The better metric is whether "func" is a valid identifier name. I don't think it is, which means "func" should always be a keyword.

**Comment by xiaoxustudio** [comment]
oh ！That seems to be the case. I was wrong. I'm sorry
