### ISSUE TITLE
Godot executable is invalid on macOS

### ISSUE THREAD

**Issue by sanchan** [godotengine/godot-vscode-plugin#598]
### Godot version

v4.2.1.stable.official [b09f793f5]

### VS Code version

1.86.2 (Universal)

### Godot Tools VS Code extension version

2.0.0

### System information

macOS 14.3.1

### Issue description

I keep getting this error:

<img width="667" alt="image" src="https://github.com/godotengine/godot-vscode-plugin/assets/640237/65e3db77-3425-4560-867a-ea37674d04a1">

when my setting for the editor path is:

<img width="650" alt="image" src="https://github.com/godotengine/godot-vscode-plugin/assets/640237/98e9dc27-734f-4e4c-8442-d36430c3e1b0">

I suspect it could be related to the Filesystem type. I'm using APFS **without** case-sensitive (default on macOS)

### Steps to reproduce

- Set in your settings:

```
"godotTools.editorPath.godot4": "/Applications/Godot.app/Contents/MacOS/Godot",
```

- Reload VSCode

**Comment by stfufane** [comment]
I can confirm I have the same issue on Mac OS Sonoma with the latest VS Code and version of the plugin. Somehow it doesn't prevent it to work, it just shows this error.

**Comment by DaelonSuzuka** [comment]
@sanchan 

Your screenshot says `(Also modified in workspace)`. Is there a path specified in `./.vscode/settings.json` that's conflicting with the one specified in your user settings?

@stfufane 

The error message should probably say *some* extension features will not work correctly. Only things that require launching a godot process, like using the debugger or opening the Editor, will require the editorPath to be set correctly.

**Comment by debris** [comment]
> Your screenshot says (Also modified in workspace). Is there a path specified in ./.vscode/settings.json that's conflicting with the one specified in your user settings?

This solved the issue for me. Better error message would be definitely helpful. Especially when `./.vscode/settings.json` is automatically created and user is oblivious to it's existance

**Comment by stfufane** [comment]
You're completely right, didn't notice it either 😬 That fixed it for me too, thanks for the tip !

**Comment by DaelonSuzuka** [comment]
> Especially when ./.vscode/settings.json is automatically created and user is oblivious to it's existance

...What's automatically creating it? This extension shouldn't have done that. Can you share the entire `./.vscode/settings.json`? (and maybe check when it was created?)

> Better error message would be definitely helpful.

How do you think it could be improved? It's telling you exactly what path it tried. When you looked at your settings, you didn't notice that it was a different path than your user setting, and you didn't notice the `(Also modified in workspace)`.

User settings being overridden by workspace settings is a fundamental feature of VSCode, and I both can't and wouldn't write the extension to do something like check where a particular setting is defined and react differently based on that.

**Comment by joelpryde** [comment]
I am getting this issue even with the local workspace settings cleared.  I am pointing it at Godot_mono.app btw:
<img width="465" alt="CleanShot 2024-02-26 at 11 49 54@2x" src="https://github.com/godotengine/godot-vscode-plugin/assets/1554710/025015b1-6ef3-43d0-bbdc-dbc18fc700b2">

**Comment by DaelonSuzuka** [comment]
I'm not a Mac guy, but I think `Godot_mono.app` is a folder.

**Comment by joelpryde** [comment]
You are completely correct!  My bad, I read "Application" instead of "executable" somehow.  All working now.  :)

**Comment by brian-xu** [comment]
After moving the application to my $HOME directory as suggested in the above mention, both issues appear to have completely disappeared.

**Comment by charafau** [comment]
> After moving the application to my $HOME directory as suggested in the above mention, both issues appear to have completely disappeared.

as strange as it seems, it was also solution for me

**Comment by geekley** [comment]
Can you reopen this?
I'm having this issue when trying to point to flatpak Godot. This was working before, but not anymore:
```jsonc
"godotTools.editorPath.godot4":
"/home/user/.local/share/flatpak/app/org.godotengine.Godot/current/active/export/bin/org.godotengine.Godot"
```
(this points to an executable shell script file that calls `flatpak run ...` passing the arguments forward)
Is flatpak no longer supported? How does the extension determine whether the executable is valid?

I'm using snap VSCodium btw, so it's not an inter-flatpak isolation issue. In fact, I tried copying the script contents to a different folder (without symlinks) to test that and it still didn't work.

**Comment by geekley** [comment]
Also, can't you read the correct Godot 4 path from `.godot/editor/project_metadata.cfg`?

I think it should generally work, except for the flatpak case, of course:
```ini
[editor_metadata]
executable_path="/app/bin/godot-bin"
```
Sorry if I'm saying something stupid and you're already doing this, but the setting's description doesn't mention reading this value by default or anything like that. Reading this value makes it easier when you have multiple projects in different Godot versions.

**Comment by rchavik** [comment]
In my case, even starting godot from cli caused a crash with some codesigning error which i've lost the exact message.

Solved it via:

```
xattr -dr com.apple.quarantine /Applications/Godot.app
codesign --force --deep --sign - /Applications/Godot.app/Contents/MacOS/Godot
```
