### ISSUE TITLE
ScenePreview does not work for CharacterBody3D

### ISSUE THREAD

**Issue by DavidAriOstenfeldt** [godotengine/godot-vscode-plugin#600]
### Godot version

4.2.1.stable and 4.3.dev3

### VS Code version

1.86.2

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 10

### Issue description

When using the new ScenePreview in vscode, CharacterBody3D and any child of it are not detected.

CharacterBody3D as root in Godot:
![billede](https://github.com/godotengine/godot-vscode-plugin/assets/57765588/07bf46cc-d5cb-4c84-be72-f1e56106c708)

CharacterBody3D as root in VS code:
![billede](https://github.com/godotengine/godot-vscode-plugin/assets/57765588/7a6f2610-b5ce-4f2e-94fa-fddcd3d280d4)

CharacterBody3D as child of root in Godot:
![billede](https://github.com/godotengine/godot-vscode-plugin/assets/57765588/1ee996be-a677-49be-a5b1-494339bc609b)

CharacterBody3D as child of root in VS Code:
![billede](https://github.com/godotengine/godot-vscode-plugin/assets/57765588/aa56e082-b97c-4749-b68e-5d52fe1714e5)

It shows up when instanciated in another scene as a PackedScene:
![billede](https://github.com/godotengine/godot-vscode-plugin/assets/57765588/fa1ffd4a-87c3-4392-9341-31682725c1fa)

I have tried with various other nodes, and it only seems to appear with CharacterBody3D.

_This is my first time opening an issue, sorry for any errors I might have made_

### Steps to reproduce

1. Create a CharacterBody3D anywhere in a scene in Godot
2. Save the scene
3. Open the scene with the CharacterBody3D in the scene preview in VS Code

**Comment by DaelonSuzuka** [comment]
That's super weird, thanks for the report! 

I can't actually replicate this:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/9890d981-edd8-4621-b8ce-e03dfeb363bd)

If you don't mind, can you upload a scene file that causes this behavior?

**Comment by DavidAriOstenfeldt** [comment]
I just tried creating a new scene with a CharacterBody3D, and it managed to detect it, even though my previous tests did not work, so I am unsure what was happening.



However, it still does not detect the two examples from my initial post, so I have attached them here.

**Comment by DaelonSuzuka** [comment]
Thanks, that's exactly what I needed. 

This is the "header" block for the root node in one of your scenes:

```ini
[node name="TargetDummy" type="CharacterBody3D" node_paths=PackedStringArray("animation_player", "visuals")]
```

The `node_paths` property is a recent addition that my scene file parser isn't handling properly.

I'll have a fix for this soon.

**Comment by DaelonSuzuka** [comment]
It's working on my end using the scenes you sent me. Thanks again for those!

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/71ff357f-59b2-4634-b8ec-fefb98b9d2b5)

**Comment by DavidAriOstenfeldt** [comment]
That's great news, thank you! And thank you for your work on this awesome extension!
