### ISSUE TITLE
GDScript formatter adds space between pow operator "**"

### ISSUE THREAD

**Issue by JoelBesada** [godotengine/godot-vscode-plugin#602]
### Godot version

4.2.1

### VS Code version

1.87.0-insider

### Godot Tools VS Code extension version

2.0.0

### System information

macOS Sonoma 14.3.1

### Issue description

When formatting gdscript, any pow operators `**` gets a space inserted in between `* *`, resulting in invalid syntax.

### Steps to reproduce

Run the formatter on the following line of code: 
`var value = 10 ** 5`

**Comment by DaelonSuzuka** [comment]
Thank you for reporting this. I can't believe I forgot the exponent operator!

**Comment by DaelonSuzuka** [comment]
Closing because the fix for this was published a while ago and this problem has tests.
