### ISSUE TITLE
Smart hints have a delay

### ISSUE THREAD

**Issue by xiaoxustudio** [godotengine/godot-vscode-plugin#610]
### Godot version

4.2.2rc1

### VS Code version

1.86.2

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 11

### Issue description

When I write a script file for a huge scene file, it will only appear after two or three seconds, but when I write other gd files, it will appear after a few milliseconds.The scenario file for this script file is huge , I think this is the reason, This has never been a problem before , and I did not change any configuration

### Steps to reproduce

1. Create a root Node
2. Create 100 nested nodes as children of root
3. Create a script for the root node
4. Yes, here's the problem

**Comment by DaelonSuzuka** [comment]
Oh, also: this comment suggests that you can reduce the completion delay with some settings in the Godot Editor.

https://old.reddit.com/r/godot/comments/1axv5xv/today_i_said_goodbye_to_coding_inside_godot_and/krqp7o8/

**Comment by xiaoxustudio** [comment]
Oh! It was useful, thanks
