### ISSUE TITLE
Default indent style changes when changing / copying blocks of text between files

### ISSUE THREAD

**Issue by HankyAd** [godotengine/godot-vscode-plugin#615]
### Godot version

4.2

### VS Code version

1.87.0

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 11

### Issue description

I'm noticing regularly issues like: 
![image](https://github.com/godotengine/godot-vscode-plugin/assets/22544211/22a7a5be-e883-497d-a62b-31ce09befa8b)

When I see this, i'm noticing that at some point VSCode has swapped from TAB indentation to SPACE indentation
![image](https://github.com/godotengine/godot-vscode-plugin/assets/22544211/cb6c717e-14df-48a9-8838-a8433aab86bb)

Godot's best practices infer using tabs:
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#formatting

### Steps to reproduce

Unsure of exact steps, but it's happening about once per hour for me

I'm noticing it mostly changing when pasting code, but I can't say that for sure

I've since attempted to disable any form of formatting from VSCode to see if it will remedy. I will update accordingly if the issue stops occurring over the next few hours of programming

**Comment by DaelonSuzuka** [comment]
I don't see how that's related to this extension because it happens to me in JavaScript/TypeScript constantly.

You can try disabling 'editor.detectIndentation` and `editor.autoIndent` settings, I guess?
