### ISSUE TITLE
Open the script document to add a language switch

### ISSUE THREAD

**Issue by lionet1224** [godotengine/godot-vscode-plugin#617]
### Godot version

4.2.1

### VS Code version

1.86.2

### Godot Tools VS Code extension version

2.0.0

### System information

macOS 14.2.1 (23C71)

### Problem statement

Open the script document to add a language switch

### Proposed solution

Open the script document to add a language switch

**Comment by Rrenovation** [comment]
@Calinou I guess what he wanted to express was   [Add support for documentation in other languages](https://github.com/godotengine/godot-vscode-plugin/issues/409#issuecomment-1217433895)

**Comment by lionet1224** [comment]
> @Calinou I guess what he wanted to express was [Add support for documentation in other languages](https://github.com/godotengine/godot-vscode-plugin/issues/409#issuecomment-1217433895) 我猜他想表达的是添加对其他语言文档的支持

Yes, that's exactly what I meant.
