### ISSUE TITLE
Intellisense shows all symbols

### ISSUE THREAD

**Issue by richcollins** [godotengine/godot-vscode-plugin#62]
When typing self. the intellisense completion appears to include every possible symbol, not just those that the Sprite class responds to.

**Comment by richcollins** [comment]
<img width="1049" alt="untitled 2" src="https://user-images.githubusercontent.com/135/39729975-915b9c40-5213-11e8-9a16-fb71d49c4f84.png">

**Comment by Geequlim** [comment]
The GDScript parser cann't parse the classe correctlly yet.  So it give you all the possible symbols.
I am planing to refactor the parser if the [optional typing in GDScript](https://github.com/godotengine/godot/issues/10630) is implemented.

**Comment by richcollins** [comment]
How is the Godot editor able to limit its completions to the methods of the class?

**Comment by balenol** [comment]
I hope this get resolved. Can't wait to get a proper vscode integration.

**Comment by balenol** [comment]
Bumping the issue

**Comment by balenol** [comment]
Bumping the issue. I should remind you that Godot 3.1 beta is here, and stable are expected some weeks from today.

**Comment by chiboreache** [comment]
Can confirm — strong typing doesn't affects on IntelliSense at all.

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.
This featue can be disabled by disable select `smart resolve mode` in the editor settings.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
