### ISSUE TITLE
Some formatting breaks in lambda functions

### ISSUE THREAD

**Issue by rktprof** [godotengine/godot-vscode-plugin#624]
### Godot version

4.2.1

### VS Code version

VSCodium 1.87.1

### Godot Tools VS Code extension version

2.0.0

### System information

macOS 14.4

### Issue description

I'm not sure if other operators misbehaves but I also remember seeing the syntax coloring breaking in a lambda but can't remember what/where that was, but when using an equals sign in a lambda:
```
poll_animation.on_complete(func() -> void:
	highlight.visible = false
)
```
becomes:
```
poll_animation.on_complete(func() -> void:
	highlight.visible=false
)
```
(it also happens when the lambda content is on the same row)

### Steps to reproduce

Take the example code above and just save the file

**Comment by Calinou** [comment]
It might be worth checking whether https://github.com/godotengine/godot-vscode-plugin/pull/605 fixes this. You can download the `godot-tools` artifact from [its checks page](https://github.com/godotengine/godot-vscode-plugin/pull/605/checks) and extract the ZIP archive, then [install the VSIX file](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) contained in the ZIP.

**Comment by DaelonSuzuka** [comment]
I can say for sure that #605 does not fix this yet, but *when* it gets fixed that's where you'll be able to find it.

**Comment by DaelonSuzuka** [comment]
Pretty sure this was fixed and published, but I just added your example as a test case to make sure we don't have a regression.
