### ISSUE TITLE
Binary operators not maintaining correct spaces

### ISSUE THREAD

**Issue by hiiii5** [godotengine/godot-vscode-plugin#627]
### Godot version

4.2.1 stable

### VS Code version

1.87

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 11

### Issue description

When working with collision masks, upon formatting, binary operators are moved in odd ways causing the code to not compile.

### Steps to reproduce

The following code snippet will not format from this:
`collision_mask = 1 << 1 | 1 << 3`
to this:
`collision_mask = 1 < < 1|1 < < 3`

**Comment by DaelonSuzuka** [comment]
This has already been reported and will be fixed in #605.

**Comment by DaelonSuzuka** [comment]
This should be fixed now in #605:

**Comment by hiiii5** [comment]
Awesome thank you!
