### ISSUE TITLE
Incorrect warning "Statement contains a semicolon"

### ISSUE THREAD

**Issue by garyo** [godotengine/godot-vscode-plugin#63]
A statement with a semicolon in a quoted string should not be flagged as an error.

Test case:
```
	func("hi; test!")
```

**Comment by Geequlim** [comment]
Same with #31

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
