### ISSUE TITLE
Scene Preview is broken

### ISSUE THREAD

**Issue by StalOlympus** [godotengine/godot-vscode-plugin#646]
### Godot version

Godot v4.2.1-stable 

### VS Code version

Version: 1.88.1

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 11

### Issue description

When I add a script that has export fields to a scene and actually drag references to it, the scene preview on VSCode stays empty and nothing is displayed. 
![resim](https://github.com/godotengine/godot-vscode-plugin/assets/166549505/aeb228e3-013b-4e82-bc7d-410ecc031448)
![resim](https://github.com/godotengine/godot-vscode-plugin/assets/166549505/8c89e6fb-97d9-4b89-a79f-a8cdee0515fe)
If I clear the export fields, save the scene, and then reopen the scene in VSCode, everything is fine!
![resim](https://github.com/godotengine/godot-vscode-plugin/assets/166549505/acb3f5bb-5dd8-4399-b7a9-1314e733778a)
![resim](https://github.com/godotengine/godot-vscode-plugin/assets/166549505/d03f684c-5394-48c0-a5f4-56a5bceb3f74)
I tried it on a brand new project with default settings containing only one scene and one script and found the same problem.

### Steps to reproduce

Create and save a new scene
Attach it a script with export fields
Assign references in the editor
Save the scene and check the Scene Preview
Clear the export fields on the scene and save it
Close the scene and reopen it on VSCode

The scene preview in VSCode should display all the nodes and assigned resources correctly, regardless of whether export fields are filled. But the scene preview in VSCode is empty or does not display the expected content when export fields are filled.

**Comment by 23Chromosomes** [comment]
Same issue.

**Comment by Jimskie101** [comment]
Same Issue. Here's a test project from version Godot Mono 4.2.1

[GodotToolsScenePreview.zip](https://github.com/user-attachments/files/15838551/GodotToolsScenePreview.zip)

No attached Exports
![image](https://github.com/godotengine/godot-vscode-plugin/assets/67926209/1be6294d-c9e4-4b9a-bf4f-e68fbd51ca37)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/67926209/dabd1bc8-cacf-4a64-ac73-7b32899b9c3a)

With attached Exports
![image](https://github.com/godotengine/godot-vscode-plugin/assets/67926209/1d1ece8e-ad00-49e0-8201-bfb4b699d20e)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/67926209/d1df3e3c-4c67-4823-831e-83cc93f8aebb)

**Comment by DaelonSuzuka** [comment]
Thanks, @Jimskie101, I'll check this out.

**Comment by DaelonSuzuka** [comment]
I believe this issue was fixed in PR #603, because the problematic scene opens correctly with the current `master` branch.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/4e6a0f0d-f22b-4085-86c1-ed4786728295)

The issue was actually the `node_paths` attribute in the [node] section header, and not the exported field itself.

I'm trying to wrap up some open issues and get a new extension version published sometime in the next week.

**Comment by Visnicio** [comment]
any estimated date for this fix going to the marketplace release? for now I probably should use the dev branch right? (master)

**Comment by Calinou** [comment]
@DaelonSuzuka Is there anything blocking a release now? If not, I can tag 2.1.0 and release it.

**Comment by DaelonSuzuka** [comment]
As far as I know it's ready for release. Please feel free to publish!

**Comment by Calinou** [comment]
2.1.0 is out: https://github.com/godotengine/godot-vscode-plugin/releases/tag/2.1.0
