### ISSUE TITLE
Headless LSP can't use relative path

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot-vscode-plugin#654]
### Godot version

4.3.dev (6118592c6d)

### VS Code version

1.88.1

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 10

### Issue description

I'm working with custom engine builds, and I'd like to have a consistent vscode setup that can be pushed to git.

Trying to specify the `godotTools.editorPath.godot4` to a relative path of any kind seems to not work, with the error

```
Cannot launch headless LSP: <path> is not a valid Godot executable
```

### Steps to reproduce

- Create a `.vscode/settings.json` in your workspace.
- Create a `build` folder and put a godot executable into it.
- Fill with `{ "godotTools.editorPath.godot4": "build/godot.windows.editor.x86_64.console.exe" }`
- Try running command `godotTools.startLanguageServer`.
- Even with variations of the path like `"${workspaceFolder}/build/godot.windows.editor.x86_64.console.exe"` or `"./build/godot.windows.editor.x86_64.console.exe"` it does not manage to launch it.
- I also confirmed that it works fine with an absolute path (although the executable did open a new cmd window, likely because of using the console.exe?).

**Comment by RedMser** [comment]
Yes I could do that, but the use case is when others clone my project (which depends on a specific custom engine build). It would be convenient to include the engine directly in the workspace and not in a global location then.

Thanks for looking into it! Another thing you could try is calling `path.resolve(workspaceFolder, editorPathConfigValue)` if the config contains a relative path.

**Comment by DaelonSuzuka** [comment]
Yeah, that makes sense. Let me see what I can do.

**Comment by DaelonSuzuka** [comment]
@RedMser Do you mind downloading and installing the [build artifact](https://github.com/godotengine/godot-vscode-plugin/actions/runs/8884570944/artifacts/1458062654) and confirming that it does what you expect now?

**Comment by RedMser** [comment]
@DaelonSuzuka Yep it works as expected with a relative path in my workspace's `settings.json`! Thanks a lot :)

(Disclaimer: I have not tested full absolute paths, or paths like `godot4.exe`)

**Comment by Etruscian** [comment]
I'm still getting the same error as described in this issue. Should I create a new issue or would you like to continue on this one?

**Comment by DaelonSuzuka** [comment]
This issue has been resolved in `master`, so there's no reason to open a new one.

**Comment by Etruscian** [comment]
Ah thanks. I somehow thought it was already in the release. Any eta on when it will be released?

**Comment by DaelonSuzuka** [comment]
I'm working on cleaning up some loose ends right now, so hopefully soon.
