### ISSUE TITLE
Provide style guidance for member ordering (and auto-fix)

### ISSUE THREAD

**Issue by dabikuru** [godotengine/godot-vscode-plugin#667]
### Godot version

4.2.2.stable

### VS Code version

1.90.1

### Godot Tools VS Code extension version

2.0.0

### System information

MacOS

### Problem statement

The GDScript style guide suggests a [recommended ordering](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#code-order) of member signals, variables, and methods. 

I thought it would be really helpful if godot-tools provided an optional warning if the recommended ordering is not being followed, and offer to auto-fix if possible.

<img width="804" alt="image" src="https://github.com/godotengine/godot-vscode-plugin/assets/6017063/ba207752-844b-45cc-b920-dd4bc871a0fc">

### Proposed solution

I am not familiar with code formatting tools yet, so please forgive the high-level description!

For the auto-fix, I could imagine the following:
- Group all members into categories (e.g. signal, public/private variable, virtual/class method, public/private method)
  - This could be done by slotting them into an object with predefined keys and empty values, to avoid needing to sort by category
- Refactor the file to present all members in the recommended category order
 
Note: to avoid unexpected behavior, within each category, the original order should be preserved. E.g.:
- Input: [var A, func _process, var C, var B, func _ready]
- Output: [var A, var C, var B, func _process, func _ready]

**Comment by Calinou** [comment]
Reordering can change the code's behavior, so I doubt it's possible to do safely.

**Comment by DaelonSuzuka** [comment]
Calinou's right, this kind of thing is deceptively difficult to execute at an acceptable level of safety and reliability.

I also don't think top-level code organization is an appropriate target for auto-formatters. I'm familiar with clang-format, prettier, biomejs, black, ruff and others, and I'm not aware of one that will actually _reorder_ sections of your files.

We appreciate the interest and your effort in describing a possible solution, but this feature doesn't really align with the extension's goals or available resources.

**Comment by dabikuru** [comment]
Thank you for the explanation, I see how auto-fix cannot easily be done safely.

Would it still make sense to at least provide a warning where the recommended ordering is not being followed? This could be an optional setting.

**Comment by DaelonSuzuka** [comment]
No, because merely detecting this situation requires almost as much work as generating the quick fix suggestions, eg correctly parsing all of GDScript and sorting every available language construct into the various categories from the "recommended ordering".

**Comment by dabikuru** [comment]
Understood, thank you!
