### ISSUE TITLE
Bitwise operators is formatted incorrectly

### ISSUE THREAD

**Issue by beicause** [godotengine/godot-vscode-plugin#676]
### Godot version

Don't matters. reproducible without Godot LSP

### VS Code version

1.90.2

### Godot Tools VS Code extension version

2.0.0

### System information

Linux Mint 21.3 (Virginia) - X11

### Issue description

`<<`, `>>` will be formatted to `< <`, `> >`, which is a syntax error in gdscript as below:

![2024-07-03 09-39-33屏幕截图](https://github.com/godotengine/godot-vscode-plugin/assets/75941842/0490f824-d374-4312-b6a9-659029840604)

### Steps to reproduce

Format gdscript code containing bitwise operators.

**Comment by atirut-w** [comment]
Huh, what happened for you to close it without context?

**Comment by DaelonSuzuka** [comment]
I'm guessing he noticed that this has been reported before?

**Comment by beicause** [comment]
Fixed in #605
