### ISSUE TITLE
Option to disable builtin code formatter

### ISSUE THREAD

**Issue by snorreks** [godotengine/godot-vscode-plugin#677]
### Godot version

4.2.2

### VS Code version

1.64.2

### Godot Tools VS Code extension version

2.0.0

### System information

Linux

### Problem statement

I am using gdformat to format the files and i do not need the builtint code formatter.

### Proposed solution

```json
"godotTools.editor.formatter": false
```

**Comment by DaelonSuzuka** [comment]
VSCode only ever formats files when you tell it to. Just turn off autoformatting.
