### ISSUE TITLE
Connecting a signal doesn't create function

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot-vscode-plugin#68]
***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

___

When connecting a signal to a game object, Godot switches to the script in VS Code but the function isn't created. If I disconnect the external editor, disconnect then connect the signal, the function is then generated in the script. Not sure if this is actually a bug or a limitation to be honest.

Godot 3.0.2 Mono stable
Code plugin 0.3.6

**Comment by nathanjwtx** [comment]
I am unable to consistently get this to work. Sometimes saving the scene causes the script to load with the signal function more often than not VSCode appears with no function in it.

**Comment by Husky110** [comment]
Yep... Same problem here...
Specs:
OS: Linux Mint 19
Mono: 5.14.0.177

**Comment by blqke** [comment]
Hello,
Same problem here
macOS 10.14
VSCode 1.31.1
with Godot Tools 0.3.7

**Comment by madamc** [comment]
Hello
Doesn't work for me either.
Windows 10 (1809)
VS Code 1.32.1
Godot Tools 0.3.7

**Comment by thejacer87** [comment]
run into this issue on manjaro too

**Comment by neikeq** [comment]
This is an issue with Godot. There's little this extension can do as Godot is hard-coded to append the function to the source in the built-in editor.

Not really the same, but related: godotengine/godot#12908. The new API for `make_function` should probably allow for communicating with external tools.

**Comment by lazyvainglory** [comment]
I thought it was just me. I also want to add that there's no indicator on the attached signal like in the built in editor.

**Comment by joanroig** [comment]
Same issue here, with Godot 3.2.2 and plugin 1.1.1

**Comment by HaroldReyiz** [comment]
Same here with Godot 3.2.1 stable official and plugin version 1.1.1.

**Comment by OFGONEN** [comment]
I faced the same problem with Godot 3.2.2

**Comment by Calinou** [comment]
@OFGONEN Please read the first post before further bumping this issue :slightly_smiling_face: 

We've had enough confirmations about this issue so far. No need to confirm it any further.

**Comment by mickdekkers** [comment]
For reference, this issue can be tracked on the Godot side in https://github.com/godotengine/godot/issues/23208 and https://github.com/godotengine/godot/issues/41283

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/23208 and https://github.com/godotengine/godot/issues/41283, as this issue is unrelated to the VS Code add-on. (It occurs in any external editor.)

**Comment by Pika1998** [comment]
I am also facing this on godot v3.2.3
