### ISSUE TITLE
No debug colors

### ISSUE THREAD

**Issue by RobbyCBennett** [godotengine/godot-vscode-plugin#682]
### Godot version

4.2.1.stable.official [b09f793f5]

### VS Code version

1.91.0

### Godot Tools VS Code extension version

2.0.0

### System information

Windows 11

### Issue description

I can see debug colors when launching the game from Godot, but not when launching from VS Code.

### Steps to reproduce

1. Open a project in Godot
2. In a scene, place a `CollisionShape2D` and give it a shape and a debug color
3. Hit F5 to Run Project
4. See that the shape appears
5. Open the project in VS Code
6. Run the command `godotTools.debugger.debugPinnedFile` (Godot Tools: Debug Pinned File)
7. See that the shape doesn't appear

**Comment by Calinou** [comment]
The Godot editor communicates whether visible collision shapes should be enabled using the `--debug-collisions` command line argument, which is passed to the running project on startup. Running from VS Code won't do that as VS Code is not aware of the option's state in the editor.

**Comment by RobbyCBennett** [comment]
My bad. I didn't see `debug_collisions` in the README. Thanks.
