### ISSUE TITLE
Trims trailing whitespace when saving a script

### ISSUE THREAD

**Issue by jerryshell** [godotengine/godot-vscode-plugin#684]
### Godot version

4.2.2.stable

### VS Code version

1.91.1

### Godot Tools VS Code extension version

https://github.com/godotengine/godot-vscode-plugin/tree/9750f8dfc6e4eeba96f7df62432751930af95337

### System information

Windows 10

### Problem statement

Godot editor has a feature to trim trailing whitespace when saving a file: `text_editor/behavior/files/trim_trailing_whitespace_on_save`
Trailing whitespace refers to tab and space characters placed at the end of lines.
Since these serve no practical purpose, they can and should be removed to make version control diffs less noisy.
I wish godot-tools would add this feature too!

### Proposed solution

What's happening now: after writing code in VS Code, I have to go back to the Godot editor and manually save it once to let the Godot editor trim the trailing whitespace automatically.

**Comment by DaelonSuzuka** [comment]
This is built in to VSCode. The setting is named `editor.trimAutoWhitespace`.

**Comment by jerryshell** [comment]
> This is built in to VSCode. The setting is named `editor.trimAutoWhitespace`.

Thanks for your help! However, I have found that `editor.trimAutoWhitespace` doesn't do what I want.
After some searching, I think the correct setting is `files.trimTrailingWhitespace`.

**Comment by DaelonSuzuka** [comment]
That's what I get for rushing! I knew this was a builtin behavior so I just searched the settings page for "whitespace" and stopped at the first setting that looked close enough.
