### ISSUE TITLE
LSP as Headless child process not working with newest Godot RC

### ISSUE THREAD

**Issue by ImmaB** [godotengine/godot-vscode-plugin#685]
### Godot version

4.3.rc1

### VS Code version

1.91.1

### Godot Tools VS Code extension version

latest master branch build (27.07.2024) 

### System information

Windows 11

### Issue description

Launching the LSP as headless child process launches the entire Godot editor

### Steps to reproduce

- enable "Godot Tools > Lsp: Headless" in vscode Settings.
- restart vscode

**Comment by Calinou** [comment]
This is due to https://github.com/godotengine/godot/issues/94755 which will be fixed in 4.3.rc2.
