### ISSUE TITLE
"How to Guide" on setting up the GDScript Formatter

### ISSUE THREAD

**Issue by Luzzotica** [godotengine/godot-vscode-plugin#687]
### Godot version

4.3.0.beta1

### VS Code version

1.91.1

### Godot Tools VS Code extension version

2.1.0

### System information

MacOS Sonoma 14.5

### Problem statement

I am trying to figure out how to enable the GDScript autoformatter (as I see there is one), but cannot find any instructions on how to do so.

### Proposed solution

Create a simple step by step to enable it.

**Comment by DaelonSuzuka** [comment]
I don't really understand what you're looking for. You just hit ctrl + shift + P, type "format document" and hit enter.

**Comment by Luzzotica** [comment]
I guess I want it to happen automatically on save.

How might I achieve that?

**Comment by DaelonSuzuka** [comment]
press ctrl + comma -> type the word "format" -> behold
