### ISSUE TITLE
[Error] Request workspace/symbol failed.   Message: Method not found: symbol   Code: -32601 

### ISSUE THREAD

**Issue by MilesWilde** [godotengine/godot-vscode-plugin#697]
### Godot version

Godot_v4.3-stable_win64

### VS Code version

1.92.2

### Godot Tools VS Code extension version

2.1.0

### System information

Windows 10

### Issue description

When I am using Tabnine AI and I talk to it, the error pops up about 15-20 times inside of the GDScriptLanguageClient Output
[Error - 4:09:50 PM] Request workspace/symbol failed.
  Message: Method not found: symbol
  Code: -32601 

It force opens the output and spams errors which can be distracting. It would be nice if I could disable specific errors from showing

### Steps to reproduce

Open Godot
Open VSC
Create a blank .gd file
Connect to language server through VSC
Install Tabnine AI, talk to it
Output should pop up with the indicated error

**Comment by MilesWilde** [comment]
Still a bug, but tabnine proving not to be useful here

**Comment by bs** [comment]
@Calinou, I'm getting this on a vanilla install of VSCode.

**Comment by Calinou** [comment]
> Is cmd/ctrl-shift-o supposed to query the LSP?

Yes, it queries the list of symbols from the current file (which is returned by the LSP).

**Comment by bs** [comment]
`cmd-shift-o` isn't returning anything for me.

Any tips on debugging? I started Godot with `./Godot --lsp-server --verbose` and looking at `Godot LSP` for messages in VSCode but don't see anything.

Curiously, most messages to go `Godot LSP` but then `cmd-t` throws to `GDScriptLanguageClient`

![CleanShot 2024-08-26 at 16 34 10@2x](https://github.com/user-attachments/assets/56bc2289-253b-40aa-8f0a-41e5fdeba1ee)
![CleanShot 2024-08-26 at 16 39 08@2x](https://github.com/user-attachments/assets/53c309ff-a9b9-4e84-8480-b2fafc1c3374)

**Comment by DaelonSuzuka** [comment]
> I started Godot with ./Godot --lsp-server --verbose 

Why are you doing that? What is the `--lsp-server` supposed to do?

**Comment by bs** [comment]
@DaelonSuzuka I was trying to see what the LSP server was returning when VSCode Godot-Tools was querying it.

**Comment by DaelonSuzuka** [comment]
@bs I can't find any evidence that an `--lsp-server` flag exists or has ever existed, so I don't understand why you would do that.

> cmd-shift-o isn't returning anything for me.

There's currently a bug in the Language Server where it won't return document symbols if there is an `extends` statement anywhere except the first line of the file.

@MilesWilde As far as I can tell, this is a problem with the Language Server, which is a component of the Godot Editor. You should open an issue at https://github.com/godotengine/godot.

**Comment by bs** [comment]
@DaelonSuzuka Hmm, I can't seem to find where I got that, either. 😅 Is there a way to output the language server requests Godot sees and any errors thrown?

I can confirm that what I'm seeing is because of the order of `extends`. Do you have a link to the github issue? I did a search and couldn't find it.

**Comment by DaelonSuzuka** [comment]
> Is there a way to output the language server requests Godot sees and any errors thrown?

Not unless you want to clone the repo, set up the dev environment, and launch the extension in debug mode. The LSP is so chatty that enabling logging in release builds was causing performance problems, so I had to make it a development-only feature.

> Do you have a link to the github issue?

I don't know if there is one, I merely observed the behavior while investigating some tickets on here.

**Comment by jaredstorm** [comment]
Could this issue also crop up when trying to rename symbols in a file? I noticed that renaming has stopped working for me after updating to the latest version of the extension

**Comment by jaredstorm** [comment]
>  but I do have the unofficial Godot Files extension v0.0.10 installed.

Just tried uninstalling this and reloading to make sure it wasn't the cause, and it wasn't.

> Could this issue also crop up when trying to rename symbols in a file?

I should also clarify, I didn't notice the language server outputting `Request workspace/symbol failed` when renaming variables, but I did when searching for workspace level symbols through the command palette. (ctrl+P, then type `#test` to reproduce), but I thought they may still be related since they both have something to do with symbols, and I don't have trouble renaming variables outside of gdscript files.

**Comment by bs** [comment]
> Not unless you want to clone the repo, set up the dev environment, and launch the extension in debug mode. The LSP is so chatty that enabling logging in release builds was causing performance problems, so I had to make it a development-only feature.

Wow, that's impressive!
I think it's about time I did this. I've been wanting to hunt down a few crashes I've been getting.

> > Do you have a link to the github issue?
> 
> I don't know if there is one, I merely observed the behavior while investigating some tickets on here.

When I saw symbols being returned in Sublime and Zed, for example, I figured it was LSP results, but it looks like they're doing local indexing.

I'll open a ticket.
 
> PS: impressive username, btw PPS: the cert on your homepage appears to have expired

Thank you! Early Github days were pizza parties at a local Ruby meetup.

Thanks for the help here, and for the cert heads-up! 😂

**Comment by bs** [comment]
Thank you, @DaelonSuzuka! When I get a chance, I'll poke at the `class_name` order bug, and will ping you on Discord!
