### ISSUE TITLE
Add support for Godot shaders

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot-vscode-plugin#70]
It would be nice if this plugin could support godot shader.
Godot shader is supposed to be similar to glsl which in turn is similar to C.
I can just set VS Code to associate `.shader` as a glsl shader, but the code assist won't work.

**Comment by AlfishSoftware** [comment]
You may be interested in the grammar I coded:
https://github.com/AlfishSoftware/godot-files-vscode/blob/develop/lang.gdshader/gdshader.tmLanguage.json
I also added the language variables as snippets, with descriptions from Godot 3 docs:
https://github.com/AlfishSoftware/godot-files-vscode/blob/develop/lang.gdshader/gdshader.code-snippets
Not ideal, but works as a starting point.

**Comment by atirut-w** [comment]
There's also a new PR for gdshader syntax highlighting: #360

**Comment by Calinou** [comment]
Implemented by https://github.com/godotengine/godot-vscode-plugin/pull/360.

Note that autocompletion is currently outside the scope of the Godot editor LSP.
