### ISSUE TITLE
Error in Cursor IDE: Request workspace/symbol failed. Message: Method not found: symbol

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot-vscode-plugin#701]
### Godot version

4.3 stable

### VS Code version

Cursor

### Godot Tools VS Code extension version

2.1.0

### System information

Windows 10

### Issue description

Cursor IDE, which is a fork of VSCode, throws this error when trying to do anything: Request workspace/symbol failed.
  Message: Method not found: symbol
  Code: -32601
Hard to tell if it's a Cursor bug or the extension.

### Steps to reproduce

Try Cursor with the extension, try to do anything.

**Comment by PLyczkowski** [comment]
No longer happens after updating Cursor

**Comment by PLyczkowski** [comment]
Oops, disregard that, I tested wrong. The chat window works, the instructions window does not:
![image](https://github.com/user-attachments/assets/c58937ea-43c9-488e-9deb-f50cdd79ce51)

**Comment by DaelonSuzuka** [comment]
This is either a problem with Cursor requesting a non-standard method, or the Godot Language Server not correctly implementing a required method. This extension has no control over either of those. You could open an issue at https://github.com/godotengine/godot.

**Comment by andyfangaf** [comment]
Same issue here with Cursor.

**Comment by DaelonSuzuka** [comment]
Can somebody try installing this [development build](https://nightly.link/godotengine/godot-vscode-plugin/workflows/ci/master/godot-tools.zip) and seeing if that fixes the problem? 

Cursor is using the `workspace/symbol` request to get info about symbols in the file and (I assume) feeding that info to its LLM. I can't actually implement the `workspace/symbol` method in the Godot engine, but hopefully this build stops the annoying error.

**Comment by dannypostma** [comment]
This solved the issue for me @DaelonSuzuka, ty!

**Comment by PLyczkowski** [comment]
> Can somebody try installing this [development build](https://nightly.link/godotengine/godot-vscode-plugin/workflows/ci/master/godot-tools.zip) and seeing if that fixes the problem?
> 
> Cursor is using the `workspace/symbol` request to get info about symbols in the file and (I assume) feeding that info to its LLM. I can't actually implement the `workspace/symbol` method in the Godot engine, but hopefully this build stops the annoying error.

Can confirm this solves the problem 👍

**Comment by DaelonSuzuka** [comment]
The fix for this issue was just published in [`2.3.0`](https://github.com/godotengine/godot-vscode-plugin/releases/tag/2.3.0)! Thanks for testing the build for me @dannypostma and @PLyczkowski!
