### ISSUE TITLE
Make current godot editor instance start the game instead of calling godot binary

### ISSUE THREAD

**Issue by RuthgerD** [godotengine/godot-vscode-plugin#706]
### Godot version

4.3

### VS Code version

any

### Godot Tools VS Code extension version

2.1.0

### System information

Linux

### Problem statement

When launching the game via the vscode debug runner a new godot instance is started.
The godot editor process is completely unaware and cannot push live updates when assets change.

### Proposed solution

Somehow ask the godot editor to start the game over the connection that the vscode extension establishes.
I am not sure how this would work or if the debugger would still work.

**Comment by atirut-w** [comment]
I don't remember Godot supporting launching from remote. You can set your debug request to "attach" and start it after launching your game from the editor to work around this for the time being.

**Comment by DaelonSuzuka** [comment]
@atirut-w Unfortunately, I was never able to finish Attach session support.

@RuthgerD There's no way to do this, you have to choose between launching your debug session from VSCode or from the Godot Editor.
