### ISSUE TITLE
find function (ctrl + f) does not work when a docs page is open

### ISSUE THREAD

**Issue by Goldenlion5648** [godotengine/godot-vscode-plugin#707]
### Godot version

4.3.stable

### VS Code version

1.92.2

### Godot Tools VS Code extension version

2.1.0

### System information

windows 10

### Problem statement

When opening a "gddoc" page in VSCode, the find shortcut (ctrl + f) does not work. This makes me prefer to navigate the web docs

### Proposed solution

Make the ctrl + f shortcut work

**Comment by DaelonSuzuka** [comment]
Ctrl+F works exactly how I'd expect:

![Code_gvQa0T7nie](https://github.com/user-attachments/assets/49aaeb42-90f7-436e-96a1-47067c4da4aa)

**Comment by Goldenlion5648** [comment]
looks like it was on my end, just reset my ctrl + f keybind and it works (previously I had the when expression as `editorFocus`, it works after resetting to `editorFocus || editorIsOpen`)
