### ISSUE TITLE
'Go to Symbo in editor' can't find any symbols on gdscripts files that start with a 'class_name' declaration

### ISSUE THREAD

**Issue by LaggyFox** [godotengine/godot-vscode-plugin#709]
### Godot version

4.3.stable

### VS Code version

1.93.0

### Godot Tools VS Code extension version

2.1.0

### System information

Windows 10

### Issue description

When a gdscript file starts with a class_name declaration, using the 'Go to Symbo in editor' command (id workbench.action.gotoSymbol), results in an empty list and a message "no editor symbols".

I only encountered this issue after updating my godot version from 4.2.2 to 4.3

### Steps to reproduce

Use the following script:
```
class_name Door
extends Area2D

func _physics_process(_delta: float) -> void:
	pass
```

After removing the first line, '_physics_process' symbol should appear in the list

**Comment by DaelonSuzuka** [comment]
This extension doesn't control this behavior, the list of symbols comes from the Language Server that runs in the Godot Editor/Engine. This is a bug in the Language Server and should be reported at [ godotengine/godot](https://github.com/godotengine/godot).

**Comment by stefanobettinelli** [comment]
I'm also having the same issue.
Was this bug reported to the godot repo? I did a quick search, but I couldn't find anything
