### ISSUE TITLE
Misc quality of life improvements

### ISSUE THREAD

**Issue by GammaGames** [godotengine/godot-vscode-plugin#71]
* Use "unnecessary" color for unused variables

Right now the editor underlines unused variables, but vscode has a built in style for unused variables. It could use that style, as well as underlined.

![image](https://user-images.githubusercontent.com/7832163/42131155-7f5137e2-7cb8-11e8-8677-c7681dc47a86.png)

* Proper folding padding

Right now when you fold functions it folds all the indenting up to the next indentation level. In python, it folds with a row of whitespace between so it's easier to read.

In gdscript:
![image](https://user-images.githubusercontent.com/7832163/42131191-623e9b62-7cb9-11e8-85bb-7012b8eb60e0.png)

In python:
![image](https://user-images.githubusercontent.com/7832163/42131195-7bb66e08-7cb9-11e8-90c8-75ca991f90db.png)

**Comment by DaelonSuzuka** [comment]
Folding seems to work correctly now:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/3c253590-d60c-41ae-8ce4-79b727f9e227)

Unused variable coloration is impossible using just TextMate Grammar syntax highlighting, but semantic tokenization using the LSP is being actively looked at.
