### ISSUE TITLE
Config causes game to run at 2x speed

### ISSUE THREAD

**Issue by Burloe** [godotengine/godot-vscode-plugin#714]
### Godot version

4.3

### VS Code version

1.93

### Godot Tools VS Code extension version

2.1.0

### System information

Win 10

### Issue description

I have 3 launch configs that I use regularly to run my project and using the "w/o DebugServer" config, it makes the game to run at 2x speed(if not more). I found that when I comment out '"fixed_fps": 60', everything runs at normal speed. Checking the time scale, it's supposedly still running at normal speed. 

When using the "w/ DebugServer" config, if I comment out DebugServer, the speed up is present. I'm aware DebugServer isn't supported but inspecting nodes in the remote tree doesn't work in VSC for me on nodes with large scripts so I need to run it with DebugServer so I can access the remote tree in both VSC and Godot.

### Steps to reproduce

```json
{
    "name": "Minimal Launch",
    "type": "godot",
    "request": "launch"
},
{ // This is the one
    "name": "w/o DebugServer",
    "type": "godot",
    "request": "launch",
    "project": "${workspaceFolder}",
    "address": "127.0.0.1",
    "port": 6007,
    // "debugServer": 6006,
    "profiling": false,
    "single_threaded_scene": false,
    "debug_collisions": false,
    "debug_paths": false,
    "debug_navigation": false,
    "debug_avoidance": false,
    "debug_stringnames": false,
    "frame_delay": 0,
    "time_scale": 1.0,
    "disable_vsync": false,
    "fixed_fps": 60 // Comment out this fixes it
},
{
    "name": "w/ DebugServer",
    "type": "godot",
    "request": "launch",
    "project": "${workspaceFolder}",
    "address": "127.0.0.1",
    "port": 6007,
    "debugServer": 6006, // Comment out this and the speed up occurs
    "profiling": false,
    "single_threaded_scene": false,
    "debug_collisions": false,
    "debug_paths": false,
    "debug_navigation": false,
    "debug_avoidance": false,
    "debug_stringnames": false,
    "frame_delay": 0,
    "time_scale": 1.0,
    "disable_vsync": false,
    "fixed_fps": 60,
}
```

**Comment by DaelonSuzuka** [comment]
Why are you specifying fixed_fps at all? (or frame_delay, or time_scale, or most of the others?) You shouldn't be using these flags unless you specifically need to.

This config only controls what flags are passed to the Godot executable, so if a certain combination of flags is producing undesirable behavior in your game, that sounds like an engine bug to me.

**Comment by Burloe** [comment]
I couldn't tell you frankly. I got the configs from some tutorial on how to setup VSC with Godot and I already deleted some but when I got one that worked, I just kept whatever was left when it worked. As far as I know, I only need everything between "name" and "DebugServer". Can I ask which ones you'd leave out?
