### ISSUE TITLE
Identifier xxx not declared in the current scope error shows when using the registered class in GDExtensions.

### ISSUE THREAD

**Issue by 949886** [godotengine/godot-vscode-plugin#718]
### Godot version

4.3.stable

### VS Code version

1.92.1

### Godot Tools VS Code extension version

2.1.0

### System information

win11

### Issue description

No error shows in Godot internal editor and the project works fine. These errors only show in vscode.

![image](https://github.com/user-attachments/assets/d577cbb0-2fb0-4b52-8781-de3c13517e78)
![image](https://github.com/user-attachments/assets/0fe118ea-be46-43d7-9ca0-355855dda1a4)
![image](https://github.com/user-attachments/assets/284c176f-e6de-41a0-a4bb-806bf2e2e21d)

### Steps to reproduce

1. Clone [sand-slide](https://github.com/kiwijuice56/sand-slide) project
2. Build with `scons` as README shows.
3. Open the game project and use vscode, errors will appear.

**Comment by DaelonSuzuka** [comment]
This extension has no control over that. The errors are provided by the Language Server, which is a component of the Godot Engine itself.
