### ISSUE TITLE
Configure font size of document

### ISSUE THREAD

**Issue by 1e0nhardt** [godotengine/godot-vscode-plugin#719]
### Godot version

4.3 stable

### VS Code version

1.91.1

### Godot Tools VS Code extension version

2.1.0

### System information

Window 10

### Problem statement

The default font size for documentation is slightly small.

### Proposed solution

Please provide a setting option to adjust the font size for documentation.

**Comment by DaelonSuzuka** [comment]
Implemented in #722:

![image](https://github.com/user-attachments/assets/261476f5-1d10-4a93-a6a6-33028d94254e)

**Comment by DaelonSuzuka** [comment]
@1e0nhardt This feature was just published in `2.3.0`. Please don't hesitate to open a new issue if you encounter problems or have another enhancement request.

**Comment by tyler-boyd** [comment]
@DaelonSuzuka I'm not sure if I'm just being an idiot, but that setting doesn't seem to do anything for me? The "Display Minimap" setting works fine, but I set "Page Scale" to 200% and it looks the same...

**Comment by xupisco** [comment]
> [@DaelonSuzuka](https://github.com/DaelonSuzuka) I'm not sure if I'm just being an idiot, but that setting doesn't seem to do anything for me? The "Display Minimap" setting works fine, but I set "Page Scale" to 200% and it looks the same...

Same here...
