### ISSUE TITLE
Add debuging support for GDScript

### ISSUE THREAD

**Issue by zero2000** [godotengine/godot-vscode-plugin#72]
hello, I use godot but it is not useful for its built-in editor, I would like to know if you plan to make the groups appear, as well as if you plan to implement the debug. to track the correct functioning of the scripts

**Comment by Geequlim** [comment]
There is the plan to implement the debugger in the future.

**Comment by Geequlim** [comment]
We can implement the gdscript [DAP](https://microsoft.github.io/debug-adapter-protocol) in the future to make it possiable.

**Comment by sprite-1** [comment]
It would really be nice to be able to launch and debug Godot projects straight from VS Code

**Comment by Calinou** [comment]
@sprite-1 Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by Mochnant** [comment]
Would this also cover being able to click on the Stack Frames when there is an error in Godot and have VS Code jump to the correct line?

**Comment by opensw** [comment]
+1 for this feature

**Comment by Calinou** [comment]
@opensw Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by Razoric480** [comment]
I've currently implemented the godot remote debugger into VSCode's DAP through Node ([video of it in action](https://cdn.discordapp.com/attachments/591191256319655958/678141502228135947/debug.mp4)), though it's not yet finished.

I figured the separation of concerns merited its own project rather than being folded into this one, which is about interaction with godot's language server, which the debugger doesn't do. But I wanted to hear what people thought, like @Geequlim who maintains the project.

**Comment by Geequlim** [comment]
@Razoric480 Look cool !
I'd like them could to be same plugin. Users who want to use vscode with godot can just install one plugin then just code and debug thier games. They don't need to know what the lsp or dap and they don't need to be confused with that.

**Comment by Geequlim** [comment]
@Razoric480 I think @Faless is refacting the gdscript debugger. You'd better let him know that.

**Comment by Razoric480** [comment]
Okay. I'll see about integrating my work into a fork of this and make a PR, when it's done.

And I only interact with the remote debugger, so if the TCP/IP signals it sends out are the same, then it should work the same. I'll still keep an eye out for any changes on the engine side in case of conflicts.

**Comment by Faless** [comment]
@Razoric480 messages are mostly the same for now, I added a `set_pid` message for supporting multisession debugging from godot editor.
But I'm actually hoping to change and normalize them a bit, see godotengine/godot#36244.

@Geequlim supporting DAP like we do with LSP would be great, and could potentially be done as an EditorPlugin, in the long run, as a module or even in GDScript as I would like to expose the debugger(s) to scripting languages.

**Comment by Razoric480** [comment]
I'll be keeping an eye on that PR for the future, then!
