### ISSUE TITLE
Could not find base class "TileMapLayer"

### ISSUE THREAD

**Issue by faulknermano** [godotengine/godot-vscode-plugin#721]
### Godot version

Godot v4.3.stable

### VS Code version

1.93.1

### Godot Tools VS Code extension version

2.1.0

### System information

Godot v4.3.stable - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6081) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

When I run the Godot Tools Debugger, in a TSCN where I only have one Node2D and a script attached that extends from `TileMapLayer` I get:
```
Exception has occurred.
Parser Error: Could not find base class "TileMapLayer".
```
This does not happen when I run it from Godot itself; it only happens in VS Code.

### Steps to reproduce

- Open a blank scene.
- Create a `Node2D`
- Attach a script onto the `Node2D` and give it any name.
- Copy-paste the following
```
extends TileMapLayer

func _ready() -> void:
    pass
```
- Save your scene.
- Set up the GT Debugger so that you run your scene.
- Debug.

You will see the error.

**Comment by DaelonSuzuka** [comment]
I would guess that VSCode is trying to use an old Godot binary. Check that your `editorPath.godot4` is correct.

**Comment by faulknermano** [comment]
@DaelonSuzuka , thank you! That was it. Sorry for the noise!
