### ISSUE TITLE
Project is opened with lowercase drive letter

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot-vscode-plugin#726]
### Godot version

4.3, 4.4 dev2

### VS Code version

1.93.1

### Godot Tools VS Code extension version

2.2.0

### System information

Windows 10

### Issue description

When opening project with VS Code, seems like the argument passed to `--path` has lowercase drive letter (e.g. `c:` instead of `C:`). I was not able to 100% confirm it, because I don't know how to check the exact command used to run project. But doing `ProjectSettings.globalize_path("res://")` will return path with lowercase drive.

I originally reported it as Godot bug:
https://github.com/godotengine/godot/issues/97147

https://private-user-images.githubusercontent.com/2223172/369533462-04078e55-af61-459e-b873-ca7e658f5798.mp4

### Steps to reproduce

1. Open workspace with Godot Editor
2. Print project path or use FileDialog
3. Absolute paths will have lowercase drive letter

**Comment by DaelonSuzuka** [comment]
Fixed in #727, but I'm not sure when the next release will be published.

**Comment by KoBeWi** [comment]
Well I'll use the CI build until then.

**Comment by DaelonSuzuka** [comment]
@KoBeWi  FYI the fix for this was just published in `2.3.0`.
