### ISSUE TITLE
Intellisense for declaring built in functions

### ISSUE THREAD

**Issue by James-Pickett** [godotengine/godot-vscode-plugin#73]
When using the built-in Godot editor, you get intellisense when declaring new function for godot's built in functions.

![image](https://user-images.githubusercontent.com/8415811/42738853-d09a7180-883f-11e8-9865-87add64ab06b.png)

But in VS Code with the plug-in you don't. =(

![image](https://user-images.githubusercontent.com/8415811/42738868-1a2ee0ba-8840-11e8-8706-c96db9de1cae.png)

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the release page
