### ISSUE TITLE
Pressing tab with auto-indent on from the beginning of a line indents too far in some cases

### ISSUE THREAD

**Issue by ther0n** [godotengine/godot-vscode-plugin#74]
When pressing tab from the beginning of a new line following the 4 lines of code below, auto-indent will indent by 2 tabs instead of 1 as expected.
 
```gdscript
func test():        
    if 1 == 1:
        print("1 = 1")
    print("Test")
```

![2018-07-20_16-29-35](https://user-images.githubusercontent.com/5874301/43023835-31e657a8-8c3a-11e8-960f-632de266da7d.gif)

**Comment by Calinou** [comment]
@ther0n Can you still reproduce this on [Godot 3.2 beta3](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-3) and the latest version of this add-on?

**Comment by ther0n** [comment]
I don't have Godot 3.2 yet, does that affect the extension in some way? I did just test it with the example code I provided. Pressing enter with the cursor at the end of the `print("Test")` line indents the newline correctly. If I delete the indents on the new line and press tab it still indents too far same as what happens in the gif.

**Comment by ther0n** [comment]
I didn't realize that the Godot 3.2 beta had language server support and that I had to manually install the 1.0.0 beta of this plugin. Just updated both and the issue does seem to be fixed!
