### ISSUE TITLE
When debugging, if a breakpoint is hit global_mouse_position uses system mouse position and not where mouse was in game window

### ISSUE THREAD

**Issue by Echofiend** [godotengine/godot-vscode-plugin#747]
### Godot version

4.3.stable

### VS Code version

1.95.1

### Godot Tools VS Code extension version

2.3.0

### System information

Linux Mint 21.3 Cinnamon

### Issue description

When debugging an issue finding the custom data for a tileset, setting a breakpoint before the get_global_mouse_position() call will use the current system mouse position when stepping through the code. In order to capture the games knowledge of the mouse the breakpoint must be set after you get the mouse position.

### Steps to reproduce

Create a scene with TileMapLayer and Tileset added
Attach script to TileMapLayer

```
func _input(event: InputEvent) -> void:
	if Input.is_action_just_pressed("click"):
		var mouse_pos:Vector2 = get_global_mouse_position()
		var tile_mouse_pos:Vector2i = local_to_map(mouse_pos)
		
		var tile_data:TileData = get_cell_tile_data(tile_mouse_pos)

		if tile_data:
			var custom_data:bool = tile_data.get_custom_data(CUSTOM_DATA)
			if custom_data:
				set_cell(tile_mouse_pos, SOURCE_ID, PLACEHOLDER_TEXT, 1)
			else:
				print("no custom data here")
		else:
			print("no tile data here")
```
place break point at 
`var mouse_pos:Vector2 = get_global_mouse_position()`
step through and you will get the system mouse position(if you have moved the mouse since execution pause)

stop debug
move breakpoint to next code line
step through and you will capture the position of the game mouse

**Comment by DaelonSuzuka** [comment]
How is this related to VSCode?

**Comment by DaelonSuzuka** [comment]
> This might be how it is handled in Godot **but I am not sure of that**.

Why would you not be sure of that? Why wouldn't you run the same scenario using just the Godot Editor _before_ typing all this up?
