### ISSUE TITLE
Functions seem to attach themselves to each other.

### ISSUE THREAD

**Issue by untmdsprt** [godotengine/godot-vscode-plugin#75]
![image](https://user-images.githubusercontent.com/10523925/44551972-59927d80-a6ee-11e8-8ebf-bdd8a268c81a.png)

The line on the leftmost side never seems to break between functions or a function followed by something else. It does break when other items follow each other. I've had to include a "#" at the end of the function to force it to stop. If you want to insert something between functions, it seems to make the new item a part of the top one instead of being its own thing on a new line.

Is this something that can be fixed? This happens in both Windows and Mac versions of VS Code.

**Comment by Calinou** [comment]
@untmdsprt Can you still reproduce this on [Godot 3.2 beta3](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-3) and the latest version of this add-on?

**Comment by DaelonSuzuka** [comment]
I don't think this happens anymore:

![image](https://github.com/godotengine/godot-vscode-plugin/assets/18042232/a28d3944-f961-4d4d-8599-e48858a5e22b)
