### ISSUE TITLE
Missing docs for VBoxContainer and HBoxContainer

### ISSUE THREAD

**Issue by st22nestrel** [godotengine/godot-vscode-plugin#753]
### Godot version

4.3.stable

### VS Code version

1.95.2

### Godot Tools VS Code extension version

2.3.0

### System information

Windows 10

### Issue description

Displaying documentation for `VBoxContainer` and `HBoxContainer` does not work, it displays this: 
![image](https://github.com/user-attachments/assets/41ba166b-234b-418b-9966-44b43c0fac4a)
Expected output is the documentation page for the `VBoxContainer`. This page is present in the Godot 4.3 editor.

Possibly documentation for other types might be broken, but so far I've only found a problem with these 2 types.

### Steps to reproduce

1. Create new `VBoxContainer` or `HBoxContainer` variable:
```
var container = VBoxContainer.new()
```
2. Use ctrl+LMB to click on the `VBoxContainer` in order to show documentation

Alternatively this issue can be reproduced by clicking on link to `VBoxContainer` or `HBoxContainer` inside documention for `BoxContainer`.

**Comment by DaelonSuzuka** [comment]
Thanks for the report!
