### ISSUE TITLE
Debugging is broken (Extension has been abandoned?)

### ISSUE THREAD

**Issue by oncoremarco** [godotengine/godot-vscode-plugin#757]
### Godot version

v4.3.stable.mono.official [77dcf97d8]

### VS Code version

1.95.3

### Godot Tools VS Code extension version

v2.3.0

### System information

Windows 10

### Issue description

Attempting to run the debugger using the "Play In Editor" button does not work, and has never worked, resulting in Godot having no functional C# debugger. I have been trying since version 4.1 and have never had a functioning debugger, leading me to believe this extension has been fully abandoned by the developer. 

### Steps to reproduce

Install Extension
"Show Run and Debug"
Create json file using option "Godot C#"
Insert the godot executable path into the correct slots
"Play in Editor"

The editor will never be opened from VS Code. Nothing will happen.

**Comment by DaelonSuzuka** [comment]
Lol.
