### ISSUE TITLE
Intellisense doesn't work under wayland when using Godot's LSP

### ISSUE THREAD

**Issue by meelkor** [godotengine/godot-vscode-plugin#758]
### Godot version

4.3.stable, 4.4.dev (0c45ace15)

### VS Code version

1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6)

### Godot Tools VS Code extension version

2.3.0, 6ddf05d4a1ead249161f27dbb7a1e4b4d7cfd1d5

### System information

Linux x64 6.11.9-arch1-1, sway

### Issue description

When running code & godot natively on wayland, the language service (as in go to definition, show variable type etc.) doesn't work.

For example on method/var mouse over it only shows `Loading...` tooltip indefinitely.
<img src=https://github.com/user-attachments/assets/8669e5bd-8282-42ed-b42f-66974429e3ae width=400>

Or when trying "go to navigation" it only starts the loading animation but nothing happens.

The language server seems to be connected just fine:
<img src=https://github.com/user-attachments/assets/b40263be-c2d0-4a7d-87c6-492987b0ab5a width=400>

--

**When using headless child process LSP, the intellisense works just fine.**
Also on the same setup it works completely fine in both following cases:
- running x11 window manager (i3)
- on wayland, but running both godot and code using xwayland (once either of the apps is runing natively on wayland, it no longer works)

The native support for wayland was added only recently [(4.3)](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-3/#wayland-support-for-linux) to godot, so who knows whether it's on the godot's or the extension's side.

I've tried to go through logs but didn't find anything relevant. Godot LSP says just:
```
2024-11-23 16:25:31.340 [info] attempting to connect to LSP at 127.0.0.1:6005
2024-11-23 16:25:31.340 [info] connected to LSP at 127.0.0.1:6005
```

I'll try to resolve the issue but any insight to what may be the cause would be helpful. Also it would be lovely to find out whether the extension works for other wayland/sway users or it's a me problem.

### Steps to reproduce

1. run sway window manager
2. run godot and open some project
3. run code with the extension and try to got to some method's definition

**Comment by atirut-w** [comment]
This is very strange. I use both on GNOME Wayland all the time and there were no problems.

**Comment by meelkor** [comment]
@atirut-w And your Godot editor has the Prefer Wayland (`run/platforms/linuxbsd/prefer_wayland`) option On? If so, then there's gotta be something strange with my setup...

**Comment by HolonProduction** [comment]
That's a problem exclusive to Sway:
- Godot Bug Report: https://github.com/godotengine/godot/issues/96942
- Godot PR with potential fix: https://github.com/godotengine/godot/pull/97480

**Comment by meelkor** [comment]
Aah, thank you very much for referncing the PR, will try it out. Closing this.
