### ISSUE TITLE
Format max empty lines between functions

### ISSUE THREAD

**Issue by harlig** [godotengine/godot-vscode-plugin#762]
### Godot version

4.4.dev5

### VS Code version

1.95.3

### Godot Tools VS Code extension version

2.3.0

### System information

macOS 15.1.1

### Problem statement

With the change [added here](https://github.com/godotengine/godot-vscode-plugin/issues/612), it'd be nice to have a formatter option to enforce 2 blank lines between functions.

### Proposed solution

![Image](https://github.com/user-attachments/assets/dbc6a045-2c0a-48f0-b67f-95fcdf5e85aa)

An extra checkbox here of `Enforce empty lines between functions` which, on format, will ensure all func definitions have exactly 2 blank lines between, removing/adding newlines as necessary.

**Comment by DaelonSuzuka** [comment]
Adding newlines is like ten times harder than removing them, so this isn't really on the agenda.
