### ISSUE TITLE
Incorrect warning in string with ellipsis

### ISSUE THREAD

**Issue by cmbarnett87** [godotengine/godot-vscode-plugin#83]
The following command mistakenly identifies 2 errors:
$Host_UI/Label.text = "...while White is working left to right."

**Errors Reported:**
': or \' expected at end of the line.
Expected indented block after expression

**Comment by Yagich** [comment]
the reason this seems to be happening is because some keywords such as if, while etc dont ignore strings, very annoying indeed 😞

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
