### ISSUE TITLE
Better Project Documentation

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot-vscode-plugin#85]
I saw in your TODO that you wanted Markdown rendered to HTML with mermaid support. SO I thought it might be helpful to point you to my project. I managed to get all of those requirements working and on readthedocs.io. The [repository documentation is here](https://gitlab.com/FeralBytes/FreecoiL/tree/finish/networking_basics/docs). Fair warning in the next day or two I will be merging this branch so instead [the documentation will be here](https://gitlab.com/FeralBytes/FreecoiL/tree/develop/docs) but right this second those are not as good as the new documentation I worked on. It should be an easy copy and paste from my repo to yours.

**Comment by minkir014** [comment]
I don't understand you. Do you want to say that these features are working or you want them to work?

**Comment by FeralBytes** [comment]
They do work.

**Comment by Geequlim** [comment]
With godot 3.2 you can dump your workspace symbols and documentations to json.
Then you can render your project api documentations to web pages via something like readthedocs.
