### ISSUE TITLE
Feature Request: Document Formatting

### ISSUE THREAD

**Issue by brogan89** [godotengine/godot-vscode-plugin#86]
Hey thanks for the awesome extension!
I'm wondering how formatting can be hooked up? I'm thinking because its going to be pretty much the same as .py files is there way to trick vscode into thinking .gd files are .py files for formatting?

Thanks in advance

**Comment by mikevaleriano** [comment]
Making the extension use autopep8 (or other formatter) instead of adding a custom formatting to the extension?

**Comment by mikevaleriano** [comment]
Okay, I managed to get this particular thing done using another extension and autopep8.

You need the [Run on Save extension](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) and [autopep8](https://pypi.org/project/autopep8/) on your path.

Next, add the following config on your vscode settings:

```json
"emeraldwalk.runonsave": {
    "commands": [
      {
        "match": ".gd",
        "isAsync": false,
        "cmd": "autopep8 --in-place --aggressive --aggressive ${file}"
      }
    ]
  },
```

It works perfectly.

**Comment by brogan89** [comment]
oh yea that does work really well. Thanks for that :)

**Comment by Razoric480** [comment]
In the meantime, there is a python-based [formatter for GDScript](https://marketplace.visualstudio.com/items?itemName=Razoric.gdscript-toolkit-formatter) on the marketplace.

**Comment by DaelonSuzuka** [comment]
As of `2.0.0`, this extension now its own GDscript formatter.
