### ISSUE TITLE
Can I have keyboard commands for more things?

### ISSUE THREAD

**Issue by alienbogart** [godotengine/godot-vscode-plugin#95]
I use the Vim mode for VSCode, and I much prefer using the keyboard than the mouse. But there's some stuff I can do with the keyboard. For example, when I put the mouse on a keyword, it shows the documentation.

**Comment by Soaku** [comment]
Hovering keywords is a feature provided by VSCode and you can assign a keyboard shortcut to it. Open up keyboard shortcuts in the command palette, then search for "Show Hover" (`editor.action.showHover`). 

Though the plugin itself could get some more commands too. Currently there are only two, "Run workspace as Godot project" and "Open workspace with Godot Editor". Those don't even seem to be working properly. They open a title-less file manager dialog with unknown purpose (should I open a workspace folder or the Godot executable?). A "connect/reconnect" command is missing.

**Comment by Calinou** [comment]
Closing, as keyboard shortcuts are already implemented.

Please open new issues you have *actionale* ideas for keyboard shortcuts to be added (along with suggestions for defaults).

> A "connect/reconnect" command is missing.

See https://github.com/godotengine/godot-vscode-plugin/pull/317.
