### ISSUE TITLE
Feature request: IntelliSense autocomplete for function parameters

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot-vscode-plugin#96]
Example:

When writing

```
func test_func(parameter_a, parameter_b):
    paramet
```

the autocomplete should suggest parameter_a and parameter_b.

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
