### ISSUE TITLE
[Enhancement] Syntax coloring: add option to color all variables, not only their definition

### ISSUE THREAD

**Issue by StragaSevera** [godotengine/godot-vscode-plugin#97]
Currently Godot Tools do recognize variable definition:
![](https://i.imgur.com/dhE9gwS.png)
But they does not recognize using this variable in the code below:
![](https://i.imgur.com/f9cCpmi.png)
It would be great if there was an option to color not only the definition, but all mentions of the variables.

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
Can you try does the new version fixed the problem ?

You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)

**Comment by Calinou** [comment]
In Godot Tools 1.0.0, variables appear to take the same identifier color as usual:

![image](https://user-images.githubusercontent.com/180032/66577621-055c8e00-eb7a-11e9-8b63-fd0da22b8242.png)

**Comment by Calinou** [comment]
Closing, as the current behavior seems to be correct. Note that third-party syntax themes may negatively impact syntax highlighting quality (depending on how well they're made). If you want comprehensive syntax highlighting, it's best to stick to the default Dark+ and Light+ themes.
