### ISSUE TITLE
False positive warning: "constant is never used"

### ISSUE THREAD

**Issue by StragaSevera** [godotengine/godot-vscode-plugin#98]
Godot Tools tell me that the JUMP_SPEED constant is never used:
![](https://i.imgur.com/f9bEw4P.png)
But it is clearly used below:
![](https://i.imgur.com/qI99RZZ.png)
I tried to update workspace symbols, but the problem still stands. Please, help!

**Comment by Geequlim** [comment]
The new version fixed the problem and will be published when godot 3.2 RC release.

**Comment by Geequlim** [comment]
I'm closing this as the new version has fixed this issue.
You can try the new version of the plugin with godot 3.2 from the [release page](https://github.com/godotengine/godot-vscode-plugin/releases)
